### ISSUE TITLE
UTF-8 Error

### ISSUE THREAD

**Issue by ixelizm** [flet-dev/flet#1000]
I'm getting utf8 errors in the message input fields, is there a way to fix it?

If I enter the letters ğ, Ğ, ç, Ç, ş, Ş, ü, Ü, ö, Ö, ı, İ, it gives this error
```
Exception in thread Thread-176 (print_output):
	Traceback (most recent call last):
		File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
		self.run()
		File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
		self._target(*self._args, **self._kwargs)
		File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\flet\flet.py", line 572, in print_output
		line = line.decode("utf-8").rstrip("\r\n")
			   ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 3: invalid start byte 
```

**Comment by ixelizm** [comment]
edit so the error message can be read

**Comment by ixelizm** [comment]
I noticed that when I run it using flet I get the same error.

**Comment by FeodorFitsner** [comment]
@ixelizm can you give me please a source code reproducing the issue?

**Comment by ixelizm** [comment]
code is ok i am using a simple textfield but when i start it with flet app.py -r -p 5000 utf8 errors occur

**Comment by FeodorFitsner** [comment]
You can try the fix with pre-release version of Flet module:

```
pip install flet --upgrade --pre
```

Let me know how it worked.
