### ISSUE TITLE
Error running tutorial async-apps code in Window10

### ISSUE THREAD

**Issue by jsjk01** [flet-dev/flet#1221]
**Description**

**Code example to reproduce the issue:**

```python
import flet as ft

async def main(page: ft.Page):
    await page.add_async(ft.Text("Hello, async world!"))

ft.app(main)
```
Code from the official website [flet - async-apps](https://flet.dev/docs/guides/python/async-apps) , When I run the code, it reports an error
```shell
Traceback (most recent call last):
  File "D:\...\use_flet.py", line 380, in <module>
    ft.app(main)
  File "D:\...\lib\site-packages\flet\flet.py", line 78, in app
    auth_token=auth_token,
  File "D:\...\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "D:\...\lib\site-packages\flet\flet.py", line 224, in app_async
    conn.page_url, assets_dir, view == FLET_APP_HIDDEN
  File "D:\...\site-packages\flet\flet.py", line 514, in open_flet_view_async
    await asyncio.create_subprocess_exec(args[0], *args[1:], env=flet_env),
  File "D:\...\lib\asyncio\subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "D:\...\lib\asyncio\base_events.py", line 1544, in subprocess_exec
    bufsize, **kwargs)
  File "D:\...\lib\asyncio\base_events.py", line 462, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```shell
Name: flet
Version: 0.4.2                                                                                            
Summary: Flet for Python - easily build interactive multi-platform apps in Python                         
Home-page:                                                                                                
Author: Appveyor Systems Inc.                                                                             
Author-email: hello@flet.dev                                                                              
License: Apache-2.0                                                                                       
Location: d:\...\lib\site-packages                             
Requires: flet-core, httpx, oauthlib, packaging, typing-extensions, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:
Windows 10 Enterprise Edition LTSC 21H2

**Additional environment details:**
`python3.7.16`

**Comment by jsjk01** [comment]
use `python code_file.py` got the error, but use `flet run code_file.py` it works.

**Comment by FeodorFitsner** [comment]
Look at this SO thread: https://stackoverflow.com/questions/44633458/why-am-i-getting-notimplementederror-with-async-and-await-on-windows

Looks like it's Python 3.7 specific issue. Try adding this in the beginning of your program:

```python
asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
```
