### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'Thread-5' in package auth

### ISSUE THREAD

**Issue by Jose427** [flet-dev/flet#1273]
**Description**

RuntimeError when i run "Sign in with OAuth provider" from example https://flet.dev/docs/guides/python/authentication
It fails for Flet 0.4.0 and later versions
It works with Flet 0.3.2

I tested with Github and Google, and python 3.9 and python 3.10

**Code example to reproduce the issue:**

https://flet.dev/docs/guides/python/authentication

import os

import flet as ft
from flet.auth.providers.github_oauth_provider import GitHubOAuthProvider

def main(page: ft.Page):

    provider = GitHubOAuthProvider(
        client_id=os.getenv("GITHUB_CLIENT_ID"),
        client_secret=os.getenv("GITHUB_CLIENT_SECRET"),
        redirect_url="http://localhost:8550/api/oauth/redirect",
    )

    def login_click(e):
        page.login(provider)

    def on_login(e):
        print("Access token:", page.auth.token.access_token)
        print("User ID:", page.auth.user.id)

    page.on_login = on_login
    page.add(ft.ElevatedButton("Login with GitHub", on_click=login_click))

ft.app(target=main, port=8550, view=ft.WEB_BROWSER)

**Describe the results you received:**

Traceback (most recent call last):
  File "C:\Users\myuser\anaconda3\envs\condalogin\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\myuser\anaconda3\envs\condalogin\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "d:\Prog\Pry\Login Google\main.py", line 21, in login_click
    page.login(provider)
  File "C:\Users\myuser\anaconda3\envs\condalogin\lib\site-packages\flet_core\page.py", line 526, in login
    self.__authorization = authorization(
  File "C:\Users\myuser\anaconda3\envs\condalogin\lib\site-packages\flet\auth\authorization.py", line 32, in __init__
    self.__async_lock = asyncio.Lock()
  File "C:\Users\myuser\anaconda3\envs\condalogin\lib\asyncio\locks.py", line 81, in __init__
    self._loop = events.get_event_loop()
  File "C:\Users\myuser\anaconda3\envs\condalogin\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-5'.

**Describe the results you expected:**

No error

**Additional information you deem important (e.g. issue happens only occasionally):**

I use conda

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.5.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: c:\users\jacs5\anaconda3\envs\condalogin\lib\site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:

Windows 11

**Additional environment details:**
dependencies:
  - anyio=3.6.2=pyhd8ed1ab_0
  - beartype=0.13.0=pyhd8ed1ab_0
  - blinker=1.6.1=pyhd8ed1ab_0
  - boltons=23.0.0=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39ha55989b_1005
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.12.7=h5b45459_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h68f70e3_3
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=23.3.1=py39hcbf5309_0
  - conda-package-handling=2.0.2=pyh38be061_0
  - conda-package-streaming=0.7.0=pyhd8ed1ab_1
  - cryptography=40.0.1=py39hb6bd5e6_0
  - flet=0.5.0=pyhd8ed1ab_0
  - flet-core=0.5.0=pyhd8ed1ab_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=py39hcbf5309_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=0.16.3=pyhd8ed1ab_0
  - httpx=0.23.3=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - libffi=3.4.2=h8ffe710_5
  - libsqlite=3.40.0=hcfcfb64_0
  - libzlib=1.2.13=hcfcfb64_4
  - menuinst=1.4.19=py39hcbf5309_1
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=3.1.0=hcfcfb64_0
  - packaging=23.0=pyhd8ed1ab_0
  - pip=23.0.1=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - pycosat=0.6.4=py39ha55989b_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.9.16=h4de0772_0_cpython
  - python_abi=3.9=3_cp39
  - pyyaml=6.0=py39ha55989b_5
  - repath=0.9.0=pyhd8ed1ab_0
  - requests=2.28.2=pyhd8ed1ab_1
  - rfc3986=1.5.0=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py39ha55989b_3
  - ruamel.yaml.clib=0.2.7=py39ha55989b_1
  - setuptools=67.6.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - vc=14.3=hb6edc58_10
  - vs2015_runtime=14.34.31931=h4c5c07a_10
  - watchdog=2.2.1=py39hcbf5309_0
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - websockets=10.4=py39h2bbff1b_1
  - wheel=0.40.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zstandard=0.19.0=py39h95af829_1
  - zstd=1.5.2=h12be248_6

**Comment by FeodorFitsner** [comment]
It's been fixed in Flet pre-release: https://pypi.org/project/flet/0.6.0.dev1298/
You can install the latest pre-release with `pip install flet --pre --upgrade`.
