### ISSUE TITLE
Bug (in packaged app only): Unsupported command: getUploadUrl

### ISSUE THREAD

**Issue by clstaudt** [flet-dev/flet#1278]
**Description**

The following error appears only after the app is packaged using `flet pack`. It does not appear when testing the app via the Python interpreter.

**Code example to reproduce the issue:**

Using this branch:
https://github.com/tuttle-dev/tuttle/tree/dev-packaging

1. Package via script using `flet pack` command: `python scripts/pack_app.py`
2. Run the resulting executable:`./dist/Tuttle` 
3. Try uploading a new profile picture for the user.

**Describe the results you received:**

```
2023-04-11 13:29:42.631 | ERROR    | __main__:upload_file_callback:135 - Exception @app.upload_file_callback raised during file upload Exception
2023-04-11 13:29:42.631 | ERROR    | __main__:upload_file_callback:138 - Unsupported command: getUploadUrl
Traceback (most recent call last):

  File "threading.py", line 973, in _bootstrap

  File "threading.py", line 1016, in _bootstrap_inner

  File "threading.py", line 953, in run

  File "flet_core/event_handler.py", line 28, in __sync_handler

  File "tuttle/app/auth/view.py", line 514, in on_profile_photo_picked
    upload_url = self.upload_file_callback(file)
                 │    │                    └ FilePickerFile(name='Screenshot 2023-04-10 at 09.22.03.png', path='/Volumes/Macintosh HD/Users/cls/Stack/Screenshot 2023-04-1...
                 │    └ <bound method TuttleApp.upload_file_callback of <__main__.TuttleApp object at 0x28551ba60>>
                 └ <tuttle.app.auth.view.ProfilePhotoContent object at 0x28559c8e0>

> File "app.py", line 125, in upload_file_callback
    upload_to = self.page.get_upload_url(file.name, 600)
                │    │    │              │    └ 'Screenshot 2023-04-10 at 09.22.03.png'
                │    │    │              └ FilePickerFile(name='Screenshot 2023-04-10 at 09.22.03.png', path='/Volumes/Macintosh HD/Users/cls/Stack/Screenshot 2023-04-1...
                │    │    └ <function Page.get_upload_url at 0x10f3f41f0>
                │    └ <flet_core.page.Page object at 0x28551aef0>
                └ <__main__.TuttleApp object at 0x28551ba60>

  File "flet_core/page.py", line 524, in get_upload_url

  File "flet_core/page.py", line 699, in _send_command

  File "flet/sync_local_socket_connection.py", line 112, in send_command

  File "flet_core/local_connection.py", line 92, in _process_command

Exception: Unsupported command: getUploadUrl
```

**Describe the results you expected:**

If not packaged with`flet pack`, the error does not occur.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Version: 0.5.1
```

**Operating system**:

macOS  13.3.1

**Additional environment details:**

**Comment by FeodorFitsner** [comment]
Let's discuss that here: https://github.com/flet-dev/flet/issues/1275#issuecomment-1503804098

**Comment by FeodorFitsner** [comment]
Close in favour of #1275
