### ISSUE TITLE
Tutorial app crashes on startup

### ISSUE THREAD

**Issue by tr31zh** [flet-dev/flet#1306]
**Description**
Tutorial app crashes on startup with console message related to flet module initialisation

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    # add/update controls on Page
    pass


ft.app(target=main)

```

**Describe the results you received:**
```shell
Traceback (most recent call last):
  File "/Users/mavi/Code/python/th_arabidopsis/scripts/flet.py", line 1, in <module>
    import flet as ft
  File "/Users/mavi/Code/python/th_arabidopsis/scripts/flet.py", line 4, in <module>
    def main(page: ft.Page):
AttributeError: partially initialized module 'flet' has no attribute 'Page' (most likely due to a circular import)
```

**Describe the results you expected:**
Tutorial output

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.5.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /Users/mavi/Code/python/th_arabidopsis/env/lib/python3.10/site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by: 
```

**Operating system**:
Mac M1 Ventura 13.0 (22A380)

**Additional environment details:**
Python 3.10.11

**Comment by tr31zh** [comment]
> Try renaming your script from flet.py to my app.py or something. flet.py cannot be used as you will fail the import of the real flet.

Thanks
