### ISSUE TITLE
Exception: Timeout waiting for invokeMethod clientStorage:set({'key': 'username', 'value': '"hello world"'}) call

### ISSUE THREAD

**Issue by Omer-Farooqui** [flet-dev/flet#1453]
**Description**

 I am trying to store a user's login credentials in the client storage, but when I try to do so I get a timeout error. I have tried reinstalling python, deleting all my packages and recreating my venv, trying an old version of flet and python. 
I've tried to run the script as administrator as well. 
**Code example to reproduce the issue:**

```python
import flet as ft
from flet import Page

def main(page: Page):
    t = ft.TextField()
    page.add(t)

    def set_client_storage(e):
        page.client_storage.set('username', t.value)
        print(page.client_storage.get('username'))

    page.add(ft.ElevatedButton(on_click=set_client_storage))

ft.app(target=main)

```

**Describe the results you received:**

 
```
Exception in thread Thread-27 (set_client_storage):
Traceback (most recent call last):
  File "C:\Users\Admin\scoop\apps\python\current\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\scoop\apps\python\current\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Admin\Coding_Projects\App\testfile.py", line 9, in set_client_storage
    page.client_storage.set('username', t.value)
  File "C:\Users\Admin\scoop\apps\python\current\Lib\site-packages\flet_core\client_storage.py", line 13, in set
    self.__page.invoke_method(
  File "C:\Users\Admin\scoop\apps\python\current\Lib\site-packages\flet_core\page.py", line 869, in invoke_method
    raise Exception(
Exception: Timeout waiting for invokeMethod clientStorage:set({'key': 'username', 'value': '"hi mom"'}) call 
```

**Describe the results you expected:**

 I expected the program to print whatever I put in the TextField after I click the button.

**Additional information you deem important (e.g. issue happens only occasionally):**

I told my friend to run the code on his pc but he doesn't seem to be getting the error.

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.7.4
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\Users\Admin\scoop\apps\python\current\Lib\site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:

 Windows 11

**Additional environment details:**

Running python 3.11.3

**Comment by ndonkoHenri** [comment]
Code:
```python
import flet as ft
from flet import Page


def main(page: Page):
    page.theme_mode = "light"

    t = ft.TextField()
    page.add(t)

    def set_client_storage(e):
        page.client_storage.set('username', t.value)
        page.add(ft.Text(page.client_storage.get('username')))

    page.add(ft.ElevatedButton(on_click=set_client_storage))


ft.app(target=main)
```


It worked normally with the above code. Flet v0.7.4
![image](https://github.com/flet-dev/flet/assets/98978078/67daab3e-598e-4cac-b3f3-37f9548fcf24)

**Comment by Omer-Farooqui** [comment]
Maybe I need to clear the locally stored credentials, do you know where they are stored?

**Comment by ndonkoHenri** [comment]
Instead of trying to delete the 'locally stored credentials', simply try to change the key: So, instead of `username` use something else.

My app aboves was running in a native browser window... and hat no errors. Still wondering what's the issue on your end.

My suggestion: create a new venv and retry

**Comment by Omer-Farooqui** [comment]
aaaaaa.. I've already tried all of that. I guess it's an OS related issue. I guess i'll change the name of the key for now.

**Comment by Omer-Farooqui** [comment]
Yeah, no luck trying to use a different key. i guess my only option is to reinstall my os :/
