### ISSUE TITLE
page.on_event: page error Converter Function Error: Null check operator used on a null value

### ISSUE THREAD

**Issue by xKristee29** [flet-dev/flet#1569]
I've encountered a problem when changing between routes, the app giving me this error:

```
2023-07-08 18:30:41,570:INFO - page.on_event: page error Converter Function Error: Null check operator used on a null value

#0      ControlChildrenViewModel.fromStore (package:flet/src/models/control_children_view_model.dart:16)
#1      _DropdownControlState.build.<anonymous closure> (package:flet/src/controls/dropdown.dart:71)
#2      _StoreStreamListenerState._createStream.<anonymous closure> (package:flutter_redux/flutter_redux.dart:550)
#3      _MapStream._handleData (dart:async/stream_pipe.dart:213)
#4      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123)
#9      _WhereStream._handleData (dart:async/stream_pipe.dart:195)
#10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#13     _DelayedData.perform (dart:async/stream_impl.dart:515)
#14     _PendingEvents.handleNext (dart:async/stream_impl.dart:620)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
```

It appears always on loading a new view

**Comment by xKristee29** [comment]
To be noted that when i clear a controls array and after i append another element it gives me this error

**Comment by FeodorFitsner** [comment]
Could you provide a repro code please?

**Comment by xKristee29** [comment]
```py
import flet as ft
from views.home import Home
from views.grupe import Grupe
from views.profil import Profil


class Router:
    def __init__(self, page: ft.Page):
        self.page = page
        self.routes = {
            '/': Home,
            '/prezenta': Home,
            '/grupe': Grupe,
            '/profil': Profil,
            '/abonament': Home
        }
        self.body = ft.ListView(controls=[], expand=1, spacing=10, padding=20, auto_scroll=False)

    def on_route_change(self, route):
        self.body.controls.clear()
        self.body.controls.append(self.routes[route.route](self.page))
        self.body.update()
```

**Comment by xKristee29** [comment]
This is the main.py
```py
import flet as ft

from modules.app_bar import AppBar
from modules.nav_bar import NavBar
from views.router import Router


def main(page: ft.Page):
    page.theme_mode = 'dark'
    page.title = "StarTrainer"

    page.appbar = AppBar(page)
    router = Router(page)
    page.navigation_bar = NavBar(page)

    page.on_route_change = router.on_route_change
    page.add(
        router.body
    )

    page.go('/')


ft.app(target=main, assets_dir="assets", web_renderer='html')
```

**Comment by xKristee29** [comment]
Everytime the on_route_change() function is called it strikes me with 5 of these errors

**Comment by ndonkoHenri** [comment]
Please can you provide a runnable/complete repro so we can better test?
