### ISSUE TITLE
flet pack 

### ISSUE THREAD

**Issue by nyano** [flet-dev/flet#1661]
When I use the example from https://flet.dev/docs/ "Counter" app and run the command "flet pack 123.py", the file 123.exe can run on the current device. However, when I try running the file on another computer, an error occurs.Why？
Use pyinstaller 123.py is same error
OS：windows 10

Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1283, in request
  File "http\client.py", line 1329, in _send_request
  File "http\client.py", line 1278, in endheaders
  File "http\client.py", line 1038, in _send_output
  File "http\client.py", line 976, in send
  File "http\client.py", line 1448, in connect
  File "http\client.py", line 942, in connect
  File "socket.py", line 827, in create_connection
  File "socket.py", line 962, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "123.py", line 806, in <module>
  File "flet_runtime\app.py", line 97, in app
  File "flet_runtime\app.py", line 178, in __app_sync
  File "flet_runtime\app.py", line 579, in open_flet_view
  File "flet_runtime\app.py", line 635, in __locate_and_unpack_flet_view
  File "flet_runtime\app.py", line 747, in __download_flet_client
  File "urllib\request.py", line 241, in urlretrieve
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

**Comment by nyano** [comment]
When I open 123.exe, it will connect to 185.199.109.133:443, maybe raw.githubusercontent.com
This device does not have Python. Do I need to download the runtime？
 why do I need to connect 185.199.109.133:443 when I open it? it's just an example
