### ISSUE TITLE
Page object passed to a class becoming None when using routing 

### ISSUE THREAD

**Issue by Soif2Sang** [flet-dev/flet#1758]
So I was using flet 0.7.4 and upgraded to 0.9.0 and now I cannot pass page object and use routing anymore at the same time because page object becomes None during the route change
```
import random
import threading
from time import sleep

import flet as ft
from flet_route import path, Routing


def testView(page: ft.Page, params, basket):
    return ft.View("/test", controls=[ft.Text("We're testing!"), ft.FilledButton("back", on_click=lambda _: page.go('/'))], )


def index(page: ft.Page, params, basket):
    return ft.View("/", controls=page.controls, )

class Test(ft.ListView):
    def __init__(self, page, **kwargs):
        super().__init__(**kwargs)
        self.page = page

        self.randomElementText = ft.Text()
        self.controls.append(self.randomElementText)

    def randomElement(self):
        self.randomElementText.value = self.page.list[random.randint(0, len(self.page.list))]
        self.page.update()
        sleep(1)
        return self.randomElement()

def main(page: ft.Page):

    page.app_routes = [
        path(
            url="/test",
            clear=True,
            view=testView
        ),
        path(
            url="/",
            clear=True,
            view=index
        )
    ]

    page.add(ft.Text(value="180"), ft.FilledButton("go /test", on_click=lambda _: page.go('/test')))



    page.routing = Routing(
        page=page,
        app_routes=page.app_routes,
    )

    page.list = [1,2,3,4,5]

    test_object = Test(page)
    page.add(test_object)
    threading.Thread(target=test_object.randomElement).start()

    page.go('/test')
    page.update()


if __name__ == "__main__":
    ft.app(target=main)
```
`Exception in thread Thread-3 (randomElement):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "", line 28, in randomElement
    return self.randomElement()
           ^^^^^^^^^^^^^^^^^^^^
  File "", line 25, in randomElement
    self.randomElementText.value = self.page.list[random.randint(0, len(self.page.list))]
                                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'list'`

**Comment by gbrandt** [comment]
I have seen this as well but could not come up with a stable repro.

**Comment by FeodorFitsner** [comment]
Page set to None when a control is removed from a sight/view. I will try to give you a working example later today or tomorrow.

**Comment by rkleivel** [comment]
I think the following code essentially reproduces the same issue.
```python
import flet as ft

class ProtectedContent(ft.Row):
    def _build(self):
        self.controls = [
            ft.Text("New Content")
        ]

class AccessControl(ft.Row):
    def _build(self):
        self.expand = True
        self.controls = [
            ft.Column(
                expand=True,
                controls=[
                    ft.Container(
                        expand=True,
                        content=ft.Text(value="Click button to add content...", expand=True, style=ft.TextThemeStyle.DISPLAY_SMALL),
                        alignment=ft.alignment.center,
                    ),
                    ft.Container(
                        expand=True,
                        content=ft.ElevatedButton(text="Click me", on_click=self.button_clicked,style=ft.ButtonStyle(padding=30)),
                        alignment=ft.alignment.center,
                    ),
                    
                ],
            )
        ]

    def button_clicked(self, e):
        self.page.controls[0] = ft.Text(value="...")
        x = ProtectedContent()
        self.page.add(x)
        self.page.update()
    
def main(page: ft.Page) -> None:
    access = AccessControl()
    page.add(access)

ft.app(target=main, view=ft.WEB_BROWSER)
```
When button is clicked the following error occurs in flet 0.9.0, while in 0.7.4 it worked fine:
```
Exception in thread Thread-11 (button_clicked):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/roald/BEAS/EDA/dash/dash.py", line 35, in button_clicked
    self.page.update()
AttributeError: 'NoneType' object has no attribute 'update'
```
What I notice is that self.page is set to `None` when content is added with `self.page.add(x)` in 0.9.0. In 0.7.4, however, `self.page` will exist and `self.page.controls` will now have 2 items as expected. 

Sidenote 1: the event object `e` passed to `button_clicked` does not lose it's page object
Sidenote 2: It turned out that I actually did not have to run `self.page.update()` to make the changes visible, so my workaround in this example was just to remove the `self.page.update()` to be able to continue with flet 0.9.0

**Comment by FeodorFitsner** [comment]
@rkleivel re: `AccessControl`/`ProtectedContent ` example - in button click handler, inside `AccessControl` you are, essentially, removing `AccessControl` control itself from a page (`self.page.controls[0] = ft.Text(value="...")` and then calling `self.page` of `AccessControl`, but it's `None`, because `self` is removed from a page.

If you want to make reusable controls then the control should not "know" anything about its containing page and its position within that page.

In your case I would add a click handler to `AccessControl` control and make an external code gluing to controls together.

**Comment by rkleivel** [comment]
@FeodorFitsner  - Hmm - yes - you're right that I'm actually removing `AccessControl`. 
But what is then the explanation that `self.page` becomes `None` and code crashes with the cited error in 0.9.0, but not in 0.7.4?

**Comment by FeodorFitsner** [comment]
Because it was working wrongly in 0.7.4. Once the control is removed from a page its reference to a page must be None.
Like now, inside control, you can check `self.page` to know whether it's shown on the page or not.

**Comment by Soif2Sang** [comment]
how can I solve my issues ? i need to access my page control from anywhere in my app at any time, I basically have jobs and some visual logging so i’ve got multiple threads updating and adding controls inside my page controls (not view control!)

**Comment by Soif2Sang** [comment]
There's another concern with this code: I'm unable to navigate back to the '/' page due to the 'page' being set to 'None'. Is it a necessity to detach the 'page' from any control when the route is changed? I can't figure out which benefit it gives:

```
import flet as ft
from flet_route import path, Routing


class MyContainer(ft.Container):
    def __init__(self, page):
        super().__init__()
        self.page = page

        self.page.app_routes.append(
            path(
                url="/test",
                clear=True,
                view=lambda page, params, basket: self.goTest(page, params, basket,)
            ),
        )

        self.content = ft.FilledButton("Go to /test", on_click=lambda _: self.page.go('/test'))

    def goTest(self, page, params, basket):
        self.page.window_width = 900
        self.page.window_height = 500

        return ft.View(route="/test", controls=[ft.Text("We are testing"), ft.FilledButton('go /', on_click=lambda _: self.returnHome())])

    def returnHome(self):
        self.page.window_width = 400
        self.page.window_height = 700
        self.page.go("/")

def index(page: ft.Page, params, basket):
    return ft.View("/", controls=page.controls, )

def main(page: ft.Page):


    page.app_routes = [
        path(
            url="/",
            clear=True,
            view=index
        )
    ]

    page.routing = Routing(
        page=page,
        app_routes=page.app_routes,
    )

    page.MyContainer = MyContainer(page)
    page.add(page.MyContainer)
    page.update()


if __name__ == "__main__":
    ft.app(target=main)
```

**Comment by Soif2Sang** [comment]
I figured out to fix my usecase I needed to use clear=False instead of True

**Comment by FeodorFitsner** [comment]
@Soif2Sang views are top level page's descendants. You can't have a container on a page and manipulate routes/views inside it. You can do just a "controller" class, not inherited from any control:

```python
import flet as ft
from flet_route import Routing, path


class MyApp:
    def __init__(self, page):
        self.page = page

        self.page.app_routes.append(
            path(
                url="/test",
                clear=True,
                view=lambda page, params, basket: self.goTest(
                    page,
                    params,
                    basket,
                ),
            ),
        )

        page.add(
            ft.FilledButton("Go to /test", on_click=lambda _: self.page.go("/test"))
        )

    def goTest(self, page, params, basket):
        self.page.window_width = 900
        self.page.window_height = 500

        return ft.View(
            route="/test",
            controls=[
                ft.Text("We are testing"),
                ft.FilledButton("go /", on_click=lambda _: self.returnHome()),
            ],
        )

    def returnHome(self):
        self.page.window_width = 400
        self.page.window_height = 700
        self.page.go("/")


def index(page: ft.Page, params, basket):
    return ft.View(
        "/",
        controls=page.controls,
    )


def main(page: ft.Page):
    page.app_routes = [path(url="/", clear=True, view=index)]

    page.routing = Routing(
        page=page,
        app_routes=page.app_routes,
    )

    MyApp(page)


if __name__ == "__main__":
    ft.app(target=main)
```
