### ISSUE TITLE
Hot Reload in the `flet run --android command` only observes the main.py file

### ISSUE THREAD

**Issue by nascin** [flet-dev/flet#1759]
**Description**
The hot reload in the `flet run --android` command only observes the main.py file, when the change is in another file, the screen update is only done after going back to the main.py file and saving.

**Operating system**:
Windows

**Comment by rkleivel** [comment]
What if you add `-d` => `flet run -d --android` ? Doesn't that work with the --android switch?

**Comment by nascin** [comment]
I tested it now, it doesn't work

**Comment by rkleivel** [comment]
Hmm...
From `flet run --help`:
```
  -d, --directory       watch script directory
  -r, --recursive       watch script directory and all sub-directories recursively
```
`-d` should do the job if the file you edit is in same directory as your main.py
`-r` should do it if your file is in a subdirectoy
Did you also test `-r`?

**Comment by nascin** [comment]
It didn't work either, I tried running something like `flet run -r --android`

**Comment by FeodorFitsner** [comment]
You should use `flet run -r -d --android` to watch entire directory recursively.

**Comment by nascin** [comment]
@FeodorFitsner, I tried the suggested command, but the following error occurred.

```
(_env) PS C:\projetos\flet\app_nascin_cripto\app-nascin-cripto> flet run -r -d --android
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\projetos\flet\app_nascin_cripto\_env\Scripts\flet.exe\__main__.py", line 7, in <module>
  File "C:\projetos\flet\app_nascin_cripto\_env\Lib\site-packages\flet\cli\cli.py", line 81, in main
    args.handler(args)
  File "C:\projetos\flet\app_nascin_cripto\_env\Lib\site-packages\flet\cli\commands\run.py", line 150, in handle
    my_event_handler = Handler(
                       ^^^^^^^^
  File "C:\projetos\flet\app_nascin_cripto\_env\Lib\site-packages\flet\cli\commands\run.py", line 213, in __init__
    self.start_process()
  File "C:\projetos\flet\app_nascin_cripto\_env\Lib\site-packages\flet\cli\commands\run.py", line 223, in start_process
    p_env["FLET_PAGE_NAME"] = "/".join(Path(self.script_path).parts[-2:])
                                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\pathlib.py", line 871, in __new__
    self = cls._from_parts(args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\pathlib.py", line 509, in _from_parts
    drv, root, parts = self._parse_args(args)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\pathlib.py", line 493, in _parse_args
    a = os.fspath(a)
        ^^^^^^^^^^^^
```
