### ISSUE TITLE
pretty_errors is not working with flet

### ISSUE THREAD

**Issue by Soif2Sang** [flet-dev/flet#1767]
I've got the latest flet and i'm trying the pretty_errors module but it doesn't seems to work.. the exception raised are not modified by pretty_errors

**Comment by Soif2Sang** [comment]
```
import pretty_errors
import flet as ft

def main(page: ft.Page):
    raise ZeroDivisionError

ft.app(main)
``` 
raises 
```
Unhandled error processing page session : Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/flet_runtime/app.py", line 358, in on_session_created
    session_handler(page)
  File "pretty_errors_flet.py", line 5, in main
    raise ZeroDivisionError
ZeroDivisionError
``` 
instead of 
```
-------------------------------------------------------------------------------
pretty_errors_flet.py 7 <module>
main()

pretty_errors_flet.py 5 main
raise ZeroDivisionError

ZeroDivisionError
```

**Comment by FeodorFitsner** [comment]
It would be more helpful if you raise this issue in [PrettyErrors repository](https://github.com/onelivesleft/PrettyErrors/). Honestly, I don't think it's Flet's issue.
