### ISSUE TITLE
User assets are not detected

### ISSUE THREAD

**Issue by srang992** [flet-dev/flet#1780]
While using the recent release of flet with FastAPI, it seems that ***flet_fastapi.app()*** can't detect the `assets` directory. Here is the code in which I am testing.

**test.py**
```
import flet as ft
import flet_fastapi


async def main(page: ft.Page):
    page.fonts = {
        "Courgette": "/fonts/Courgette-Regular.ttf"
    }
    page.vertical_alignment = ft.MainAxisAlignment.CENTER
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
    
    await page.add_async(
        ft.Text("Welcome to Flet, FastAPI!", size=40, font_family="Courgette")
    )
    
    
app = flet_fastapi.app(main, assets_dir="./assets")
```

**main.py**
```
import uvicorn

if __name__ == '__main__':
    uvicorn.run("counter:app", port=8900, reload=True)
```
I am running the app using **main.py** script. I previously tried with the string "assets" in the **assets_dir** parameter of `flet_fastapi.app()`, but still giving the error saying "assets_dir must be absolute path".

**error`**
```
INFO:     Will watch for changes in these directories: ['D:\\FletFastAPI']
INFO:     Uvicorn running on http://127.0.0.1:8900 (Press CTRL+C to quit)
INFO:     Started reloader process [15944] using StatReload
INFO:     Started server process [15812]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:60426 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\FletFastAPI\.venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\FletFastAPI\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\FletFastAPI\.venv\lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "D:\FletFastAPI\.venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\FletFastAPI\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\FletFastAPI\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\FletFastAPI\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\FletFastAPI\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\FletFastAPI\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\FletFastAPI\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\FletFastAPI\.venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\FletFastAPI\.venv\lib\site-packages\starlette\routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "D:\FletFastAPI\.venv\lib\site-packages\flet_fastapi\flet_static_files.py", line 64, in __call__
    await self.__once.do(self.__config, scope["root_path"])
  File "D:\FletFastAPI\.venv\lib\site-packages\flet_fastapi\once.py", line 13, in do
    await func(*args, **kwargs)
  File "D:\FletFastAPI\.venv\lib\site-packages\flet_fastapi\flet_static_files.py", line 100, in __config
    raise Exception("assets_dir must be absolute path.")
Exception: assets_dir must be absolute path.
```
If I am making any mistake, I am happy to hear.

**Comment by ndonkoHenri** [comment]
From the error message, seems like `assets_dir must be absolute path.`
Try with one, and let's see.

**Comment by ndonkoHenri** [comment]
For simplicity, you can also use this:
`assets_dir=str(Path(__file__).resolve().parent.joinpath("assets"))`

**Comment by srang992** [comment]
> For simplicity, you can also use this:
> 
> ```python
> from pathlib import Path
> ...
> ...
> app = flet_fastapi.app(main, assets_dir=str(Path(__file__).resolve().parent.joinpath("assets")))
> ```

Yes, it worked. But isn't it too long to define a path. Is there any easy alternative?

**Comment by srang992** [comment]
> From the error message, seems like `assets_dir must be absolute path.` Try with one.

what do you mean by **try with one**?

**Comment by ndonkoHenri** [comment]
I meant, try using an absolute path to your `assets_dir` as mentioned in the error message.

**Comment by ndonkoHenri** [comment]
An alternative (not that shorter though) is using: 

```py
app = flet_fastapi.app(main, assets_dir=str(Path(__file__).resolve().parent /"assets"))
```

**Comment by FeodorFitsner** [comment]
The reason it requires absolute path is because it is hard to determine the location of "main" script from within `app()` function when run with `uvicorn` or other web server. For regular `python <script.py>` [this method worked](https://github.com/flet-dev/flet/blob/main/sdk/python/packages/flet-runtime/src/flet_runtime/utils.py#L150), but how to determine script location for `uvicorn <script>:app`?.. We could do resolve relatively to a current dir though, but what would be the current dir when running in a Docker container?..
