### ISSUE TITLE
I can't build a flet application using nuitka

### ISSUE THREAD

**Issue by NamerPolice** [flet-dev/flet#1854]
run this python -m nuitka --onefile --disable-console --windows-icon-from-exe=icon.ico .\test.py
i get error 
Nuitka-Scons:INFO: Compiled 622 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 621
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
Nuitka-Reports:INFO: Compilation report written to file 'nuitka-crash-report.xml'.
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\__main__.py", line 155, in <module>
    main()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\__main__.py", line 141, in main
    MainControl.main()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\MainControl.py", line 1093, in main
    _main()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\MainControl.py", line 984, in _main
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\PostProcessing.py", line 317, in executePostProcessing
    executePostProcessingResources(manifest=manifest, onefile=False)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\PostProcessing.py", line 260, in executePostProcessingResources
    res_copied = copyResourcesFromFileToFile(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\utils\WindowsResources.py", line 243, in copyResourcesFromFileToFile
    res_data = getResourcesFromDLL(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\utils\WindowsResources.py", line 105, in getResourcesFromDLL
    raise ctypes.WinError()
OSError: [WinError 193] %1 is not a valid Win32 application.
Nuitka-Reports:INFO: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.

if run python -m nuitka --onefile --disable-console  .\test.py NO PROBLEM! pls help

**Comment by NamerPolice** [comment]
need change window flet icon with nuitka
everything works out if you use command pack, but I need nuitka for protection

**Comment by NamerPolice** [comment]
![image](https://github.com/flet-dev/flet/assets/63663636/0877a163-1e83-4844-9d21-fd020a28d473)
how to change this with nuitka ???
