### ISSUE TITLE
Flet raises NotImplemented error when trying to access client storage

### ISSUE THREAD

**Issue by seriaati** [flet-dev/flet#1886]
**Description**

When trying to access `page.client_storage`, flet raises a `NotImplemented` error.
The app is using asyncio.

**Code example to reproduce the issue:**

```python
async def main(page: ft.Page):
    contains_key = page.client_storage.contains_key("key")
```

**Describe the results you received:**

```
Unhandled error processing page session 0177bbbf-e9fe-4be0-b83b-636f69d8d88a: Traceback (most recent call last):
  File "C:\Users\seria\source\repos\tuan-tuan\.venv\Lib\site-packages\flet_runtime\app.py", line 443, in on_session_created
    await session_handler(page)
  File "c:\Users\seria\source\repos\tuan-tuan\run_web_app.py", line 224, in main
    await page.go_async("/login")
  File "C:\Users\seria\source\repos\tuan-tuan\.venv\Lib\site-packages\flet_core\page.py", line 539, in go_async
    await self.__on_route_change.get_handler()(
  File "C:\Users\seria\source\repos\tuan-tuan\.venv\Lib\site-packages\flet_core\event_handler.py", line 43, in __async_handler
    await h(r)
  File "c:\Users\seria\source\repos\tuan-tuan\run_web_app.py", line 141, in on_route_change
    if page.client_storage.contains_key("authenticated"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\seria\source\repos\tuan-tuan\.venv\Lib\site-packages\flet_core\client_storage.py", line 46, in contains_key
    self.__page.invoke_method(
  File "C:\Users\seria\source\repos\tuan-tuan\.venv\Lib\site-packages\flet_core\page.py", line 889, in invoke_method
    result = self._send_command(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\seria\source\repos\tuan-tuan\.venv\Lib\site-packages\flet_core\page.py", line 730, in _send_command
    return self.__conn.send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\seria\source\repos\tuan-tuan\.venv\Lib\site-packages\flet_core\connection.py", line 21, in send_command
    raise NotImplementedError()
NotImplementedError
```

**Describe the results you expected:**

I should be able to access the client storage normally, just like how the session storage worked.

**Additional information you deem important (e.g. issue happens only occasionally):**
None

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.10.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\Users\seria\source\repos\tuan-tuan\.venv\Lib\site-packages
Requires: copier, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:

Windows

**Additional environment details:**

**Comment by ndonkoHenri** [comment]
You are in `async` mode, so you have to use `contains_key_async` instead of `contains_key`.
