### ISSUE TITLE
`ListView` throws `RangeError` when items exceed an unknown boundary

### ISSUE THREAD

**Issue by Soif2Sang** [flet-dev/flet#1922]
**Description**

It's been a month my users complains about the UI stops freshing after some time, I got few customers that also noticed by spamming the start/pause ubtton they can make the UI stops freshing which I hope they are the same bug so here am I provided a code reproduction that can make the same issue happen, I'm personnally UNABLE to make it freeze on my computer but few customers can. Just spam start/pause and wait until the apps stop getting refreshed

**Code example to reproduce the issue:**

```python
import sys
import threading
from time import sleep

import flet as ft

class Logger(ft.ListView):
    def __init__(self,frame,page,**kwargs):
        super().__init__(**kwargs)
        self.auto_scroll = True
        self.parent = frame
        self.initial_page = page

    def add_text(self, texte:str, color=None):
        if color is None:
            text = ft.Text(value=texte,weight=ft.FontWeight.W_600, selectable=True)
        else:
            text = ft.Text(value=texte, weight=ft.FontWeight.W_600, color=color, selectable=True)
        self.controls.append(text)
        self.initial_page.update()

    def add_divider(self):
        self.controls.append(ft.Divider())
        self.initial_page.update()


class Frame(ft.Tabs):
    def __init__(self, page, number: str, **kwargs):
        super().__init__(**kwargs)
        self.number = number
        self.settings = ft.Tabs()
        self.expand = True
        self.logger = Logger(self, page)

        self.tabs.append(ft.Tab(content=self.logger, text="Logs"))


    def add_text(self, texte: str, color=None):
        self.logger.add_text(texte, color)

    def add_divider(self):
        self.logger.add_divider()



class Task():
    def __init__(self, tile):
        self.tile = tile
    
    def script_pause(self):
        said = False

        while self.tile.paused:
            if not said:
                self.set_text(f"Script is paused.", "orange")
                said = True

        if self.tile.stopped:
            self.set_text(f"You stopped the bot", "Red")
            self.set_divider()
            sys.exit()

        if said:
            self.set_text(f"You resumed the script.", "Green")

    def run(self):
        while 1:
            self.script_pause()
            sleep(0.001)

    def set_text(self, param, param1):
        self.tile.logs.controls.append(ft.Text(value=param, color=param1))
        self.tile.initial_page.update()

    def set_divider(self):
        self.tile.logs.controls.append(ft.Divider())
        self.tile.initial_page.update()



class Tile(ft.Row):
    def __init__(self, page, logs, **kwargs):
        super().__init__(**kwargs)
        self.initial_page = page
        self.tasks_process = None
        self.logs = logs
        self.paused = False
        self.stopped = False

        self.main_task = Task(self)

        self.tasks_process = threading.Thread(target=self.main_task.run)

        self.button_start = ft.IconButton(
            icon=ft.icons.NOT_STARTED_OUTLINED,
            on_click=self.start
        )
        self.button_stop = ft.IconButton(
            icon=ft.icons.STOP_OUTLINED,
            disabled=True,
            on_click=self.stop
        )


        self.alignment = ft.MainAxisAlignment.SPACE_BETWEEN
        self.controls.extend([
            ft.Row(
                controls=[
                    self.button_start,
                    self.button_stop
                ]
            ),
        ]
        )


    def start(self, e):
        self.button_start.icon = ft.icons.PAUSE
        self.button_stop.disabled = False

        self.paused = False
        self.stopped = False

        self.initial_page.update()
        self.start_tasks()
        self.button_start.on_click = self.pause
        self.tasks_process.join()
        self.button_start.on_click = self.start
        self.paused = False
        self.stopped = False
        self.button_start.icon = ft.icons.NOT_STARTED_OUTLINED
        self.button_stop.disabled = True
        self.initial_page.update()


    def resume(self, e):
        self.paused = False

        self.button_start.icon = ft.icons.PAUSE
        self.initial_page.update()
        self.button_start.on_click = self.pause

    def pause(self, e):
        self.paused = True

        self.button_start.icon = ft.icons.NOT_STARTED_OUTLINED
        self.initial_page.update()
        self.button_start.on_click = self.resume

    def stop(self, e):
        self.stopped = True
        self.paused = False
        self.button_start.icon = ft.icons.NOT_STARTED_OUTLINED
        self.button_stop.disabled = True
        self.initial_page.update()

    def start_tasks(self):
        if not self.tasks_process.is_alive():
            self.tasks_process = threading.Thread(target=self.main_task.run)
            self.tasks_process.start()
        else:
            print("Task is frozen, you may need to restart the bot.")



def main(page: ft.Page):


    frame = Frame(page, '1')
    tile = Tile(page, frame.logger)


    page.add(tile, frame)
    page.update()


if __name__ == "__main__":
    ft.app(main)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.10.3
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\Users\user\Documents\Projet\Rise of kingdom\Bluestacks Version\bot\.venv\Lib\site-packages
Requires: copier, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by: flet-route
```

**Operating system**:

WIndows from 10 to 11

**Additional infos**:

Issue also appears on lower flet versions

**Comment by Soif2Sang** [comment]
By the way, switching between tabs is still working fine, hovering button is still working, but clicking on anything that leads to update something will simply doesn't update the UI

**Comment by oSquat** [comment]
I am able to reproduce this with Flet 10.1 and Python 3.9.2 on Linux. 

Does this have more to do with appending a large number of items self.title.logs.controls? After limiting the list length the problem no longer occurred. See the example snippet below. I don't have time to test it now, but the UI begins to lag once the list grows so long and I wonder if limiting the number of times you call .update() would also resolve this. Like, if update were called in an async loop.

    def set_text(self, param, param1):
        self.tile.logs.controls.insert(0, ft.Text(value=param, color=param1))
        if len(self.tile.logs.controls) > 25:
            del self.tile.logs.controls[25:]
        self.tile.initial_page.update()

**Comment by Soif2Sang** [comment]
First of all thanks for the response, unfortunately the issue also appears when i'm limiting the logs up to 200 lines

**Comment by SKbarbon** [comment]
Hey @Soif2Sang ,
Can you tell me the purpose of this code? I think your approach for the purpose may contain unsafe-thread implementation.

**Comment by Soif2Sang** [comment]
@SKbarbon
let me put a bit more context to it,
So thé code I provided is a simplier version of my main app, the app controls multiple emulators that are performing tasks that needs to be logged for the user experience, but recently the app started to get freeze performing the task, I was not able to reproduce it effectively but some users noticed that if thé logger is not in the page.controls (or view) the app does not get any freeze, then few noticed that spamming start/pause with the logger on the page can also cause this issue. Note that freeze can appear from 15minutes to 10s of hours depending on the user. So here am I giving a code reproduction that can lead to this issue

**Comment by ndonkoHenri** [comment]
I caught this while in dev-mode: 
```bash
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError: Invalid value: Not in inclusive range 0..453: 454
```
Seems like the listview items exceed some boundary.
Related SO Thread: https://stackoverflow.com/questions/53967624/flutter-error-rangeerror-index-invalid-value-not-in-range-0-2-inclusive

Will try to come up with a fix..

**Comment by FeodorFitsner** [comment]
@ndonkoHenri did you get more detailed exception log?

**Comment by ndonkoHenri** [comment]
Here:
```bash
flutter: Button _4 clicked!
flutter: WS message: {"action":"pageControlsBatch","payload":[{"action":"updateControlProps","payload":{"props":[{"i":"_4","icon":"not_started_outlined"}]}}]}
flutter: Row build: _3
flutter: IconButton build: _4
flutter: IconButton build: _5
flutter: Button _4 clicked!
flutter: WS message: {"action":"pageControlsBatch","payload":[{"action":"updateControlProps","payload":{"props":[{"i":"_4","icon":"pause"}]}}]}
flutter: WS message: {"action":"pageControlsBatch","payload":[{"action":"addPageControls","payload":{"controls":[{"t":"text","i":"_464","p":"_8","c":[],"at":"455","color":"Green","value":"You resumed the script."}],"trimIDs":[]}}]}
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError: Invalid value: Not in inclusive range 0..454: 455
#0      List.insert (dart:core-patch/growable_array.dart:11:7)
#1      addControls (package:flet/src/reducers.dart:423:17)
#2      appReducer (package:flet/src/reducers.dart:336:9)
#3      Store._createReduceAndNotify.<anonymous closure> (package:redux/src/store.dart:235:28)
#4      Store.dispatch (package:redux/src/store.dart:267:27)
#5      FletServer._onMessage (package:flet/src/flet_server.dart:265:16)
#6      FletWebSocketServerProtocol._onMessage (package:flet/src/flet_server_protocol_web_socket.dart:56:14)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#11     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
#12     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#17     _StreamController._add (dart:async/stream_controller.dart:658:7)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#22     _StreamController._add (dart:async/stream_controller.dart:658:7)
#23     _StreamController.add (dart:async/stream_controller.dart:606:5)
#24     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#30     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332:23)
#31     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#33     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#37     _StreamController._add (dart:async/stream_controller.dart:658:7)
#38     _StreamController.add (dart:async/stream_controller.dart:606:5)
#39     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
#40     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#43     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#44     _StreamController._add (dart:async/stream_controller.dart:658:7)
#45     _StreamController.add (dart:async/stream_controller.dart:606:5)
#46     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
#47     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by FeodorFitsner** [comment]
There is a racing condition. While the page update is in progress (`.update()` is running), it calculates the diff and sends to UI, etc.) and adding a new control to the list interferes with `.update()`. That's why, on Flutter side, it tries to insert it on 455 position ("at":"455") which is greater than the length of the list.

Flet UI is not thread-safe. Thread-safe UI would mean it's locked on update of any attribute/list of any control, every time
or, in ideal world, `.update()` should be immediate.
 
Solution? Lock!

A few suggestions how to make your Flet code more maintainable and reusable:

**Do not pass `Page` instance into control**

You don't need to (should not) do that:

```py
class Logger(ft.ListView):
    def __init__(self, frame, page, **kwargs):
        super().__init__(**kwargs)
        self.initial_page = page
        ...
```

Once control is added to the page its instance could be accessed via `self.page`.

```py
class Logger(ft.ListView):
    def __init__(self, frame, **kwargs):
        super().__init__(**kwargs)
        ...

    def before_update(self):
        self.page # it's set to an owning Page instance
```

**Do not update page or any parent controls from inside a control**

Instead of this:

```py
    def add_divider(self):
        self.controls.append(ft.Divider())
        self.initial_page.update()
```

do this:

```py
    def add_divider(self):
        self.controls.append(ft.Divider())
        self.update()
```

Control should know nothing about "outside" world and it should not modify that "outside" world directly.

If you need to "tell" something to control parents use events. Parent control can pass a method reference into child control (event handler), for example:

```py
class Logger(ft.ListView):
    def __init__(self, on_control_change):
        super().__init__()
        self.on_control_change = on_control_change

    def do_somthing(self):
        # ...
        # notify outside world
        self.on_control_change()

logger = Logger(lambda: print("Something happened inside logger!"))
```

**Make control isolated**

```py
class Logger(ft.ListView):

    ...

    def is_isolated(self) -> bool:
        return True
```

That means any call to `page.update()` will not include changes inside the control. You should explicitly update control with `mycontrol.update()` or from inside control `self.update()`.

**Use encapsulation**

Do not expose the internals of control and do not assume you know how it's made inside.

Like, by calling `self.tile.logs.controls.append()` outside control you *know* that it's inherited from `ListView` and has `controls` list. That breaks encapsulation principle. Today it's `controls`, tomorrow it's something else.

Control should expose methods and properties that define its allowed behaviour. Use `self.title.logs.add_text()` everywhere in the program, and only that.

**Use locks to synchronize access from multiple threads and prevent happy-clicking**

As we provide access to a control via methods and properties only (previous section) we can **guard** those methods and properties with locks or other synchronization mechanisms.

The final look of `Logger` class with locks is:

```py
class Logger(ft.ListView):
    def __init__(self, frame, **kwargs):
        super().__init__(**kwargs)
        self.__lock = Lock()
        self.auto_scroll = True
        self.parent = frame

    def add_text(self, texte: str, color=None):
        with self.__lock:
            if color is None:
                text = ft.Text(value=texte, weight=ft.FontWeight.W_600, selectable=True)
            else:
                text = ft.Text(
                    value=texte,
                    weight=ft.FontWeight.W_600,
                    color=color,
                    selectable=True,
                )
            self.controls.append(text)
            self.update()

    def add_divider(self):
        with self.__lock:
            self.controls.append(ft.Divider())
            self.update()

    def is_isolated(self) -> bool:
        return True
```

Entire program:

```py
import sys
import threading
from threading import Lock
from time import sleep

import flet as ft


class Logger(ft.ListView):
    def __init__(self, frame, **kwargs):
        super().__init__(**kwargs)
        self.__lock = Lock()
        self.auto_scroll = True
        self.parent = frame

    def add_text(self, texte: str, color=None):
        with self.__lock:
            if color is None:
                text = ft.Text(value=texte, weight=ft.FontWeight.W_600, selectable=True)
            else:
                text = ft.Text(
                    value=texte,
                    weight=ft.FontWeight.W_600,
                    color=color,
                    selectable=True,
                )
            self.controls.append(text)
            self.update()

    def add_divider(self):
        with self.__lock:
            self.controls.append(ft.Divider())
            self.update()

    def is_isolated(self) -> bool:
        return True


class Frame(ft.Tabs):
    def __init__(self, page, number: str, **kwargs):
        super().__init__(**kwargs)
        self.number = number
        self.settings = ft.Tabs()
        self.expand = True
        self.logger = Logger(self)

        self.tabs.append(ft.Tab(content=self.logger, text="Logs"))

    def add_text(self, texte: str, color=None):
        self.logger.add_text(texte, color)

    def add_divider(self):
        self.logger.add_divider()


class Task:
    def __init__(self, tile):
        self.tile = tile

    def script_pause(self):
        said = False

        while self.tile.paused:
            if not said:
                self.set_text(f"Script is paused.", "orange")
                said = True

        if self.tile.stopped:
            self.set_text(f"You stopped the bot", "Red")
            self.set_divider()
            sys.exit()

        if said:
            self.set_text(f"You resumed the script.", "Green")

    def run(self):
        while 1:
            self.script_pause()
            sleep(0.001)

    def set_text(self, text, color):
        self.tile.logs.add_text(text, color)

    def set_divider(self):
        self.tile.logs.add_divider()


class Tile(ft.Row):
    def __init__(self, logs, **kwargs):
        super().__init__(**kwargs)
        self.tasks_process = None
        self.logs = logs
        self.paused = False
        self.stopped = False

        self.main_task = Task(self)

        self.tasks_process = threading.Thread(target=self.main_task.run)

        self.button_start = ft.IconButton(
            icon=ft.icons.NOT_STARTED_OUTLINED, on_click=self.start
        )
        self.button_stop = ft.IconButton(
            icon=ft.icons.STOP_OUTLINED, disabled=True, on_click=self.stop
        )

        self.alignment = ft.MainAxisAlignment.SPACE_BETWEEN
        self.controls.extend(
            [
                ft.Row(controls=[self.button_start, self.button_stop]),
            ]
        )

    def start(self, e):
        self.button_start.icon = ft.icons.PAUSE
        self.button_stop.disabled = False

        self.paused = False
        self.stopped = False

        self.update()
        self.start_tasks()
        self.button_start.on_click = self.pause
        self.tasks_process.join()
        self.button_start.on_click = self.start
        self.paused = False
        self.stopped = False
        self.button_start.icon = ft.icons.NOT_STARTED_OUTLINED
        self.button_stop.disabled = True
        self.update()

    def resume(self, e):
        self.paused = False

        self.button_start.icon = ft.icons.PAUSE
        self.update()
        self.button_start.on_click = self.pause

    def pause(self, e):
        self.paused = True

        self.button_start.icon = ft.icons.NOT_STARTED_OUTLINED
        self.update()
        self.button_start.on_click = self.resume

    def stop(self, e):
        self.stopped = True
        self.paused = False
        self.button_start.icon = ft.icons.NOT_STARTED_OUTLINED
        self.button_stop.disabled = True
        self.update()

    def start_tasks(self):
        if not self.tasks_process.is_alive():
            self.tasks_process = threading.Thread(target=self.main_task.run)
            self.tasks_process.start()
        else:
            print("Task is frozen, you may need to restart the bot.")


def main(page: ft.Page):

    frame = Frame(page, "1")
    tile = Tile(frame.logger)

    page.add(tile, frame)


if __name__ == "__main__":
    ft.app(main)
```

You can use diff to see what changed.
