### ISSUE TITLE
WindowDragArea can not close maximize

### ISSUE THREAD

**Issue by NjustWrun** [flet-dev/flet#1982]
The example of WindowDragArea say:
maximizable
Whether double-clicking on a window drag area causes window to maximize/restore. Default is True.

I tried turning off maximization but it didn't work.
How can I turn off the double-click maximize of WindowDragArea.

my code is :

def main(page: ft.Page):
    page.window_title_bar_hidden = True
    page.window_title_bar_buttons_hidden = True
    s = ft.WindowDragArea(
        ft.Container(
            ft.Text("Drag this area to move, maximize and restore application window."),
            bgcolor=ft.colors.AMBER_300,
            padding=10,
        ),
        expand=True,
    )
    s.maximizable = False
    page.add(
        ft.Row(
            [
                s,
                # ft.IconButton(ft.icons.CLOSE, on_click=lambda _: page.window_close()),
            ]
        )
    )

ft.app(target=main)

**Comment by NjustWrun** [comment]
def main(page: ft.Page):
    page.window_title_bar_hidden = True
    page.window_title_bar_buttons_hidden = True
    s = ft.WindowDragArea(
        ft.Container(
            ft.Text("Drag this area to move, maximize and restore application window."),
            bgcolor=ft.colors.AMBER_300,
            padding=10,
        ),
        expand=True,
        maximizable=False,
    )
I added maximizable to the constructor and the error message is as follows

Unhandled error processing page session : Traceback (most recent call last):
  File "C:\Users\TR\AppData\Local\pypoetry\Cache\virtualenvs\milet-JvxaWHZV-py3.10\lib\site-packages\flet\flet.py", line 302, in on_session_created
    session_handler(page)
  File "D:\associated-file\milet\test.py", line 7, in main
    s = ft.WindowDragArea(
TypeError: WindowDragArea.__init__() got an unexpected keyword argument 'maximizable'

**Comment by ndonkoHenri** [comment]
Can you move to the latest flet version and try again?
