### ISSUE TITLE
import error after pip install flet

### ISSUE THREAD

**Issue by ipconfiger** [flet-dev/flet#200]
```
╰─$ python app.py                    
Traceback (most recent call last):
  File "/Users/alex/Projects/testspace/flex_test/app.py", line 1, in <module>
    import flet
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/site-packages/flet/__init__.py", line 1, in <module>
    from flet.alert_dialog import AlertDialog
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/site-packages/flet/alert_dialog.py", line 3, in <module>
    from beartype import beartype
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/site-packages/beartype/__init__.py", line 59, in <module>
    from beartype._decor.main import beartype
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/site-packages/beartype/_decor/main.py", line 22, in <module>
    from beartype.typing import TYPE_CHECKING
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/site-packages/beartype/typing/__init__.py", line 329, in <module>
    from beartype.typing._typingpep544 import (
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/site-packages/beartype/typing/_typingpep544.py", line 35, in <module>
    from beartype._util.cache.utilcachecall import callable_cached
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/site-packages/beartype/_util/cache/utilcachecall.py", line 33, in <module>
    from beartype._util.func.arg.utilfuncargtest import (
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/site-packages/beartype/_util/func/arg/utilfuncargtest.py", line 16, in <module>
    from beartype._util.func.utilfunccodeobj import get_func_codeobj
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/site-packages/beartype/_util/func/utilfunccodeobj.py", line 19, in <module>
    from beartype._data.datatyping import Codeobjable, TypeException
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/site-packages/beartype/_data/datatyping.py", line 85, in <module>
    BeartypeReturn = Union[BeartypeableT, BeartypeConfedDecorator]
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/typing.py", line 262, in inner
    return func(*args, **kwds)
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/typing.py", line 339, in __getitem__
    return self._getitem(self, parameters)
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/typing.py", line 451, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/typing.py", line 231, in _remove_dups_flatten
    return tuple(_deduplicate(params))
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/typing.py", line 205, in _deduplicate
    all_params = set(params)
TypeError: unhashable type: 'list'
```

**Comment by FeodorFitsner** [comment]
This issue was reported before: https://github.com/flet-dev/flet/issues/69 and it's something with first versions of Python 3.9. Upgrading to the latest 3.9.x or 3.10 fixes it.
