### ISSUE TITLE
flet create fails on Windows with error: git clone failed due to Filename too long

### ISSUE THREAD

**Issue by Code4SAFrankie** [flet-dev/flet#2215]
**Description**

Trying to run `flet create` to test Android functionality as per documentation, but it fails with a git clone error due to a filename being too long.

**Code example to reproduce the issue:**

`flet create my-app`

**Describe the results you received:**

Got this error:

```
C:\f>flet create my-app
git clone failed with error: Cloning into 'flet-app-templates'...
warning: unable to access 'flet_build/{{cookiecutter.out_dir}}/android/app/src/main/kotlin/{{ cookiecutter.org_name.replace('.', cookiecutter.sep) }}{{ cookiecutter.sep }}{{ cookiecutter.project_name }}{{ cookiecutter.sep }}/.gitattributes': Filename too long
error: unable to create file flet_build/{{cookiecutter.out_dir}}/android/app/src/main/kotlin/{{ cookiecutter.org_name.replace('.', cookiecutter.sep) }}{{ cookiecutter.sep }}{{ cookiecutter.project_name }}{{ cookiecutter.sep }}/MainActivity.kt: Filename too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


Traceback (most recent call last):
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\WPy64-39100\python-3.9.10.amd64\Scripts\flet.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\site-packages\flet\cli\cli.py", line 81, in main
    args.handler(args)
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\site-packages\flet\cli\commands\create.py", line 58, in handle
    cookiecutter(
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\site-packages\cookiecutter\main.py", line 80, in cookiecutter
    base_repo_dir, cleanup_base_repo_dir = determine_repo_dir(
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\site-packages\cookiecutter\repository.py", line 107, in determine_repo_dir
    cloned_repo = clone(
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\site-packages\cookiecutter\vcs.py", line 103, in clone
    subprocess.check_output(  # nosec
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/flet-dev/flet-app-templates.git']' returned non-zero exit status 128.
```

**Describe the results you expected:**

Expected it to create a flet template to run on Android

**Additional information you deem important (e.g. issue happens only occasionally):**

`git clone https://github.com/flet-dev/flet-app-templates.git` works when I execute that separately.

**Flet version (`pip show flet`)**:

```
0.15.0
```

**Operating system**:

**Additional environment details:**

Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32

**Comment by Code4SAFrankie** [comment]
Hi

Tried `C:\Users\User>flet create my-app` as opposed to `c:\f`. Gave the same error.

**Comment by sergiopalbau** [comment]
i have the same issue, :(

**Comment by FeodorFitsner** [comment]
What version of git do you have?

**Comment by FeodorFitsner** [comment]
And what OS is that?

**Comment by FeodorFitsner** [comment]
Can confirm the issue exists. Looking into that.

**Comment by FeodorFitsner** [comment]
It should be fixed now.

**Comment by capey0** [comment]
Nope not fixed ... I get it with version 23.0

**Comment by Niki-Huang** [comment]
Hello，the problem still exists

**Comment by abdu12347** [comment]
download python version 3.12.7  or up

**Comment by Michal-Mikolas** [comment]
Hello, I also have this problem. Python 3.12.9 on Windows 10.

**Comment by ndonkoHenri** [comment]
Please open a new issue with the details.
