### ISSUE TITLE
when start with AppView.FLET_APP_WEB, unable to use page.window_center(), unable to change window size

### ISSUE THREAD

**Issue by mcjoshua110** [flet-dev/flet#2250]
C:\Python\Python11\python11.exe C:\Users\Administrator\PycharmProjects\MyFletApp\tests\t5.py 
Unhandled error processing page session 968abe3a-d35e-4e1a-9860-737aff571ca4: Traceback (most recent call last):
  File "C:\Python\Python11\Lib\site-packages\flet_runtime\app.py", line 454, in on_session_created
    await session_handler(page)
  File "C:\Users\Administrator\PycharmProjects\MyFletApp\tests\t5.py", line 12, in main
    page.window_center()
  File "C:\Python\Python11\Lib\site-packages\flet_core\page.py", line 1116, in window_center
    self.update()
  File "C:\Python\Python11\Lib\site-packages\flet_core\page.py", line 290, in update
    r = self.__update(self)
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python11\Lib\site-packages\flet_core\page.py", line 419, in __update
    results = self.__conn.send_commands(self._session_id, commands).results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python11\Lib\site-packages\flet_core\connection.py", line 27, in send_commands
    raise NotImplementedError()
NotImplementedError

**Comment by ndonkoHenri** [comment]
Please share some repro code to test.
