### ISSUE TITLE
When the starting view type is AppView.FLET_APP_WEB, it cannot be started after packaging. May I ask what the problem is？

### ISSUE THREAD

**Issue by mcjoshua110** [flet-dev/flet#2253]
When the starting view type is AppView.FLET_APP_WEB, it cannot be started after packaging. May I ask what the problem is？

`
import asyncio
import flet as ft
from flet_core.types import AppView

class Countdown(ft.UserControl):

    def __init__(self, seconds):
        super().__init__()
        self.seconds = seconds

    async def did_mount_async(self):
        self.running = True
        asyncio.create_task(self.update_timer())

    async def will_unmount_async(self):
        self.running = False

    async def update_timer(self):
        while self.seconds and self.running:
            mins, secs = divmod(self.seconds, 60)
            self.countdown.value = "{:02d}:{:02d}".format(mins, secs)
            await self.update_async()
            await asyncio.sleep(1)
            self.seconds -= 1

    def build(self):
        self.countdown = ft.Text()
        return self.countdown

async def main(page: ft.Page):

    bt = ft.ElevatedButton("aaa", on_click=lambda _: page.launch_url("http://127.0.0.1:8002/index.html"))

    await page.add_async(Countdown(120), Countdown(60), bt)

if __name__ == '__main__':
    ft.app(
        target=main,
        port=8002,
        assets_dir='assets',
        view=AppView.FLET_APP_WEB,
    )`

**packing code:**
`flet pack test.py`

**Error log**

Traceback (most recent call last):
  File "test.py", line 47, in <module>
  File "flet_runtime\app.py", line 81, in app
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "flet_runtime\app.py", line 224, in app_async
  File "flet_runtime\app.py", line 427, in __connect_internal_async
  File "flet_runtime\app.py", line 549, in __start_flet_server
Exception: Web root path not found: C:\Users\Administrator\AppData\Local\Temp\_MEI245642\flet\web

**Comment by FeodorFitsner** [comment]
`flet pack` is not intended for packaging Flet app as a web.

`flet build web` is coming (before the end of this year) which will be producing a static website.

**Comment by FeodorFitsner** [comment]
or what's your scenario here, what would you like to achieve?

**Comment by mcjoshua110** [comment]
After running business tasks on the APP, an HTML report will be generated.
I hope that through the internal web service of the APP, they can access the reports generated by the APP through URLs and web pages

**Comment by ndonkoHenri** [comment]
https://docs.flet.dev/publish/
