### ISSUE TITLE
Exception: Could not connected to Flet server in 30 seconds.

### ISSUE THREAD

**Issue by Ilian445** [flet-dev/flet#2325]
Traceback (most recent call last):
  File "/root/workapp/main.py", line 326, in <module>
    flet.app(target=sign, view=WEB_BROWSER, port=44)
  File "/usr/local/lib/python3.10/dist-packages/flet_runtime/app.py", line 97, i                                                                                        n app
    __app_sync(
  File "/usr/local/lib/python3.10/dist-packages/flet_runtime/app.py", line 134,                                                                                         in __app_sync
    conn = __connect_internal_sync(
  File "/usr/local/lib/python3.10/dist-packages/flet_runtime/app.py", line 391,                                                                                         in __connect_internal_sync
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/flet/sync_websocket_connection.p                                                                                        y", line 63, in connect
    raise Exception(
Exception: Could not connected to Flet server in 30 seconds.

Hi, I changed port in  ``` flet.app(target=sign, view=WEB_BROWSER, port=44)```, everything worked with port 80

**Flet version**: 0.17.0
**Operating system**: Linux / Ubuntu Server 22.04

**Comment by Ilian445** [comment]
It fixed itself
