### ISSUE TITLE
Issue when using Filepicker in ft.UserControl

### ISSUE THREAD

**Issue by EasyDevv** [flet-dev/flet#2353]
**Description**

**Code example to reproduce the issue:**

```python
import flet as ft


class App(ft.UserControl):
    def __init__(self, page: ft.Page,):
        super().__init__(page)
        self.page = page
        self.pick_files_dialog = ft.FilePicker(on_result=self.pick_files_result)
        page.overlay.append(self.pick_files_dialog)


    def build(self):
        print(self.page.overlay)

        return ft.Row(
                [
                    ft.ElevatedButton(
                        "Test",
                        icon=ft.icons.UPLOAD_FILE,
                        on_click=lambda _: self.pick_files_dialog.pick_files(
                            allow_multiple=True
                        ),
                    ),
                ]
            )

    def pick_files_result(e: ft.FilePickerResultEvent):
        print("Checked")


async def main(page: ft.Page):    
    await page.update_async()
    app = App(page)
    await page.add_async(app)

ft.app(target=main)
```

**Describe the results you received:**

```bash
Traceback (most recent call last):
  File "c:\Projects\test_app\.venv\Lib\site-packages\flet_runtime\app.py", line 438, in on_event
    await conn.sessions[e.sessionID].on_event_async(
  File "c:\Projects\test_app\.venv\Lib\site-packages\flet_core\page.py", line 517, in on_event_async
    handler(ce)
  File "c:\Projects\test_app\tester copy.py", line 20, in <lambda>
    on_click=lambda _: self.pick_files_dialog.pick_files(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Projects\test_app\.venv\Lib\site-packages\flet_core\file_picker.py", line 168, in pick_files
    self.update()
  File "c:\Projects\test_app\.venv\Lib\site-packages\flet_core\control.py", line 271, in update
    self.__page.update(self)
  File "c:\Projects\test_app\.venv\Lib\site-packages\flet_core\page.py", line 292, in update
    r = self.__update(*controls)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Projects\test_app\.venv\Lib\site-packages\flet_core\page.py", line 419, in __update
    results = self.__conn.send_commands(self._session_id, commands).results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Projects\test_app\.venv\Lib\site-packages\flet_core\connection.py", line 27, in send_commands
    raise NotImplementedError()
NotImplementedError
```

**Describe the results you expected:**

Open the file selection window 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
0.18.0
```

**Operating system**:

Windows 11

**Additional environment details:**

**Comment by LineIndent** [comment]
Your app is async and so when you use `pick_files` it should be `pick_files_async`.

The following adjustments works. Have a go and see if it works:

```py
import flet as ft


class App(ft.UserControl):
    def __init__(
        self,
        page: ft.Page,
    ):
        super().__init__(page)
        self.page = page
        self.pick_files_dialog = ft.FilePicker(
            on_result=self.pick_files_result,
        )

        self.open_icon = ft.ElevatedButton(
            "Test",
            icon=ft.icons.UPLOAD_FILE,
            on_click=self.pick_files,
        )

    def build(self):
        return ft.Row(
            controls=[
                self.open_icon,
                self.pick_files_dialog,
            ]
        )

    async def pick_files(self, e):
        await self.pick_files_dialog.pick_files_async(allow_multiple=True)

    def pick_files_result(self, e: ft.FilePickerResultEvent):
        print("Checked")


async def main(page: ft.Page):
    await page.update_async()
    app = App(page)
    await page.add_async(app)


ft.app(target=main)



```

**Comment by EasyDevv** [comment]
> Your app is async and so when you use `pick_files` it should be `pick_files_async`.
> 
> The following adjustments works. Have a go and see if it works:
> 
> ```python
> import flet as ft
> 
> 
> class App(ft.UserControl):
>     def __init__(
>         self,
>         page: ft.Page,
>     ):
>         super().__init__(page)
>         self.page = page
>         self.pick_files_dialog = ft.FilePicker(
>             on_result=self.pick_files_result,
>         )
> 
>         self.open_icon = ft.ElevatedButton(
>             "Test",
>             icon=ft.icons.UPLOAD_FILE,
>             on_click=self.pick_files,
>         )
> 
>     def build(self):
>         return ft.Row(
>             controls=[
>                 self.open_icon,
>                 self.pick_files_dialog,
>             ]
>         )
> 
>     async def pick_files(self, e):
>         await self.pick_files_dialog.pick_files_async(allow_multiple=True)
> 
>     def pick_files_result(self, e: ft.FilePickerResultEvent):
>         print("Checked")
> 
> 
> async def main(page: ft.Page):
>     await page.update_async()
>     app = App(page)
>     await page.add_async(app)
> 
> 
> ft.app(target=main)
> ```

Thank you for your help. It works !

**Comment by EasyDevv** [comment]
Thank you for your help. It works !
