### ISSUE TITLE
macos el capitan 10.11.6 Flet wont start app or browser - error at LSOpenURLsWithRole()

### ISSUE THREAD

**Issue by rmpythoncode** [flet-dev/flet#2379]
When I try to run Flet in an old macbook pro 5.5 (mid 2009) with el capitan (10.11.6) the app wont start.

Any sugestions for a work around? Thank you very much.

(flet) rms-MacBook-Pro:test rm$ flet run testando.py 
LSOpenURLsWithRole() failed with error -10825 for the file /Users/rm/.flet/bin/flet-0.18.0/Flet.app.
Exception in thread Thread-1 (__connection_loop):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rm/venvs/flet/lib/python3.10/site-packages/flet_runtime/sync_local_socket_connection.py", line 150, in __connection_loop

**Comment by FeodorFitsner** [comment]
I'm afraid macOS 10.11 (El Capitan) is not supported.
Flutter project template is for macOS 10.14 (Mojave), by default, but Flet goes even further and requires macOS 11.0 (Big Sur).

**Comment by rmpythoncode** [comment]
I got Flet to work with dosdude1 Catalina patcher on mid 2009 MacBook pro. It works very well at least so far but only the web hotreload the Native app seens not to work.

**Comment by FeodorFitsner** [comment]
You mean upgraded your macOS to Catalina with dosdude1?

**Comment by rmpythoncode** [comment]
Yes. I did upgrade to Catalina with dosdude1 patcher and It does works very well.
MacBook Pro 5.5 mid 2009
SSD
8GB RAM
vscode 1.85
Catalina Native Python 3.8
Chrome (i use older release 95.xxx for being lightweight)
:-)
