### ISSUE TITLE
`flet build web` doesn't build or shows black screen

### ISSUE THREAD

**Issue by frowNYfaceUnknown** [flet-dev/flet#2421]
**Description**
My flet app tests as expected, using `flet run [--ios] [--android]`, on all the following platforms:

- windows,
- web,
- ios and
- andoid.

When I try to run `flet build web` it gives me the following error:
```
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...OK   
Generating splash screens...OK
Packaging Python app...OK     
Building web app...Resolving dependencies...   
  ffi 2.1.0 (2.1.2 available)
  fl_chart 0.65.0 (0.66.0 available)
  flutter_lints 2.0.3 (3.0.1 available)        
  flutter_native_splash 2.3.7 (2.3.9 available)
  js 0.6.7 (0.7.0 available)
  lints 2.1.1 (3.0.0 available)
  matcher 0.12.16 (0.12.16+1 available)        
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.10.0 (1.11.0 available)
  package_info_plus 4.2.0 (5.0.1 available)
  path 1.8.3 (1.9.0 available)
  petitparser 5.4.0 (6.0.2 available)
  test_api 0.6.1 (0.7.0 available)
  toml 0.14.0 (0.15.0 available)
  web 0.3.0 (0.4.2 available)
  web_socket_channel 2.4.0 (2.4.3 available)
  webview_flutter_wkwebview 3.10.2 (3.10.3 available)
  xml 6.3.0 (6.5.0 available)
Got dependencies!
18 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

Compiling lib\main.dart for the Web...
Error detected in pubspec.yaml:
Compiling lib\main.dart for the Web...                             71.2s

No file or variants found for asset: app/app.zip.hash.

Target web_release_bundle failed: Exception: Failed to bundle asset files.
#0      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:63:5)
<asynchronous suspension>
#1      WebReleaseBundle.build (package:flutter_tools/src/build_system/targets/web.dart:401:29)
<asynchronous suspension>
#2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#4      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#5      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#6      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:89:34)
<asynchronous suspension>
#7      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:199:5)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Exception: Failed to compile application for the Web.

Error building Flet app - see the log of failed command above.
```

To get rid of this error, if I remove `app/app.zip.hash`, which by the way _does not_ exist in the temp directory, from the `pubspec.yaml` the build is successful, but when I run it, it only shows a black screen after the flet logo popup.

Output for `python -m http.server --directory build/web` after successful build:
```
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::ffff:127.0.0.1 - - [18/Jan/2024 15:49:01] "GET / HTTP/1.1" 304 -
::ffff:127.0.0.1 - - [18/Jan/2024 15:49:03] "GET /flutter_service_worker.js?v=2306065268 HTTP/1.1" 304 -
```

**Comment by FeodorFitsner** [comment]
Could you please provide a full build log please and some screenshots? I'm asking because building with `flet build` shouldn't display a round loading circle.

**Comment by frowNYfaceUnknown** [comment]
Sure! I built the application again and this time I didn't get a loading circle.

Here's the output for `flet build web -v` (`-vv` was too long, can upload if necessary):

```
Flutter bootstrap directory: C:\Users\aarya\AppData\Local\Temp\flet_flutter_build_GXMeWnIXKc
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...OK
Generating splash screens...OK
Packaging Python app...OK
Building web app...['D:\\flutter\\flutter\\bin\\flutter.BAT', 'build', 'web']
OK
Copying build to build\web directory...OK
Deleting Flutter bootstrap directory C:\Users\aarya\AppData\Local\Temp\flet_flutter_build_GXMeWnIXKc
Success!
```

And here's the output for `python -m http.server --directory build/web`:

```
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::ffff:127.0.0.1 - - [19/Jan/2024 00:35:20] "GET / HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:35:20] "GET /flutter_service_worker.js?v=2963444582 HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:35:21] "GET /index.html HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:35:21] "GET /assets/AssetManifest.json HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:35:21] "GET /assets/FontManifest.json HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:35:27] "GET /main.dart.js HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:35:29] "GET /flutter_service_worker.js?v=2963444582 HTTP/1.1" 304 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:38:19] "GET /assets/app/app.zip HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:38:19] "GET /flutter_service_worker.js?v=2963444582 HTTP/1.1" 304 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:38:28] "GET /flutter_service_worker.js?v=2963444582 HTTP/1.1" 304 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:38:36] "GET /flutter_service_worker.js?v=2963444582 HTTP/1.1" 304 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:38:40] "GET / HTTP/1.1" 304 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:38:40] "GET /favicon.png HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:38:42] "GET /flutter_service_worker.js?v=2963444582 HTTP/1.1" 304 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:38:47] "GET / HTTP/1.1" 304 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:38:49] "GET /flutter_service_worker.js?v=2963444582 HTTP/1.1" 304 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:39:59] "GET / HTTP/1.1" 304 -
::ffff:127.0.0.1 - - [19/Jan/2024 00:40:01] "GET /flutter_service_worker.js?v=2963444582 HTTP/1.1" 304 -
```

A few screenshots:
![image](https://github.com/flet-dev/flet/assets/92662416/d86bb030-2ecc-4ef8-a7df-278a71d313af)
![image](https://github.com/flet-dev/flet/assets/92662416/a5caf1df-faeb-4588-b778-c540e9ba76c7)

**Comment by FeodorFitsner** [comment]
What errors do you have on `Console` tab of your browser's developer tools?

**Comment by frowNYfaceUnknown** [comment]
![image](https://github.com/flet-dev/flet/assets/92662416/fabad60d-2379-45b4-9b71-8045cbaf131c)

Should I add ssl in requirements.txt or through micropip?

**Comment by FeodorFitsner** [comment]
See this issue: https://github.com/pyodide/pyodide/issues/529#issuecomment-542340441
In short, `pymongo` won't work in the browser.

See [this comment](https://github.com/pyodide/pyodide/pull/4044#issuecomment-1667868452) in [that Pyodide PR](https://github.com/pyodide/pyodide/pull/4044):

> Pyodide does not support sockets because of browser limitations, so I'm pessimistic that pymongo and other DB client packages will work.

You should make you app as server-side: https://flet.dev/docs/guides/python/deploying-web-app/running-flet-with-fastapi

**Comment by frowNYfaceUnknown** [comment]
Thank you so much! It worked out by building it as a server-side app.

**Comment by psksvp** [comment]
Hi 

I'm having the same problem here. So there is no way to run as static web?

**Comment by psksvp** [comment]
Hi 

Please ignore my comment. The problem isn't related. Sorry for not looking at my error carefully before posting.
