### ISSUE TITLE
Trello clone example

### ISSUE THREAD

**Issue by ronnydemeyerAM** [flet-dev/flet#2486]
**Trello clone example not working**

I'm learning python in evening school and i wanted to follow your Trello clone example
I copied the codes for the first 4 files and already have trouble.

**In main.py "TrelloApp" is unknown, i added:**

```python
from app_bar import TrelloApp
```

**Running this already gives an error:**

"""
C:\Users\SIDDMRO\.conda\envs\am2311_serverx\python.exe \\ampythonbelgium\Jobs\COO\apps\trello_clone\src\main.py 
Unhandled error processing page session e5c7dd52-f539-49c5-9706-215777c8e5f0: Traceback (most recent call last):
  File "C:\Users\SIDDMRO\.conda\envs\am2311_serverx\Lib\site-packages\flet_runtime\app.py", line 359, in on_session_created
    session_handler(page)
  File "\\ampythonbelgium\Jobs\COO\apps\trello_clone\src\main.py", line 15, in main
    page.add(app)
  File "C:\Users\SIDDMRO\.conda\envs\am2311_serverx\Lib\site-packages\flet_core\page.py", line 300, in add
    r = self.__update(self)
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SIDDMRO\.conda\envs\am2311_serverx\Lib\site-packages\flet_core\page.py", line 411, in __update
    commands, added_controls, removed_controls = self.__prepare_update(*controls)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SIDDMRO\.conda\envs\am2311_serverx\Lib\site-packages\flet_core\page.py", line 433, in __prepare_update
    control.build_update_commands(
  File "C:\Users\SIDDMRO\.conda\envs\am2311_serverx\Lib\site-packages\flet_core\control.py", line 374, in build_update_commands
    ctrl.build_update_commands(
  File "C:\Users\SIDDMRO\.conda\envs\am2311_serverx\Lib\site-packages\flet_core\control.py", line 386, in build_update_commands
    innerCmds = ctrl._build_add_commands(
                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrelloApp' object has no attribute '_build_add_commands'
"""

**Operating system = Windows 11**

**Comment by Joerki** [comment]
Hi @RonnyDeMeyer,

I also looked for that and found the example here:

https://github.com/flet-dev/examples

But also that code is deprecated. Let's hope that the example gets a fix for stable release 1.0: 

https://github.com/flet-dev/examples/issues/115

**Comment by abdulkuddusa4** [comment]
when will 1.0 release

**Comment by ndonkoHenri** [comment]
Can you please give the code another try? It has been updated.
