### ISSUE TITLE
Error when changing controls order

### ISSUE THREAD

**Issue by roto5296** [flet-dev/flet#2528]
**Description**

**Code example to reproduce the issue:**

```python
import flet as ft

def main(page: ft.Page):
    def on_click1(e_):
        print([isinstance(c.page, ft.Page) for c in row.controls])
        row.controls = [button1, button2, a, h, b, c, d, e, f, g]
        row.update()
        h.name = ft.icons.FAVORITE
        h.update()

    def on_click2(e_):
        print([isinstance(c.page, ft.Page) for c in row.controls])
        row.controls = [button1, button2, a, b, d, e, f, g, h, c]
        row.update()
        c.name = ft.icons.FAVORITE
        c.update()

    a = ft.Icon(name=ft.icons.FAVORITE, color=ft.colors.PINK)
    b = ft.Icon(name=ft.icons.AUDIOTRACK, color=ft.colors.GREEN_400, size=30)
    c = ft.Icon(name=ft.icons.BEACH_ACCESS, color=ft.colors.BLUE, size=50)
    d = ft.Icon(name="settings", color="#c1c1c1")
    e = ft.Icon(name=ft.icons.FAVORITE, color=ft.colors.PINK)
    f = ft.Icon(name=ft.icons.AUDIOTRACK, color=ft.colors.GREEN_400, size=30)
    g = ft.Icon(name=ft.icons.BEACH_ACCESS, color=ft.colors.BLUE, size=50)
    h = ft.Icon(name="settings", color="#c1c1c1")
    button1 = ft.ElevatedButton(on_click=on_click1)
    button2 = ft.ElevatedButton(on_click=on_click2)
    row = ft.Row([button1, button2, a, b, c, d, e, f, g, h])
    page.add(row)

ft.app(target=main)

```

**Describe the results you received:**
When I clicked button1, this program run correctly.
But, when I clicked button2, the following error was displayed.
```
Exception in thread Thread-66 (on_click2):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hikun5296/test.py", line 17, in on_click2
    c.update()
  File "/home/hikun5296/.venv/lib/python3.10/site-packages/flet_core/control.py", line 270, in update
    assert self.__page, "Control must be added to the page first."
AssertionError: Control must be added to the page first.
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.19.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /home/hikun5296/.venv/lib/python3.10/site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by: 
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages): **

```
(The requirements)
```

**Operating system**:
ubuntu 22.04 on wsl2

**Additional environment details:**

**Comment by lekshmanmj** [comment]
def on_click2(e_):
        c.name = ft.icons.FAVORITE
        c.update()
        row.controls = [button1, button2, a, b, d, e, f, g, h, c]
        row.update()

**Comment by taaaf11** [comment]
@roto5296 it works with this code:
```python
def on_click2(e_):
        c.name = ft.icons.FAVORITE
        row.controls = [button1, button2, a, b, d, e, f, g, h, c]
        # c.update()
        row.update()
```
