### ISSUE TITLE
flet app packaged as MacOS App startup issue

### ISSUE THREAD

**Issue by kspviswa** [flet-dev/flet#2593]
**Description**

I'm seeing issue when flet app packaged as MacOS app starts. It works fine within a `.venv` and while running `flet run main.py`. Only the packaged macOS app doesn't work / start

App : https://github.com/kspviswa/pyOllaMx

**Code example to reproduce the issue:**

not applicable 

**Describe the results you received:**

Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/main.py", line 3, in <module>
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/prompt.py", line 3, in <module>
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/search.py", line 5, in <module>
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/pydantic/v1/main.py", line 339, in __init__
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/pydantic/v1/main.py", line 1100, in validate_model
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/langchain_community/utilities/duckduckgo_search.py", line 33, in validate_environment
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/duckduckgo_search/__init__.py", line 10, in <module>
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/duckduckgo_search/duckduckgo_search.py", line 14, in <module>
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/docstring_inheritance/__init__.py", line 89, in __init__
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/docstring_inheritance/__init__.py", line 75, in __init__
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/docstring_inheritance/class_docstrings_inheritor.py", line 88, in inherit_docstrings
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/docstring_inheritance/class_docstrings_inheritor.py", line 136, in _inherit_attrs_docstrings
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/docstring_inheritance/docstring_inheritors/bases/inheritor.py", line 115, in inherit
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/docstring_inheritance/docstring_inheritors/bases/inheritor.py", line 127, in _inherit
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/docstring_inheritance/docstring_inheritors/bases/inheritor.py", line 268, in _inherit_sections
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/docstring_inheritance/docstring_inheritors/bases/inheritor.py", line 334, in _filter_args_section
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempH56BGa/__pypackages__/docstring_inheritance/docstring_inheritors/bases/inheritor.py", line 209, in _warn
  File "./inspect.py", line 1244, in getsourcelines
  File "./inspect.py", line 1081, in findsource
OSError: could not get source code

**Describe the results you expected:**

macOS app to start and function

**Additional information you deem important (e.g. issue happens only occasionally):**

It happens only in my recent version of app. Only thing I added was more logic that includes some duckduck-go search api usage

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.19.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: <path/to>.venv/lib/python3.12/site-packages
Requires: cookiecutter, flet-runtime, packaging, qrcode, watchdog, websocket-client, websockets
Required-by:
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
duckduckgo_search==4.4
```

**Operating system**:

MacOS 14.3

**Additional environment details:**

Flet pack command used : 
`flet build macos --build-version '0.0.2' --copyright 'Viswa Kumar 2024 ©' --project 'PyOllaMx' --company 'PyOllaMx'`

**Comment by FeodorFitsner** [comment]
This looks suspicious:

```
...
File "./inspect.py", line 1081, in findsource
OSError: could not get source code
```

Not sure what sources it's trying to load, but be aware that during the packaging all `.py` files are compiled to `.pyc`.

**Comment by kspviswa** [comment]
I tried renamed other unreferenced / used `.py` files to `.py1` and kept just the actual files. But still no luck

```
Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/main.py", line 3, in <module>
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/prompt.py", line 3, in <module>
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/search.py", line 5, in <module>
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/pydantic/v1/main.py", line 339, in __init__
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/pydantic/v1/main.py", line 1100, in validate_model
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/langchain_community/utilities/duckduckgo_search.py", line 33, in validate_environment
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/duckduckgo_search/__init__.py", line 10, in <module>
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/duckduckgo_search/duckduckgo_search.py", line 14, in <module>
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/docstring_inheritance/__init__.py", line 89, in __init__
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/docstring_inheritance/__init__.py", line 75, in __init__
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/docstring_inheritance/class_docstrings_inheritor.py", line 88, in inherit_docstrings
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/docstring_inheritance/class_docstrings_inheritor.py", line 136, in _inherit_attrs_docstrings
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/docstring_inheritance/docstring_inheritors/bases/inheritor.py", line 115, in inherit
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/docstring_inheritance/docstring_inheritors/bases/inheritor.py", line 127, in _inherit
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/docstring_inheritance/docstring_inheritors/bases/inheritor.py", line 268, in _inherit_sections
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/docstring_inheritance/docstring_inheritors/bases/inheritor.py", line 334, in _filter_args_section
  File "/var/folders/rd/nsmb4_7n0lx599jrv5sl21400000gn/T/serious_python_tempzWHgaN/__pypackages__/docstring_inheritance/docstring_inheritors/bases/inheritor.py", line 209, in _warn
  File "./inspect.py", line 1244, in getsourcelines
  File "./inspect.py", line 1081, in findsource
OSError: could not get source code

```

**Comment by FeodorFitsner** [comment]
I'm going to add https://github.com/flet-dev/serious-python/issues/71 and we'll see if that fixes that lib.

**Comment by kspviswa** [comment]
@FeodorFitsner - I did a little check . I commented out the code that explicitly uses the duckduckgo search api, but kept the rest of the stuff. The packaged app worked. Next I included the `search.py` but just didn't use it in my `main.py`. Result was still positive. Only when I call a func in `search.py` that uses DDGS, I'm seeing this error. 

One more point to note is that, even though my code is not async, the ddgs library apparently inherits sync version from async version. While running my app in local mode, I saw few warnings, but the app was still functional. However when I pack that into MacOS app, that's where I'm facing this current issue.

Just my 2 cents for you, if it helps in understanding the issue.

PS: I have also opened an issue with ddgs library as well https://github.com/deedy5/duckduckgo_search/issues/183

**Comment by kspviswa** [comment]
@FeodorFitsner - My issue got fixed . Thanks to https://github.com/deedy5/duckduckgo_search/issues/185 . Feel free to close this issue . My app is now packed and released here : https://github.com/kspviswa/pyOllaMx/releases

**Comment by FeodorFitsner** [comment]
Thanks for letting know!
