### ISSUE TITLE
iOS ipa not building

### ISSUE THREAD

**Issue by justinkumpe** [flet-dev/flet#2658]
**Description**

I am trying to build ipa file. I run flet build ipa --project "kumpe3dkiosk" --product "Kumpe3D Kiosk" --company "KumpeApps LLC" --org "com.kumpeapps.ios" --no-ios-splash --team 2T42Z3DM34 -o /Users/justinkumpe/Downloads/K3D --build-version 0.0.1 --build-number 1 -vvc and it says successful but I just get a build folder with Runner.xcarchive. I do not get the ipa file.

**Flet version (`pip show flet`)**:

```
0.20.0
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet==0.20.0
libgravatar==1.0.4
pyhtml2pdf==0.0.7
PyMySQL==1.1.0
python-dotenv==1.0.1
selenium==4.17.2
infisical_api==1.0.0
```

**Operating system**:

macOS 14.3.1

**Additional environment details:**

**Comment by justinkumpe** [comment]
Build command output is too large for comment but here is a text file link [https://raw.githubusercontent.com/kumpeapps/Kumpe3D_Kiosk/PreProd/build_log.txt](https://raw.githubusercontent.com/kumpeapps/Kumpe3D_Kiosk/PreProd/build_log.txt)

**Comment by FeodorFitsner** [comment]
Looks like a bug. Working on a fix. Thanks for the detailed log - that helped!

**Comment by FeodorFitsner** [comment]
Flet 0.20.1 has been just released which now copies build output from both `build/ios/archive` and `build/ios/ipa` folder.
Update to 0.20.1 (`pip install flet --upgrade`) and give build command another try.

**Comment by justinkumpe** [comment]
Now it is hanging at Failed to build iOS app.  I updated my log file at [https://raw.githubusercontent.com/kumpeapps/Kumpe3D_Kiosk/PreProd/build_log.txt](https://raw.githubusercontent.com/kumpeapps/Kumpe3D_Kiosk/PreProd/build_log.txt)

I thought maybe it could be something in my code so I build a simple hello world with no additional python modules and got the same error when building ios.

**Comment by FeodorFitsner** [comment]
Could you build with less detailed log please (`-v`)?

**Comment by justinkumpe** [comment]
I updated the log file at https://raw.githubusercontent.com/kumpeapps/Kumpe3D_Kiosk/PreProd/build_log.txt

But I assume this is the piece you need.
'''
Failed to build iOS app
Error (Xcode): /Users/justinkumpe/.pub-cache/hosted/pub.dev/flet-0.20.1/lib/src/utils/text.dart:156:8: Error: 'FontVariation' isn't a type.


Encountered error while archiving for device.
Deleting Flutter bootstrap directory /var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/flet_flutter_build_JgLgHZdTht
Error building Flet app - see the log of failed command above.

'''

**Comment by FeodorFitsner** [comment]
Alright, I see where the error is coming from.

Flet 0.20.1 requires Flutter 3.19.0 which just came yesterday. Upgrade your Flutter installation to the latest version (`flutter upgrade --force`) and it will do the trick.

**Comment by justinkumpe** [comment]
That worked, it now builds. But I am getting this error when launching the app on iOS.

```
Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/main.py", line 3, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/flet/__init__.py", line 1, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/flet_runtime/__init__.py", line 1, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/flet_core/__init__.py", line 158, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/flet_core/page.py", line 58, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/flet_runtime/auth/__init__.py", line 1, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/flet_runtime/auth/authorization.py", line 8, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpx/__init__.py", line 2, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpx/_api.py", line 4, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpx/_client.py", line 30, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpx/_transports/default.py", line 30, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpcore/__init__.py", line 1, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpcore/_api.py", line 5, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpcore/_sync/__init__.py", line 1, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpcore/_sync/connection.py", line 12, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpcore/_synchronization.py", line 13, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/trio/__init__.py", line 22, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/trio/_core/__init__.py", line 21, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/trio/_core/_local.py", line 9, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/trio/_core/_run.py", line 43, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/trio/_core/_thread_cache.py", line 79, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/trio/_core/_thread_cache.py", line 45, in get_os_thread_name_func
  File "./ctypes/util.py", line 329, in find_library
  File "./ctypes/util.py", line 289, in _findSoname_ldconfig
  File "/Users/appveyor/projects/serious-python/dist/root/python3/lib/python3.11/subprocess.py", line 1026, in __init__
  File "/Users/appveyor/projects/serious-python/dist/root/python3/lib/python3.11/subprocess.py", line 1883, in _execute_child
TypeError: fork_exec() takes 0 positional arguments but 23 were given
```
