### ISSUE TITLE
flet build apk -- verbose error v0.20.0

### ISSUE THREAD

**Issue by noe1995** [flet-dev/flet#2683]
Hello everyone.

I have tried to run the following command

flet build apk --verbose

but i have a error:

Flutter bootstrap directory: C:\xxx\DESARR~1\AppData\Local\Temp\flet_flutter_build_iJocUHqJab
Additional Flutter dependencies:
{}
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...
Run subprocess: ['C:\\flutter\\bin\\dart', 'run', 'flutter_launcher_icons']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\xxx\DESARROLLO\AppData\Local\Programs\Python\Python312\Scripts\flet.exe\__main__.py", line 7, in <module>
  File "C:\xxx\DESARROLLO\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\cli.py", line 83, in main
    args.handler(args)
  File "C:\xxx\DESARROLLO\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\commands\build.py", line 585, in handle
    icons_result = self.run(
                   ^^^^^^^^^
  File "C:\xxx\DESARROLLO\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\commands\build.py", line 814, in run
    r = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "C:\xxx\DESARROLLO\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xxx\DESARROLLO\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\xxx\DESARROLLO\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

any suggestions? thanks.

**Comment by FeodorFitsner** [comment]
It's Python 3.12.0 specific issue. Upgrade your Python installation to 3.12.2.

**Comment by MostafaKK00** [comment]
I have a problem and it stops converting the application to apk 
PS C:\Users\ninja\Desktop\PythonFile\f\myapp> flet build apk --verbose
Flutter bootstrap directory: C:\Users\ninja\AppData\Local\Temp\flet_flutter_build_QDuuckPBts
Additional Flutter dependencies:     
{}
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...Copying C:\Users\ninja\Desktop\PythonFile\f\myapp\assets\icon.png to 
C:\Users\ninja\AppData\Local\Temp\flet_flutter_build_QDuuckPBts\images
OK
Generating app icons...
Run subprocess: ['C:\\Program Files\\flutter\\bin\\dart.BAT', 'run', 'flutter_launcher_icons']

and he stop here
