### ISSUE TITLE
iOS fork_exec() TypeError

### ISSUE THREAD

**Issue by justinkumpe** [flet-dev/flet#2702]
**Description**

Buld app using flet build ios command. When I launch the app I get the below error.
```python
Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/main.py", line 3, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/flet/__init__.py", line 1, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/flet_runtime/__init__.py", line 1, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/flet_core/__init__.py", line 158, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/flet_core/page.py", line 58, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/flet_runtime/auth/__init__.py", line 1, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/flet_runtime/auth/authorization.py", line 8, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpx/__init__.py", line 2, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpx/_api.py", line 4, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpx/_client.py", line 30, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpx/_transports/default.py", line 30, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpcore/__init__.py", line 1, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpcore/_api.py", line 5, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpcore/_sync/__init__.py", line 1, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpcore/_sync/connection.py", line 12, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/httpcore/_synchronization.py", line 13, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/trio/__init__.py", line 22, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/trio/_core/__init__.py", line 21, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/trio/_core/_local.py", line 9, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/trio/_core/_run.py", line 43, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/trio/_core/_thread_cache.py", line 79, in <module>
  File "/var/folders/jd/2x7b0kxd2wdfq3925702b1c00000gn/T/serious_python_temp1UCSyq/__pypackages__/trio/_core/_thread_cache.py", line 45, in get_os_thread_name_func
  File "./ctypes/util.py", line 329, in find_library
  File "./ctypes/util.py", line 289, in _findSoname_ldconfig
  File "/Users/appveyor/projects/serious-python/dist/root/python3/lib/python3.11/subprocess.py", line 1026, in __init__
  File "/Users/appveyor/projects/serious-python/dist/root/python3/lib/python3.11/subprocess.py", line 1883, in _execute_child
TypeError: fork_exec() takes 0 positional arguments but 23 were given
```

**Flet version (`pip show flet`)**:

```
Version: 0.20.2
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet>=0.20.2
libgravatar==1.0.4
pyhtml2pdf==0.0.7
PyMySQL==1.1.0
python-dotenv==1.0.1
selenium==4.17.2
infisical_api==1.0.0
```

**Operating system**:

macOS 14.3.1

**Comment by FeodorFitsner** [comment]
The place in `trio` library where it happens: https://github.com/python-trio/trio/blob/4b6b49707a1afad6af1413d01abf66031534e0bd/src/trio/_core/_thread_cache.py#L45

Need investigate.

It might be possible to fix with monkey patching. And we'd need to provide a proper stub for `fork_exec` function.
