### ISSUE TITLE
Flet with FastAPI (examples) not working -> 500 Internal Server Error

### ISSUE THREAD

**Issue by thinkORo** [flet-dev/flet#2739]
I have tried to follow the examples for Flet and FastAPI (e.g. here (https://flet.dev/blog/flet-for-fastapi/) or here (https://pypi.org/project/flet-fastapi/) or here (https://flet.dev/docs/guides/python/deploying-web-app/running-flet-with-fastapi/)).

None of the examples work. After calling uvicorn I get an URL. But after calling up the website, the error "500 Internal Server Error" appears immediately.

I'm running the latest version of Flet and Flet-FastAPI in a new VENV on Arch linux.

Here is the most minimal example I have tried (from the first link).

Code for hello.py:
```python
import flet as ft
import flet_fastapi

async def main(page: ft.Page):
    await page.add_async(
        ft.Text("Hello, Flet!")
    )

app = flet_fastapi.app(main)
```

```bash
uvicorn hello:app
```

The error is:
```
 $ uvicorn hello:app
INFO:     Started server process [294077]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/oro/Program/miniforge3/envs/flet/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oro/Program/miniforge3/envs/flet/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oro/Program/miniforge3/envs/flet/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/oro/Program/miniforge3/envs/flet/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    self.middleware_stack = self.build_middleware_stack()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oro/Program/miniforge3/envs/flet/lib/python3.11/site-packages/fastapi/applications.py", line 211, in build_middleware_stack
    for cls, options in reversed(middleware):
        ^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
INFO:     127.0.0.1:52312 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/oro/Program/miniforge3/envs/flet/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oro/Program/miniforge3/envs/flet/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oro/Program/miniforge3/envs/flet/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/oro/Program/miniforge3/envs/flet/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    self.middleware_stack = self.build_middleware_stack()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oro/Program/miniforge3/envs/flet/lib/python3.11/site-packages/fastapi/applications.py", line 211, in build_middleware_stack
    for cls, options in reversed(middleware):
        ^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
INFO:     127.0.0.1:52322 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
```

**Comment by ndonkoHenri** [comment]
Read [this](https://flet.dev/blog/flet-fastapi-and-async-api-improvements#fastapi-with-uvicorn-replaces-built-in-web-server) concerning `flet_fastapi`.

The below should work normally:
```py
import flet as ft
import flet.fastapi as flet_fastapi

async def main(page: ft.Page):
    await page.add_async(
        ft.Text("Hello, Flet!")
    )

app = flet_fastapi.app(main)
```
