### ISSUE TITLE
Bug in 0.21.0 with on_route_change

### ISSUE THREAD

**Issue by Ambassador-of-programming** [flet-dev/flet#2820]
In the new version, an error occurs during routing. Everything worked fine in previous versions.

The error goes out: 
```
Task exception was never retrieved
future: <Task finished name='Task-25' coro=<__run_socket_server.<locals>.on_event() done, defined at C:\Users\pro\.virtualenvs\MyPasswords-cDgjCAtp\Lib\site-packages\flet_runtime\app.py:215> exception=AttributeError("'NoneType' object has no attribute 'route'")>
Traceback (most recent call last):
  File "C:\Users\pro\.virtualenvs\MyPasswords-cDgjCAtp\Lib\site-packages\flet_runtime\app.py", line 217, in on_event
    await conn.sessions[e.sessionID].on_event_async(
  File "C:\Users\pro\.virtualenvs\MyPasswords-cDgjCAtp\Lib\site-packages\flet_core\page.py", line 472, in on_event_async
    await handler(ce)
  File "C:\Users\pro\.virtualenvs\MyPasswords-cDgjCAtp\Lib\site-packages\flet_core\event_handler.py", line 25, in fn
    await handler(ce)
  File "c:\Users\pro\Documents\project\MyPasswords\system\ru\navigation\FletRouter.py", line 20, in route_change
    print(route.route)
          ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'route'
```

Routing Code: 
```
class Router:
    async def init(self, page: ft.Page):
        self.routes = {
            '/': await index(page),
            '/1': await 1(page),
            '/2': await 2(page),
            '/3': await 3(page),
            '/4': await 4(page),
        }
        self.body = ft.Container()

    async def route_change(self, route):
        print(route.route)
        self.body.content = self.routes[route.route]
        self.body.update()
```

And the code for the main menu: 
```
async def main(page: ft.Page):
    from FletRouter import Router
    myRouter = Router()
    await myRouter.init(page)
    page.on_route_change = myRouter.route_change
    page.add(
        myRouter.body
    )
    page.go('/')
        
ft.app(
    target=main, 
    assets_dir="assets", 
)
```

I've seen that `print(route.route)` passes the correct route position. And in older versions everything works successfully, but after the upgrade everything breaks. But routing continues to work, but in the console I get an error

**Comment by FeodorFitsner** [comment]
I'm testing with the following example on Flet 0.21.0 and not getting an error:

```python
import flet as ft


class Router:
    async def init(self, page: ft.Page):
        self.routes = {}
        self.body = ft.Container()

    async def route_change(self, route):
        print("ROUTER:", route.route)
        # self.body.content = self.routes[route.route]
        self.body.update()


async def main(page: ft.Page):
    myRouter = Router()
    await myRouter.init(page)
    page.on_route_change = myRouter.route_change
    page.add(myRouter.body)
    page.go("/")


ft.app(
    target=main,
    assets_dir="assets",
)

```

**Comment by Ambassador-of-programming** [comment]
The error occurs when trying to go to another page

**Comment by FeodorFitsner** [comment]
Could you please provide more complete example that reproduces the issue?

**Comment by Ambassador-of-programming** [comment]
This is the code that reproduces the error: 
```
import flet as ft

async def index(page: ft.Page):

    content = ft.Column(controls=[
        ft.ResponsiveRow(controls=[
            ft.Text(value="payment_data", size=30, text_align=ft.TextAlign.CENTER),
        ]),
        ft.Row(height=20),
        
        ft.ResponsiveRow(controls=[
            ft.Text(value="Payment Date", size=30, text_align=ft.TextAlign.CENTER),
        ]),
    ])
    return content

async def payment(page: ft.Page):

    content = ft.Column(controls=[
        ft.ResponsiveRow(controls=[
            ft.Text(value="payment_data", size=30, text_align=ft.TextAlign.CENTER),
        ]),
        ft.Row(height=20),
        
        ft.ResponsiveRow(controls=[
            ft.Text(value="payment_data", size=30, text_align=ft.TextAlign.CENTER),
        ]),
    ])
    return content

class Router:
    async def init(self, page: ft.Page):
        self.routes = {
            '/': await index(page),
            '/payment_data': await payment(page),
        }
        self.body = ft.Container()

    async def route_change(self, route):
        print(route)
        self.body.content = self.routes[route.route]
        self.body.update()

async def bottomappbar(page: ft.Page) -> ft.AppBar:
    async def go_home(event):
        return page.go('/')
    async def go_settings(event):
        return page.go('/payment_data')

    bottomappbar = ft.BottomAppBar(
        bgcolor=ft.colors.TERTIARY_CONTAINER,
        content=ft.Row(
            controls=[
                ft.Container(expand=True),
                ft.IconButton(icon=ft.icons.HOME, icon_color=ft.colors.BLUE_200, on_click=go_home),
                ft.Container(expand=True),
                ft.IconButton(icon=ft.icons.SETTINGS, icon_color=ft.colors.BLUE_200, on_click=go_settings),
                ft.Container(expand=True),
            ]
        ),
        height=65,)
    return bottomappbar

async def main(page: ft.Page):
    page.bottom_appbar = await bottomappbar(page)
    myRouter = Router()
    await myRouter.init(page)
    page.on_route_change = myRouter.route_change
    page.add(
        myRouter.body
    )
    page.go('/')
        
ft.app(
    target=main, 
    assets_dir="assets", 
)
```

**Comment by Ambassador-of-programming** [comment]
This is the code that reproduces the error: 
```
import flet as ft

async def index(page: ft.Page):

    content = ft.Column(controls=[
        ft.ResponsiveRow(controls=[
            ft.Text(value="Page index", size=30, text_align=ft.TextAlign.CENTER),
        ]),
        ft.Row(height=20),

    ])
    return content

async def payment(page: ft.Page):

    content = ft.Column(controls=[
        ft.ResponsiveRow(controls=[
            ft.Text(value="Page payment", size=30, text_align=ft.TextAlign.CENTER),
        ]),
        ft.Row(height=20),

    ])
    return content

class Router:
    async def init(self, page: ft.Page):
        self.routes = {
            '/': await index(page),
            '/payment_data': await payment(page),
        }
        self.body = ft.Container()

    async def route_change(self, route):
        print(route)
        self.body.content = self.routes[route.route]
        self.body.update()

async def bottomappbar(page: ft.Page) -> ft.AppBar:
    async def go_home(event):
        return page.go('/')
    async def go_settings(event):
        return page.go('/payment_data')

    bottomappbar = ft.BottomAppBar(
        bgcolor=ft.colors.TERTIARY_CONTAINER,
        content=ft.Row(
            controls=[
                ft.Container(expand=True),
                ft.IconButton(icon=ft.icons.HOME, icon_color=ft.colors.BLUE_200, on_click=go_home),
                ft.Container(expand=True),
                ft.IconButton(icon=ft.icons.SETTINGS, icon_color=ft.colors.BLUE_200, on_click=go_settings),
                ft.Container(expand=True),
            ]
        ),
        height=65,)
    return bottomappbar

async def main(page: ft.Page):
    page.bottom_appbar = await bottomappbar(page)
    myRouter = Router()
    await myRouter.init(page)
    page.on_route_change = myRouter.route_change
    page.add(
        myRouter.body
    )
    page.go('/')
        
ft.app(
    target=main, 
    assets_dir="assets", 
)
```

**Comment by FeodorFitsner** [comment]
Can reproduce, thank you! Working on the fix.

**Comment by FeodorFitsner** [comment]
Release Flet 0.21.1 with the fix.
