### ISSUE TITLE
libmpv.so.1 not found (when libmpv is already installed) - fixable but hacky

### ISSUE THREAD

**Issue by yashasolutions** [flet-dev/flet#2823]
# The problem 

*error while loading shared libraries: libmpv.so.1*

```
$ python counter.py
/home/user/.flet/bin/flet-0.21.1/flet/flet: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/user/code/flet/counter.py", line 29, in <module>
    flet.app(target=main)
  File "/home/user/code/flet/.venv/lib/python3.11/site-packages/flet_runtime/app.py", line 70, in app
    return asyncio.run(
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/code/flet/.venv/lib/python3.11/site-packages/flet_runtime/app.py", line 207, in app_async
    await conn.close()
  File "/home/user/code/flet/.venv/lib/python3.11/site-packages/flet_runtime/flet_socket_server.py", line 191, in close
    if self.__receive_loop_task:
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FletSocketServer' object has no attribute '_FletSocketServer__receive_loop_task'. Did you mean: '_FletSocketServer__receive_loop'?
```

However, mpv is installed on the system (linux Arch):

```sh
$ ls -l /usr/lib/libmpv.so*
libmpv.so        libmpv.so.2      libmpv.so.2.2.0
```

## The hacky fix
so a quick symlink can fix the problem:

```
 sudo ln -s /usr/lib/libmpv.so /usr/lib/libmpv.so.1
```

and then it works but I am sure the dependency resolution could figure this out on its own without this kind solution.

(side note: just found about Flet today, it looks amazing, can't wait to give a go with a real project)

**Comment by Lucifer516-hp** [comment]
well, for me I had to link the libraries again and again and still no improved, had to link libmpv, libmujs, lua5.2 and then jepg turbo still no improvement

**Comment by syleishere** [comment]
apt install libmpv1
this works for me at least under ubuntu 22.04

I do however get following:
** (flet:29655): CRITICAL **: 03:35:11.411: void update_pressing_state(FlKeyEmbedderResponder *, uint64_t, uint64_t): assertion 'lookup_hash_table(self->pressing_records, physical_key) != 0' failed
/usr/local/lib/python3.12/dist-packages/flet_core/page.py:292: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.__expires_at = datetime.utcnow() + timedelta(


The counter app however does work as intended

**Comment by syleishere** [comment]
Hmm this only happening with WSL Ubuntu-22.04, I don't see it happening as normal VM Ubuntu-22.04.

**Comment by syleishere** [comment]
I don't think I can, I run all my real VM's under BHYVE virtualization in FreeBSD with vm-bhyve, not sure if arch architecture supported.

**Comment by lokcito** [comment]
In Debian 12 - Debian GNU/Linux 12 (bookworm) 
Being root: 
`apt install libmpv-dev mpv
`
`dpkg -L libmpv-dev`
the output is: 
> 
> /usr
> /usr/include
> /usr/include/mpv
> /usr/include/mpv/client.h
> /usr/include/mpv/render.h
> /usr/include/mpv/render_gl.h
> /usr/include/mpv/stream_cb.h
> /usr/lib
> /usr/lib/x86_64-linux-gnu
> /usr/lib/x86_64-linux-gnu/pkgconfig
> /usr/lib/x86_64-linux-gnu/pkgconfig/mpv.pc
> /usr/share
> /usr/share/doc
> /usr/share/doc/libmpv-dev
> /usr/share/doc/libmpv-dev/changelog.Debian.gz
> /usr/share/doc/libmpv-dev/changelog.gz
> /usr/share/doc/libmpv-dev/copyright
> /usr/lib/x86_64-linux-gnu/libmpv.so
> 

Then I've applied the symbol:
`ln -s /usr/lib/x86_64-linux-gnu/libmpv.so  /usr/lib/libmpv.so.1 `

and it worked for me.

**Comment by loleg** [comment]
In the [documentation](https://flet.dev/docs/publish/linux#mpv-for-video) it currently says "[libmpv](https://mpv.io/) libraries must be installed if your Flet app uses Video control." This deserves more investigation, or the docs should be corrected if libmpv is a requirement for all projects.

**Comment by yashasolutions** [comment]
to add to @loleg, it would also be good to know which version is required, because I had lipmpv, just libmpv.so.2 didn't cut it and it required libmpv.so.1

**Comment by mayconrcampos** [comment]
Just to report this same error on OpenSUSE Tumbleweed.

$ error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory

**Comment by ivanhercaz** [comment]
I confirm this workaround works fine with Manjaro too! Thank you, @yashasolutions.

**Comment by pedrobezerra14** [comment]
Tive esse mesmo problema ao tentar rodar um programa em Python em uma distribuição Linux brasileira, Biglinux(que é baseada em Arch). 
A solução: 
` sudo ln -s /usr/lib/libmpv.so /usr/lib/libmpv.so.1`
Funcionou perfeitamente, muito obrigado @yashasolutions !!!!

English:

I had this same problem when trying to run a Python program on a Brazilian Linux distribution, Biglinux (which is based on Arch). 
The solution: 
` sudo ln -s /usr/lib/libmpv.so /usr/lib/libmpv.so.1`
It worked perfectly, thank you very much @yashasolutions!!!!

**Comment by Lucifer516-sudoer** [comment]
> Tive esse mesmo problema ao tentar rodar um programa em Python em uma distribuição Linux brasileira, Biglinux(que é baseada em Arch). A solução: ` sudo ln -s /usr/lib/libmpv.so /usr/lib/libmpv.so.1` Funcionou perfeitamente, muito obrigado @yashasolutions !!!!
> 
> English:
> 
> I had this same problem when trying to run a Python program on a Brazilian Linux distribution, Biglinux (which is based on Arch). The solution: ` sudo ln -s /usr/lib/libmpv.so /usr/lib/libmpv.so.1` It worked perfectly, thank you very much @yashasolutions!!!!

nice, but for me it is still not working, i am being asked to link multiple dependencies, I think flet team must jump into this pit and help us

**Comment by FeodorFitsner** [comment]
Hold on guys, I'm working on "light" version of desktop client for Linux with Audio/Video disabled: https://github.com/flet-dev/flet/issues/3163

**Comment by HenryAreiza** [comment]
In Ubuntu 24.04 LTS, I got the same error and solved it with this:

`sudo apt update`
`sudo apt install libmpv-dev libmpv2`
`sudo ln -s /usr/lib/x86_64-linux-gnu/libmpv.so /usr/lib/libmpv.so.1`

Credits for this YouTube tutorial: https://youtu.be/dA53LgkDFEw?si=Z7n8YpGLOfJ2q_tw

**Comment by MarceloMarot** [comment]
I've solved it in Fedora 39, creating the symlink in `/usr/lib64` instead of `/usr/lib` 
`sudo ln -s /usr/lib64/libmpv.so /usr/lib64/libmpv.so.1`

Also package names are different.
[Thanks to luizmarinhojr for the tutorial](https://gist.github.com/luizmarinhojr/f5ede39febd53fceb757eef88618f2b8)

**Comment by HamzaMateen** [comment]
> In Ubuntu 24.04 LTS, I got the same error and solved it with this:
> 
> `sudo apt update` `sudo apt install libmpv-dev libmpv2` `sudo ln -s /usr/lib/x86_64-linux-gnu/libmpv.so /usr/lib/libmpv.so.1`
> 
> Credits for this YouTube tutorial: https://youtu.be/dA53LgkDFEw?si=Z7n8YpGLOfJ2q_tw

This helped me! 
I am on:

Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic

**Comment by DarexD** [comment]
Solution in Ubuntu: https://github.com/DarexD/Solution-libmpv.so-Flet

I don't know if it works in other distributions.

**Comment by jiang131072** [comment]
libmpv.so.1 is an outdated version. See [Debian libmpv1 search result](https://packages.debian.org/search?keywords=libmpv1) and [Debian libmpv2 search result](https://packages.debian.org/search?keywords=libmpv2). Main stream Linux distros only provide libmpv2 now (refer to pkgs.org), so this problem is universal to desktop Linux.

**Comment by Vulturu1** [comment]
Hello all! I've been having this issue and have tried creating a symlink however that does not solve my issue. When I try to run my script I am still given the same error saying that libmpv.so.1 is not found. Anybody know what I could try next? P.S. I am running this script on a raspberry pi 4 with the full desktop version of RpiOS which uses Ubuntu 24.04 LTS.

**Comment by jdpask21** [comment]
Hello, I have Fixed this problem in Raspberry Pi 3 (RpiOS) with the following steps.
1. `sudo rm /usr/lib/libmpv.so.1` (This step is not necessary unless you have previously created a symbolic link to libmpv.so.1.)
2. `dpkg -L libmpv2` You may get the path where libmpv.so.2 was downloaded. (In my case, this path is `/usr/lib/aarch64-linux-gnu/libmpv.so.2`)
3. `sudo ln -s [path you get in step2] /usr/lib/libmpv.so.1`

If you installed libmvp1 instead of libmpv2, I think that you execute command `dpkg -L libmvp` or `dpkg -L libmpv1` in step2.

**Comment by Vulturu1** [comment]
Hello thank you so much for the reply I appreciate it. Unfortunately I have another issue. When trying the commands you gave me I was told that libmpv.so.2 was not installed. I followed another comment here which had told me how to install all of these packages. How can I install this package? Whats the package name?

**Comment by Vulturu1** [comment]
Thank you for your time and for the comment. It worked perfectly. Hopefully this issue will be fixed from the source in future updates. Thanks again!

**Comment by CodedIsTaken** [comment]
yet to find the solution on rawhide.

**Comment by FeodorFitsner** [comment]
Flet 0.25 pre-release includes a new "Light" version of Linux client: https://flet.dev/blog/flet-new-packaging-pre-release#light-client-for-linux

Try installing pre-release Flet with:

```
pip install flet --pre --upgrade
```

**Comment by bbaster** [comment]
@FeodorFitsner Removing all audio/video functionality for all Linux users is absolutely not a good solution, please rebuild against a current version of libraries

**Comment by bbaster** [comment]
It seems like it's actually an issue with a library, I will open an issue there.
My apologies for blaming this project

**Comment by ndonkoHenri** [comment]
> Flet 0.25 pre-release includes a new "Light" version of Linux client: https://flet.dev/blog/flet-new-packaging-pre-release#light-client-for-linux
> 
> Try installing pre-release Flet with:
> 
> ```
> pip install flet --pre --upgrade
> ```

A new Flet version with this has been released: `pip install 'flet[all]'`

**Comment by denis-mota** [comment]
> No Debian 12 - Debian GNU/Linux 12 (bookworm) Sendo root: a saída é:`apt install libmpv-dev mpv ``dpkg -L libmpv-dev`
> 
> > /usr /usr/include /usr/include/mpv /usr/include/mpv/client.h /usr/include/mpv/render.h /usr/include/mpv/render_gl.h /usr/include/mpv/stream_cb.h /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/pkgconfig /usr/lib/x86_64-linux-gnu/pkgconfig/mpv.pc /usr/share /usr/share/doc /usr/share/doc/libmpv-dev /usr/share/doc/libmpv-dev/changelog. Debian.gz /usr/share/doc/libmpv-dev/changelog.gz /usr/share/doc/libmpv-dev/copyright /usr/lib/x86_64-linux-gnu/libmpv.so
> 
> Em seguida, apliquei o símbolo: `ln -s /usr/lib/x86_64-linux-gnu/libmpv.so /usr/lib/libmpv.so.1 `
> 
> E funcionou para mim.

This worked for my Linux Mint Cinnamon.

**Comment by NonneTrapuE** [comment]
Hi ! 

Have the same problem with Flet on Rocky Linux 9.
Shared library is on /usr/lib64libmpv.so. I have tested install pre-release of Flet, link /usr/lib64/libmpv.so on /usr/lib/libmpv.so.1 but nothing have the same problem .

Can help me to fix this ?

**Comment by sqvist** [comment]
Hello, 
I have teh same issue as above... No matter how i install flet, i get the :

/home/fobar/.flet/bin/flet-0.27.1/flet/flet: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory

My installed packages is 
flet                      0.27.1
flet-desktop-light        0.27.1

I was under the impression that flet-desktop-light didnt need the libmpv?? :/

**Comment by cfjedimaster** [comment]
I hope it is ok to ask this in this particular issue as it seems on topic. While trying to follow the instructions to get things working under WSL, we're asked tgo: `sudo apt install libmpv-dev libmpv2`. This is returning: `Unable to locate package libmpv2`

**Comment by metal3d** [comment]
Flet uses an outdated libmpv for many distributions (Fedora has got libmpv 2). Maybe the maintainers should change the dependencies. Ubuntu is not the only one distribution.

**Comment by jonasreyes** [comment]
## English Version

**Subject:** Flet Linux Development Considerations  

Hello Flet community,  

I'm currently developing [DeepRoot](https://github.com/jonasreyes/deeproot), an API-based AI client with a strong focus on promoting GNU/Linux adoption. While I'm impressed with Flet's capabilities, I'd like to share some observations about desktop app development:  

- **File Picker Dependency:** The reliance on external file pickers remains a significant limitation  
- **libmpv.so.1 Concern:** This dependency creates substantial barriers for Linux developers  
  - The `flet-desktop-light` alternative still requires this library  
  - This affects beginner-friendly deployment  

**Positive Development:**  
Canaima GNU/Linux (Venezuelan distro) has committed to pre-installing `libmpv.so.1` in future releases  

**Additional Note:**  
Wayland compatibility issues have been observed  

Would appreciate the team's perspective on these matters.  

Best regards,  
Jonás Reyes  
Caracas, Venezuela  

---

## Versión en Español

**Asunto:** Consideraciones sobre desarrollo Linux con Flet  

Hola comunidad Flet,  

Actualmente desarrollo [DeepRoot](https://github.com/jonasreyes/deeproot), un cliente de IA que promueve GNU/Linux. Si bien Flet es excelente, tengo algunas observaciones:  

- **Selector de archivos:** La dependencia externa sigue siendo limitante  
- **Problema con libmpv.so.1:**  
  - La versión `flet-desktop-light` aún requiere esta biblioteca  
  - Esto complica el despliegue para usuarios nuevos  

**Avance positivo:**  
Canaima GNU/Linux (distro venezolana) incluirá `libmpv.so.1` por defecto  

**Nota adicional:**  
Se han detectado problemas con Wayland  

Agradecería conocer la postura del equipo.  

Saludos,  
Jonás Reyes  
Caracas, Venezuela  

---

## Русская версия (Russian)

**Тема:** Вопросы разработки под Linux с Flet  

Приветствую сообщество Flet,  

Я разрабатываю [DeepRoot](https://github.com/jonasreyes/deeproot) — клиент ИИ с акцентом на GNU/Linux. Хочу поделиться наблюдениями:  

- **Файловый диалог:** Внешняя зависимость остаётся проблемой  
- **Проблема libmpv.so.1:**  
  - Даже `flet-desktop-light` требует эту библиотеку  
  - Это усложняет развёртывание  

**Хорошие новости:**  
Дистрибутив Canaima GNU/Linux будет включать `libmpv.so.1`  

**Дополнительно:**  
Обнаружены проблемы с Wayland  

Буду рад обсудить эти вопросы.  

С уважением,  
Хонас Рейес  
Каракас, Венесуэла  

---

## 中文版本 (Chinese)

**主题:** 关于Flet Linux开发的反馈  

Flet社区大家好，  

我正在开发[DeepRoot](https://github.com/jonasreyes/deeproot)——一个基于API的AI客户端，致力于推广GNU/Linux。使用Flet时发现以下问题：  

- **文件选择器:** 外部依赖仍是限制因素  
- **libmpv.so.1问题:**  
  - `flet-desktop-light`版本仍需该库  
  - 影响新手用户的部署体验  

**积极进展:**  
Canaima GNU/Linux(委内瑞拉发行版)将预装`libmpv.so.1`  

**补充说明:**  
Wayland兼容性存在问题  

期待团队的看法。  

此致  
乔纳斯·雷耶斯  
委内瑞拉加拉加斯

**Comment by nnamnielk** [comment]
> I hope it is ok to ask this in this particular issue as it seems on topic. While trying to follow the instructions to get things working under WSL, we're asked tgo: `sudo apt install libmpv-dev libmpv2`. This is returning: `Unable to locate package libmpv2`

The following worked for me on WSL2 Ubuntu: 
`sudo apt install libmpv-dev && sudo ln -sf /usr/lib/x86_64-linux-gnu/libmpv.so.2 /usr/lib/x86_64-linux-gnu/libmpv.so.1`

**Comment by AcuityAce** [comment]
Just Figured id make sure everyone knows this is still a issue, im on open suse tumbleweed and i cant seem to get it working even after doing some tinkering with linking and such
