### ISSUE TITLE
Flet incompatible with Python version <= 3.8

### ISSUE THREAD

**Issue by xylophoneengine** [flet-dev/flet#2825]
**Description**

Running Flet as an async app does not work at all. Things do not load etc. However, most concerning is that when closing the app code is called which is not compatible with Python 3.8 or older.

[in flet_socket_server.py line 188](https://github.com/flet-dev/flet/blob/398a8d47c3710f4c772542dd928201dfe8c4b0cb/sdk/python/packages/flet-runtime/src/flet_runtime/flet_socket_server.py#L188) 
self.__executor.shutdown(wait=False, cancel_futures=True) is called. This calls shutdown in [ThreadPoolExecutor](https://docs.python.org/3.8/library/concurrent.futures.html#concurrent.futures.Executor).
Here the keyword cancel_futures does not exist.

I do not get this error with v0.20.2, but do get it with v0.21.0 and v0.21.1.
This leads me to believe, that Python 3.8 support has been dropped. Is this correct?

**Flet version (`pip show flet`)**:

```
pip show flet           
Name: flet
Version: 0.21.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python  
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: j:\mydata_afzw_de\hiwi_work\.venv\lib\site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by:
```

```
flet==0.21.0
```

**Operating system**:

Python 3.8.10

**Comment by xylophoneengine** [comment]
Closing due to incorrect life-cycle handling.
For others having the same issue:
`will_unmount` and `did_mount` now work with async apps as well
`async_will_unmount` and `async_did_mount` do not exist anymore.

**Comment by xylophoneengine** [comment]
Closed instead of adding example. I am sorry.

Minimal example: `
import flet as ft

async def main(page: ft.Page):
    await page.add_async(ft.Text("Hello, async world!"))

ft.app(main)
`

Error:`
PS J:\mydata_afzw_de\hiwi_work> python .\async_test.py
.\async_test.py:5: DeprecationWarning: Call to add_async() is deprecated since version 0.21.0 and will be removed in version 1.0. Use add() method instead.
  await page.add_async(ft.Text("Hello, async world!"))
Traceback (most recent call last):
  File ".\async_test.py", line 8, in <module>
    ft.app(main)
  File "J:\mydata_afzw_de\hiwi_work\.venv\lib\site-packages\flet_runtime\app.py", line 70, in app
    return asyncio.run(
  File "C:\Users\adria\scoop\apps\python38\current\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\adria\scoop\apps\python38\current\lib\asyncio\base_events.py", line 616, in run_until_complete    
    return future.result()
  File "J:\mydata_afzw_de\hiwi_work\.venv\lib\site-packages\flet_runtime\app.py", line 207, in app_async
    await conn.close()
  File "J:\mydata_afzw_de\hiwi_work\.venv\lib\site-packages\flet_runtime\flet_socket_server.py", line 188, in close
    self.__executor.shutdown(wait=False, cancel_futures=True)
TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001ED8165CC10>
Traceback (most recent call last):
  File "C:\Users\adria\scoop\apps\python38\current\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\adria\scoop\apps\python38\current\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\adria\scoop\apps\python38\current\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\adria\scoop\apps\python38\current\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
`

**Comment by FeodorFitsner** [comment]
Will take a look.

Python 3.7 is no longer supported, but 3.8 should be supported. Looks like `cancel_futures` argument was introduced in Python 3.9.
