### ISSUE TITLE
Issues with page.client_storage.set() function.

### ISSUE THREAD

**Issue by MaxXilon** [flet-dev/flet#2864]
**Description**

Tried using the page.client_storage.set() to store a list but it returned ValueError: Circular Reference detected.

**Code example to reproduce the issue:**

```import flet as ft


def main(page):
  colors=['red','blue','green',]

  page.add(ft.Card(ft.Text('hi')))

  colors+=page.controls

  page.client_storage.set('color',colors)

  page.update()

  x=page.client_storage.get('color')

  print (x)

ft.app(main)
```

**Describe the results you received:**

- Error logs: 
```
Unhandled error processing page session WLWZITQpiLLyQRQQ: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flet/fastapi/flet_app.py", line 140, in __on_session_created
    await asyncio.get_running_loop().run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/sdcard/snowLeopard/Cs.py", line 11, in main
    page.client_storage.set('color',colors)
  File "/usr/local/lib/python3.10/dist-packages/flet_core/client_storage.py", line 10, in set
    jv = self.__page._convert_attr_json(value)
  File "/usr/local/lib/python3.10/dist-packages/flet_core/control.py", line 139, in _convert_attr_json
    json.dumps(value, cls=EmbedJsonEncoder, separators=(",", ":"))
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/dist-packages/flet_core/embed_json_encoder.py", line 43, in encode
    return super().encode(self._convert_enums(o))
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
```

**Describe the results you expected:**

The input list displayed at the console.

**Additional information you deem important (e.g. issue happens only occasionally):**
- hot reload not functioning properly.

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.21.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by:
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet
```

**Operating system**:

- Linux
- Testing on Android.

Linux version:
Distributor ID: Ubuntu                                                        Description:    Ubuntu 22.04.4 LTS                                            Release:        22.04                                                         Codename:       jammy

Android version:
8.1.0

**Comment by burhansvural** [comment]
```python

import flet as ft

def main(page):
  colors=['red','blue','green']

  page.add(
    ft.Card(
        content=ft.Text('hi'))
    )

  colors+=page.controls

  print(colors)

  page.client_storage.set("color",str(colors))

  x=page.client_storage.get('color')

  print (x)

ft.app(main)

```

**Comment by burhansvural** [comment]
Also, an example of deleting a circular reference is available in the link below:
https://stackoverflow.com/questions/44777369/remove-circular-references-in-dicts-lists-tuples

**Comment by MaxXilon** [comment]
Thanks 😊,
