### ISSUE TITLE
You uploaded an APK or Android App Bundle that was signed in debug mode. You need to sign your APK or Android App Bundle in release mode. Find out more about signing.

### ISSUE THREAD

**Issue by sumitkanoje** [flet-dev/flet#2868]
**Description**

Installed the new version pip install flet==0.21.1
I built aab bundle using `flet build aab --no-ios-splash --verbose` command

After this when I tried uploading the aab file on google play console I got following error

```
You uploaded an APK or Android App Bundle that was signed in debug mode. You need to sign your APK or Android App Bundle in release mode. Find out more about signing.
```
<img width="1356" alt="Screenshot 2024-03-13 at 5 36 43 PM" src="https://github.com/flet-dev/flet/assets/10687127/ae79cf6a-2224-478c-b1a9-3ce9a2229fbc">

Below I'm pasting logs from flet build command

```
Flutter bootstrap directory: /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/flet_flutter_build_bGLZQZPuSa
Additional Flutter dependencies:
{}
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...Copying /Users/sumit/Works/Self/Flet/todo/assets/icon.png to /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/flet_flutter_build_bGLZQZPuSa/images
OK
Generating app icons...
Run subprocess: ['/Users/sumit/Works/Flutter/flutter-stable/bin/dart', 'run', 'flutter_launcher_icons']
Resolving dependencies in /private/var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/flet_flutter_build_bGLZQZPuSa... (4.8s)
Got dependencies in /private/var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/flet_flutter_build_bGLZQZPuSa.
Building package executable... (2.0s)
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)                               
  ════════════════════════════════════════════
  
• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...              done
Creating Icons for Windows...          done
Creating Icons for MacOS...            done

✓ Successfully generated launcher icons
OK
Generating splash screens...
Run subprocess: ['/Users/sumit/Works/Flutter/flutter-stable/bin/dart', 'run', 'flutter_native_splash:create']
Building package executable... (1.9s)
Built flutter_native_splash:create.
[Android] Creating default splash images
[Android] Creating dark mode splash images
[Android] Creating default android12splash images
[Android] Creating dark mode android12splash images
[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android] No android/app/src/main/res/values-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android] No android/app/src/main/res/values-night-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-night-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
[Web] Creating images
[Web] Creating images
[Web] Creating background images
[Web] Creating CSS
[Web] Updating index.html
╔════════════════════════════════════════════════════════════════════════════╗
║                       NEED A GREAT FLUTTER DEVELOPER?                      ║
╠════════════════════════════════════════════════════════════════════════════╣
║                                                                            ║
║   I am available!  Find me at https://www.linkedin.com/in/hansonjon/       ║
║                                                                            ║
╚════════════════════════════════════════════════════════════════════════════╝

✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash

OK
Packaging Python app...
Run subprocess: ['/Users/sumit/Works/Flutter/flutter-stable/bin/dart', 'run', 'serious_python:main', 'package', '/Users/sumit/Works/Self/Flet/todo', 
'--mobile', '--platform', 'mobile', '--dep-mappings', 'flet=flet-embed', '--req-deps', 'flet-embed', '--exclude', 'build']
Building package executable... (1.3s)
Built serious_python:main.
Running package command
Creating asset directory: /private/var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/flet_flutter_build_bGLZQZPuSa/app
Copying Python app from /Users/sumit/Works/Self/Flet/todo to /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/serious_python_tempYoMJ7M
Configured mobile platform with sitecustomize.py at /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/serious_python_sitecustomizeKi71iy/sitecustomize.py
Installing dependencies [flet-embed==0.21.1] with pip command to /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/serious_python_tempYoMJ7M/__pypackages__
Extracting Python distributive from /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/cpython-3.11.6+20231002-aarch64-apple-darwin-install_only.tar.gz to /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/hostpython3.11_DMExwb
Compiling Python sources at /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/serious_python_tempYoMJ7M
Delete unnecessary files with extensions: [.py, .c, .h, .typed, .exe, .so, .a, .pdb, .pyd, .dll]
Delete unnecessary files and directories: [__pycache__, bin]
Creating app archive at /private/var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/flet_flutter_build_bGLZQZPuSa/app/app.zip from /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/serious_python_tempYoMJ7M
Deleting temp directory /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/serious_python_tempYoMJ7M
Deleting sitecustomize directory /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/serious_python_sitecustomizeKi71iy
Deleting Python directory /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/hostpython3.11_DMExwb
OK
Building .aab bundle for Android...
Run subprocess: ['/Users/sumit/Works/Flutter/flutter-stable/bin/flutter', 'build', 'appbundle']
Resolving dependencies... (1.7s)
  fl_chart 0.65.0 (0.66.2 available)
  flutter_lints 2.0.3 (3.0.1 available)
  flutter_native_splash 2.3.7 (2.3.13 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.0 (10.0.4 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.3 available)
  leak_tracker_testing 2.0.1 (3.0.1 available)
  lints 2.1.1 (3.0.0 available)
  material_color_utilities 0.8.0 (0.11.0 available)
  meta 1.11.0 (1.12.0 available)
  package_info_plus 4.2.0 (5.0.1 available)
  petitparser 5.4.0 (6.0.2 available)
  test_api 0.6.1 (0.7.0 available)
  toml 0.14.0 (0.15.0 available)
  vm_service 13.0.0 (14.1.0 available)
  xml 6.3.0 (6.5.0 available)
Got dependencies!
16 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 212680 bytes (25.0% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1261080 bytes (23.3% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
/usr/local/share/android-sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-strip: error: '/private/var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/flet_flutter_build_bGLZQZPuSa/build/app/intermediates/merged_native_libs/release/out/lib/arm64-v8a/libpythonbundle.so': The file was not recognized as a valid object file

/usr/local/share/android-sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-strip: error: '/private/var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/flet_flutter_build_bGLZQZPuSa/build/app/intermediates/merged_native_libs/release/out/lib/armeabi-v7a/libpythonbundle.so': The file was not recognized as a valid object file

/usr/local/share/android-sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-strip: error: '/private/var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/flet_flutter_build_bGLZQZPuSa/build/app/intermediates/merged_native_libs/release/out/lib/x86_64/libpythonbundle.so': The file was not recognized as a valid object file

Running Gradle task 'bundleRelease'...                            122.5s
✓ Built build/app/outputs/bundle/release/app-release.aab (41.9MB).
OK
Copying build to build/aab directory...Copying build output from: /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/flet_flutter_build_bGLZQZPuSa/build/app/outputs/bundle/release/*
OK
Deleting Flutter bootstrap directory /var/folders/cy/y7tc39gd75q3vk5lmn9_z7xc0000gn/T/flet_flutter_build_bGLZQZPuSa
Success!
```

**Operating system**:
I'm on Mac OS Sonoma 14.3.1 (23D60)

**Additional Details**:

flutter doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.3.1 23D60 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.87.0)
[✓] Connected device (2 available)
[✓] Network resources
```

**Comment by applicatlat** [comment]
could you find a solution to it?

**Comment by xkayo32** [comment]
Did you manage to solve the problem?

**Comment by sumitkanoje** [comment]
@xkayo32 @applicatlat Nope, did not hear anything on this from @flet team yet

**Comment by yucel685** [comment]
Aynı sorunu yaşıyorum. Serious_python ile flutteri imzalayarak çalıştırmayı denedim. Ama serious_python os error erno 2 hatasını aşamadım

**Comment by jeongyoungki** [comment]
I found a reason why this happen.
I'm not 100% sure but i guess.
because of client/android/app/bundle.gradle file

in the git-hub : https://github.com/flet-dev/flet/blob/main/client/android/app/build.gradle


![image](https://github.com/flet-dev/flet/assets/82494261/401fa567-edbb-452f-b4e1-cbff4d11804c)


that must be fix like this .

![image](https://github.com/flet-dev/flet/assets/82494261/d288bc08-52dc-4c98-a32f-fb34b6a9a6f9)

I don't know how to build apk ... 

I think while building the apk flet must use bundle.gradle ... and because of 'debug' flag the apk which we built can not be uploaded correctly in play store console.

need change.

**Comment by jeongyoungki** [comment]
I referenced this site : https://luvris2.tistory.com/833

**Comment by fasilwdr** [comment]
@jeongyoungki  Could you please provide the updated version repo of  flet-build-template?

@ndonkoHenri

**Comment by ajaysehwal** [comment]
but in flet_template where we found android folder

**Comment by filiperochalopes** [comment]
It can be solved with command 

```sh
flet build aab --android-signing-key-store-password mypass --android-signing-key-password mypass --android-signing-key-store /path/to/keystore.jks
```

It was how I solved my issue like that. I think this issue can be marked as solved @ndonkoHenri

**Comment by FeodorFitsner** [comment]
Thanks @filiperochalopes ...and signing can be configuring in `pyproject.toml` as well: https://flet.dev/docs/publish/android#signing-android-bundle

**Comment by yoberner** [comment]
Hi all,
when I run:
`flet build aab --template-dir /Users/user/mygit/flet-build-template`
I get this error:

```
[04:22:35] JDK installed ✅                                                                                                                                           
           Android SDK installed ✅                                                                                                                                   
[04:22:36] Created Flutter bootstrap project from gh:flet-dev/flet-build-template with ref "0.26.0" ✅                                                                
[04:22:39] Unhandled exception:                                                                                                                                       
           Could not find an option named "--requirements".                                                                                                           
                                                                                                                                                                      
           Usage: dart run serious_python:main package                                                                                                                
           -h, --help            Print this usage information.                                                                                                        
               --pre             Install pre-release dependencies.                                                                                                    
               --mobile          Package for mobile.                                                                                                                  
               --web             Package for web.                                                                                                                     
               --verbose         Verbose output.                                                                                                                      
           -a, --asset           Asset path, relative to pubspec.yaml, to package Python program into.                                                                
               --dep-mappings    Pip dependency mappings in the format 'dep1>dep2,dep3>dep4'.                                                                         
               --req-deps        Required pip dependencies in the format 'dep1,dep2==version,...'                                                                     
               --find-links      Path or URL to HTML page with links to wheels.                                                                                       
               --platform        Make pip to install dependencies for this platform, e.g. 'emscripten_3_1_45_wasm32'. An attempt to install native Python modules will
           raise an error.                                                                                                                                            
               --exclude         List of relative paths to exclude from app package, e.g. "assets,build".                                                             
                                                                                                                                                                      
           Run "dart run serious_python:main help" to see global options.                                                                                             
           #0      Command.usageException (package:args/command_runner.dart:466:7)                                                                                    
           #1      CommandRunner.parse (package:args/command_runner.dart:140:15)                                                                                      
           #2      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:36)                                                                    
           #3      new Future.sync (dart:async/future.dart:313:27)                                                                                                    
           #4      CommandRunner.run (package:args/command_runner.dart:122:14)                                                                                        
           #5      main (file:///Users/yonatanberner/.pub-cache/hosted/pub.dev/serious_python-0.7.1/bin/main.dart:10:16)                                              
           #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)                                                      
           #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)                                                                      
                                                                                                                                                                      
[04:22:46] Doctor summary (to see all details, run flutter doctor -v):                                                                                                
           [✓] Flutter (Channel stable, 3.27.3, on macOS 15.2 24C101 darwin-arm64, locale en-US)                                                                      
           [✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)                                                                           
           [✓] Xcode - develop for iOS and macOS (Xcode 16.2)                                                                                                         
           [✓] Chrome - develop for the web                                                                                                                           
           [✓] Android Studio (version 2024.2)                                                                                                                        
           [✓] IntelliJ IDEA Ultimate Edition (version 2024.2.0.2)                                                                                                    
           [✓] VS Code (version 1.97.0)                                                                                                                               
           [✓] Connected device (4 available)                                                                                                                         
           [✓] Network resources                                                                                                                                      
                                                                                                                                                                      
           • No issues found!                                                                                                                                         
Error building Flet app - see the log of failed command above.
```

Anyone have any ideas why?
When I run just `flet build aab` it builds fine. I just need it to work with the template.

Thanks!

**Comment by FeodorFitsner** [comment]
@yoberner If have to use `--template` argument with the path/URL to a repository with the template. `--template-dir` is a directory *within* the repository. `--template-ref` is a ref ID for Git-like repos.

More info here: https://flet.dev/docs/publish#customizing-packaging-template

**Comment by ndonkoHenri** [comment]
@yoberner your build-template clone should be based off the latest branch/tag (0.26.0 atm) of the official build template.

**Comment by kumar2215** [comment]
@FeodorFitsner I forked the template repo and made changes to it. I then ran flet build aab --template "https://github.com/kumar2215/flet-build-template.git" --template-ref d36c88d1622b5bcc861b1d497b9d36e9d7a23759 but the build still fails with:

```
[13:56:55] Flutter 3.27.3 installed ✅                                                                                                                                              
           JDK installed ✅                                                                                                                                                         
           Android SDK installed ✅                                                                                                                                                 
[13:56:59] Created Flutter bootstrap project from https://github.com/kumar2215/flet-build-template.git with ref "d36c88d1622b5bcc861b1d497b9d36e9d7a23759" ✅                       
[13:57:02] Unhandled exception:                                                                                                                                                     
           Could not find an option named "--requirements".                                                                                                                         
                                                                                                                                                                                    
           Usage: dart run serious_python:main package                                                                                                                              
           -h, --help            Print this usage information.                                                                                                                      
               --pre             Install pre-release dependencies.                                                                                                                  
               --mobile          Package for mobile.                                                                                                                                
               --web             Package for web.                                                                                                                                   
               --verbose         Verbose output.                                                                                                                                    
           -a, --asset           Asset path, relative to pubspec.yaml, to package Python program into.                                                                              
               --dep-mappings    Pip dependency mappings in the format 'dep1>dep2,dep3>dep4'.                                                                                       
               --req-deps        Required pip dependencies in the format 'dep1,dep2==version,...'                                                                                   
               --find-links      Path or URL to HTML page with links to wheels.                                                                                                     
               --platform        Make pip to install dependencies for this platform, e.g. 'emscripten_3_1_45_wasm32'. An attempt to install native Python modules will raise an     
           error.                                                                                                                                                                   
               --exclude         List of relative paths to exclude from app package, e.g. "assets,build".                                                                           
                                                                                                                                                                                    
           Run "dart run serious_python:main help" to see global options.                                                                                                           
           #0      Command.usageException (package:args/command_runner.dart:466:7)                                                                                                  
           #1      CommandRunner.parse (package:args/command_runner.dart:140:15)                                                                                                    
           #2      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:36)                                                                                  
           #3      new Future.sync (dart:async/future.dart:313:27)                                                                                                                  
           #4      CommandRunner.run (package:args/command_runner.dart:122:14)                                                                                                      
           #5      main (file:///C:/Users/Kumar%20Lenovo%20PC/AppData/Local/Pub/Cache/hosted/pub.dev/serious_python-0.7.1/bin/main.dart:10:16)                                      
           #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)                                                                    
           #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)                                                                                    
                                                                                                                                                                                    
[13:57:09] Doctor summary (to see all details, run flutter doctor -v):                                                                                                              
           [√] Flutter (Channel stable, 3.27.3, on Microsoft Windows [Version 10.0.22631.4890], locale en-SG)                                                                       
           [√] Windows Version (Installed version of Windows is version 10 or higher)                                                                                               
           [√] Android toolchain - develop for Android devices (Android SDK version 35.0.1)                                                                                         
           [√] Chrome - develop for the web                                                                                                                                         
           [√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)                                                                                           
           [√] Android Studio (version 2024.2)                                                                                                                                      
           [√] IntelliJ IDEA Ultimate Edition (version 2024.3)                                                                                                                      
           [√] VS Code (version 1.97.2)                                                                                                                                             
           [√] Connected device (3 available)                                                                                                                                       
           [√] Network resources                                                                                                                                                    

           • No issues found!                                                                                                                                                       

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Error building Flet app - see the log of failed command above.                                                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by ahmedlemine** [comment]
Tried all the solutions presented here carefully and none worked. Thank you all.

**Comment by beedell-roke** [comment]
@ahmedlemine, likewise. [`stackoverflow.com/a/61180311`](https://stackoverflow.com/a/61180311/9731176) corroborates that `signingConfig` should exist inside `build.gradle`, but whether Kotlin or Groovy DSL, I've been unable to locate it in an empty API 36 activity, created in `android-studio-2025.2.2.8-1.fc43`.

**Comment by beedell-roke** [comment]
> [`#issuecomment-3797115913`](https://github.com/flet-dev/flet/issues/2868#issuecomment-3797115913)

@ahmedlemine, the solution was as I have since described at [`stackoverflow.com/a/79875975`](https://stackoverflow.com/a/79875975/9731176) — [`developer.android.com/studio/publish/app-signing#sign-apk`](https://developer.android.com/studio/publish/app-signing#sign-apk:~:text=Play%20App%20Signing%2E-,Generate%20an%20upload%20key%20and,as%20shown%20in%20figure%205%2E,-Now%20you%E2%80%99re%20ready). [^1] [^2]

[^1]: [`discussions.unity.com/t/152815/3`](https://discussions.unity.com/t/how-to-sign-apk-in-release-mode/152815/3)

[^2]: [`forum.cocosengine.org/t/25906/3`](https://forum.cocosengine.org/t/how-to-build-an-apk-in-in-release-mode-from-android-studio/25906/3)
