### ISSUE TITLE
Error running app after adding selenium library to my app

### ISSUE THREAD

**Issue by sjswnf** [flet-dev/flet#2899]
I am trying to build a windows app.

I added **selenium** library to my app. It runs well before building(using 'flet run' command).

But it fails after building windows app(using 'flet build windows').

This is the error message when running .exe file after building.

-------

Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\main.py", line 1, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\flet\__init__.py", line 1, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\flet_runtime\__init__.py", line 1, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\flet_core\__init__.py", line 178, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\flet_core\page.py", line 65, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\flet_runtime\auth\__init__.py", line 1, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\flet_runtime\auth\authorization.py", line 8, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\httpx\__init__.py", line 2, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\httpx\_api.py", line 6, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\httpx\_client.py", line 32, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\httpx\_transports\default.py", line 32, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\httpcore\__init__.py", line 1, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\httpcore\_api.py", line 5, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\httpcore\_sync\__init__.py", line 1, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\httpcore\_sync\connection.py", line 12, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\httpcore\_synchronization.py", line 11, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\trio\__init__.py", line 76, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\trio\_path.py", line 99, in <module>
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\trio\_path.py", line 116, in Path
  File "C:\Users\JJ\AppData\Local\Temp\serious_python_tempd9e19e95\__pypackages__\trio\_path.py", line 41, in decorator
AssertionError

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.20.2
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
```

**Operating system**:
Windows 11

**Comment by 808Grayson** [comment]
I also have the same issue with the same exact output. You can get around it by using flet pack instead

**Comment by Furim** [comment]
could someone give a possible fix how to fix that? because im trying to put it in requirements.txt and app just crashes instantly when compiled unto .apk

**Comment by ndonkoHenri** [comment]
I gave it a try with the latest Flet version on CI and it worked on my windows 11 UTM VM. 

- [repo](https://github.com/ndonkoHenri/test-flet-github-actions/tree/150e53c733f3c0b67d4a8873f5bef1270d86d770)
- [workflow](https://github.com/ndonkoHenri/test-flet-github-actions/actions/runs/22103280174/job/63878646954)
- [artifact](https://github.com/ndonkoHenri/test-flet-github-actions/actions/runs/22103280174) - you can download the `windows-artifact` to test

Let know if you face any issues.
