### ISSUE TITLE
ft.app(view=None) is not properly handled

### ISSUE THREAD

**Issue by BrownNPC** [flet-dev/flet#3000]
**Description**

I wanted to run a flet app webserver and not automatically open a browser and neither did want to open up a window. This used to be possible by setting view=None in ft.app but now it's broken. 
This also breaks this documentation section about [self hosting on nginx](https://flet.dev/docs/guides/python/deploying-web-app/hosting-providers/self-hosting/#sample-mainpy-flet-app)
**Code example to reproduce the issue:**

```python
import flet as ft

def main(page: ft.Page):
    page.title = "Flet counter example"
    page.vertical_alignment = ft.MainAxisAlignment.CENTER

    txt_number = ft.TextField(value="0", text_align=ft.TextAlign.RIGHT, width=100)

    def minus_click(e):
        txt_number.value = str(int(txt_number.value) - 1)
        page.update()

    def plus_click(e):
        txt_number.value = str(int(txt_number.value) + 1)
        page.update()

    page.add(
        ft.Row(
            [
                ft.IconButton(ft.icons.REMOVE, on_click=minus_click),
                txt_number,
                ft.IconButton(ft.icons.ADD, on_click=plus_click),
            ],
            alignment=ft.MainAxisAlignment.CENTER,
        )
    )

ft.app(view=None, port=8080, target=main)
```

**Describe the results you received:**
The app crashes 

The code does not handle view=None properly. 
```Traceback (most recent call last):
  File "/home/linus/coding-projects/timer/main.py", line 66, in <module>
    ft.app(main, web_renderer="html", port=8000, view=None)
  File "/home/linus/coding-projects/timer/.venv/lib64/python3.11/site-packages/flet_runtime/app.py", line 70, in app
    return asyncio.run(
           ^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/linus/coding-projects/timer/.venv/lib64/python3.11/site-packages/flet_runtime/app.py", line 208, in app_async
    await conn.close()
  File "/home/linus/coding-projects/timer/.venv/lib64/python3.11/site-packages/flet/fastapi/serve_fastapi_web_app.py", line 20, in close
    await self.server.shutdown()
  File "/home/linus/coding-projects/timer/.venv/lib64/python3.11/site-packages/uvicorn/server.py", line 261, in shutdown
    for server in self.servers:
                  ^^^^^^^^^^^^
AttributeError: 'Server' object has no attribute 'servers'. Did you mean: 'serve'?
```
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

This also breaks this documentation section about [self hosting on nginx](https://flet.dev/docs/guides/python/deploying-web-app/hosting-providers/self-hosting/#sample-mainpy-flet-app)
**Flet version (`pip show flet`)**:
0.21.2
**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet
```

**Operating system**:

linux, fedora 39
**Additional environment details:**
python 3.11

**Comment by HouWhalee1222** [comment]
Same issue, just want to open the app in the browser on another tablet instead of open on localhost automatically
