### ISSUE TITLE
After app build application can not find python package

### ISSUE THREAD

**Issue by fredykoci** [flet-dev/flet#3001]
![Snímek obrazovky 2024-04-08 v 12 41 50](https://github.com/flet-dev/flet/assets/18038918/183d40c2-ac22-4f0b-9fb5-9f0433b4ad64)

after build on macos

flet version 0.21.2
python version 3.9.6
on mac silicon

**Comment by marc-svg** [comment]
I think it the same same issue:
from simple flet app: 

import flet as ft
def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))
ft.app(main)

Error running app
Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/var/folders/1b/pmdh6fxx4514vl_t0n8ct1w80000gn/T/serious_python_tempeqE4G4/main.py", line 1, in <module>
  File "/var/folders/1b/pmdh6fxx4514vl_t0n8ct1w80000gn/T/serious_python_tempeqE4G4/__pypackages__/flet/__init__.py", line 1, in <module>
  File "/var/folders/1b/pmdh6fxx4514vl_t0n8ct1w80000gn/T/serious_python_tempeqE4G4/__pypackages__/flet_runtime/__init__.py", line 1, in <module>
  File "/var/folders/1b/pmdh6fxx4514vl_t0n8ct1w80000gn/T/serious_python_tempeqE4G4/__pypackages__/flet_core/__init__.py", line 1, in <module>
  File "/var/folders/1b/pmdh6fxx4514vl_t0n8ct1w80000gn/T/serious_python_tempeqE4G4/__pypackages__/flet_core/audio.py", line 4, in <module>
  File "/var/folders/1b/pmdh6fxx4514vl_t0n8ct1w80000gn/T/serious_python_tempeqE4G4/__pypackages__/flet_core/control.py", line 11, in <module>
  File "/var/folders/1b/pmdh6fxx4514vl_t0n8ct1w80000gn/T/serious_python_tempeqE4G4/__pypackages__/flet_core/utils/__init__.py", line 1, in <module>
  File "/var/folders/1b/pmdh6fxx4514vl_t0n8ct1w80000gn/T/serious_python_tempeqE4G4/__pypackages__/flet_core/utils/concurrency_utils.py", line 1, in <module>
  File "./asyncio/__init__.py", line 8, in <module>
  File "./asyncio/base_events.py", line 25, in <module>
  File "/Users/appveyor/projects/serious-python/dist/root/python3/lib/python3.11/subprocess.py", line 104, in <module>
ModuleNotFoundError: No module named '_posixsubprocess'


After build on mac and running on iPhone 15 Pro

flet version 0.20.0
python 3.12.2
on mac silicon

had the same issue since flet 0.21.2 but thought would be solved with new flet version

Thanks

**Comment by marc-svg** [comment]
flet version 0.22.0. 
sorry

**Comment by phanstudio** [comment]
i encountered the problem, i just added the library to the requirements.txt eg.
uuid==1.30
flet

**Comment by phanstudio** [comment]
try this it should help. i still have an issue:
C:\Users\ajuga\AppData\Local\Android\sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-strip.exe: error: 'C:\Users\ajuga\AppData\Local\Temp\flet_flutter_build_b66Tj6w6Ss\build\serious_python_android\intermediates\merged_native_libs\release\out\lib\arm64-v8a\libpythonbundle.so': The file was not recognized as a valid object file  

C:\Users\ajuga\AppData\Local\Android\sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-strip.exe: error: 'C:\Users\ajuga\AppData\Local\Temp\flet_flutter_build_b66Tj6w6Ss\build\serious_python_android\intermediates\merged_native_libs\release\out\lib\armeabi-v7a\libpythonbundle.so': The file was not recognized as a valid object file

C:\Users\ajuga\AppData\Local\Android\sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-strip.exe: error: 'C:\Users\ajuga\AppData\Local\Temp\flet_flutter_build_b66Tj6w6Ss\build\serious_python_android\intermediates\merged_native_libs\release\out\lib\x86_64\libpythonbundle.so': The file was not recognized as a valid object file

**Comment by ndonkoHenri** [comment]
Please give a try to latest Flet version. 
If anyone faces an issue, report using the [bug issue-template](https://github.com/flet-dev/flet/issues/new?assignees=&labels=&projects=&template=01_bug_report.yml).
