### ISSUE TITLE
build ipa success when no --team but failed when --team=‘MyTeamId’

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/flet#3127]
**Description**

build ipa success when no --team but failed when --team=‘MyTeamId’

**Code example to reproduce the issue:**

```sh
flet build --build-number=1 --build-version="1.0.0"  -vv ipa  # success
flet build --build-number=1 --build-version="1.0.0" --team="XXXXXXXXXX" -vv ipa  # failed!!
```

**Describe the results you received:**

...
[ +15 ms] Failed to build iOS app

[ +2 ms] Error (Xcode): No profiles for 'com.flet.sss_laser_studio' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.flet.sss_laser_studio'. Automatic signing is

disabled

       and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.

       /var/folders/y0/vj8btd8n62ng7kl8s810xl440000gn/T/flet_flutter_build_dMHWaluCp9/ios/Runner.xcodeproj
[ +2 ms] It appears that there was a problem signing your application prior to installation on the device.

[ ] Verify that the Bundle Identifier in your project is your signing id in Xcode

[ ] open ios/Runner.xcworkspace

[ ] Also try selecting 'Product > Build' to fix the problem.

[ +3 ms] "flutter ipa" took 242,430ms.

[ +4 ms] Encountered error while archiving for device.

[ ]

       #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)

       #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:680:7)

       <asynchronous suspension>

       #2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:425:50)

       <asynchronous suspension>

       #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)

       <asynchronous suspension>

       #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)

       <asynchronous suspension>

       #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)

       <asynchronous suspension>

       #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)

       <asynchronous suspension>

       #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)

       <asynchronous suspension>

       #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)

       <asynchronous suspension>

       #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)

       <asynchronous suspension>

       #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)

       <asynchronous suspension>

       #11     main (package:flutter_tools/executable.dart:90:3)

       <asynchronous suspension>
...

**Describe the results you expected:**

success.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
(.venv) hgcdeMac-mini:plan hgc$ pip show flet
Name: flet
Version: 0.22.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page: 
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: /Users/hgc/workspace/plan/.venv/lib/python3.11/site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by: 
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
flet==0.22.*
```

**Operating system**:

macOS Sonoma  14.4.1

**Additional environment details:**
flutter: 3.19.6

**Comment by ndonkoHenri** [comment]
Please provide information and context as required by the issue template.

**Comment by BrentHuang** [comment]
> Please provide information and context as required by the issue template.

OK

**Comment by jaluscg** [comment]
Maybe it's because of the argument "--no-codesing" that it's implemented in an implicit way when you don't put the "--team" parameter in the CI Docs called build.py

**Comment by justinkumpe** [comment]
I am having this same issue but have not had the time to gather the info needed to properly debug the issue. I can say flet is signing with iOS App Development. This is wrong, it should be signing with iOS App Distribution.

**Comment by yoberner** [comment]
Any update on this?

**Comment by ndonkoHenri** [comment]
We are working on improving ipa packaging in #4868

**Comment by ndonkoHenri** [comment]
Closing this issue in favor of #4869
