### ISSUE TITLE
ValueError: 'hide' is not a valid WindowEventType

### ISSUE THREAD

**Issue by 3mora2** [flet-dev/flet#3505]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

```py
            self.page.window.visible = False
            self.page.update()
```
```
asyncio:ERROR:Task exception was never retrieved
future: <Task finished name='Task-53' coro=<__run_socket_server.<locals>.on_event() done, defined at E:\Projects\temp project\AListerFlet\venv_pyins\Lib\site-packages\flet_runtime\app.py:217> exception=ValueError("'hide' is not a valid WindowEventType")>
Traceback (most recent call last):
  File "E:\Projects\temp project\AListerFlet\venv_pyins\Lib\site-packages\flet_runtime\app.py", line 219, in on_event
    await conn.sessions[e.sessionID].on_event_async(
  File "E:\Projects\temp project\AListerFlet\venv_pyins\Lib\site-packages\flet_core\page.py", line 914, in on_event_async
    await handler(ce)
  File "E:\Projects\temp project\AListerFlet\venv_pyins\Lib\site-packages\flet_core\event_handler.py", line 18, in fn
    ce = self.__result_converter(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\temp project\AListerFlet\venv_pyins\Lib\site-packages\flet_core\page.py", line 157, in <lambda>
    self.__on_event = EventHandler(lambda e: WindowEvent(e))
                                             ^^^^^^^^^^^^^^
  File "E:\Projects\temp project\AListerFlet\venv_pyins\Lib\site-packages\flet_core\page.py", line 3074, in __init__
    self.type = WindowEventType(e.data)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ammar\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 714, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ammar\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 1130, in __new__
    raise ve_exc
ValueError: 'hide' is not a valid WindowEventType
```

### Code

```py
            self.page.window.visible = False
            self.page.update()
```

### To reproduce

add `'hide'` to `WindowEventType `in `flet_core\types.py`

### Operating System

Windows

### Operating system details

win64

### Flet version

v0.23.1

### Regression

I'm not sure / I don't know

**Comment by 3mora2** [comment]
+ 
`ValueError: 'show' is not a valid WindowEventType`

**Comment by FebCodeGeek** [comment]
+1
I have the same problem.
