### ISSUE TITLE
Running Flet app on web browser fails

### ISSUE THREAD

**Issue by AbdouSadou** [flet-dev/flet#3526]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Running simple Flet app with parameter `view=ft.AppView.WEB_BROWSER` throws an error. The webpage opens on localhost (1270.0.0.1:58009) with an `Internal Server Error`.

Running the app as normal (desktop) without the parameter works fine.

### Code

```py
import flet as ft

def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))

ft.app(target=main, view=ft.AppView.WEB_BROWSER)
```

### To reproduce

Just run provided sample code

### Expected behavior

Opens a webpage on default browser, displaying "Hello flet".

### Screenshots

Error thrown on run:

```bash
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/flet/fastapi/flet_static_files.py", line 83, in __call__
    await self.__once.do(self.__config, scope["root_path"])
  File "/usr/lib/python3.12/site-packages/flet_runtime/utils/once.py", line 13, in do
    await func(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/flet/fastapi/flet_static_files.py", line 120, in __config
    raise Exception(f"Web root path not found: {web_dir}")
Exception: Web root path not found: /usr/lib/python3.12/site-packages/flet/web
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.12/site-packages/flet/fastapi/flet_static_files.py", line 83, in __call__
    await self.__once.do(self.__config, scope["root_path"])
  File "/usr/lib/python3.12/site-packages/flet_runtime/utils/once.py", line 13, in do
    await func(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/flet/fastapi/flet_static_files.py", line 120, in __config
    raise Exception(f"Web root path not found: {web_dir}")
Exception: Web root path not found: /usr/lib/python3.12/site-packages/flet/web
```

The webpage opens on localhost (1270.0.0.1:58009) with an `Internal Server Error`
![image](https://github.com/flet-dev/flet/assets/24844115/044e6460-b290-45bf-83a7-47b293072b70)

### Operating System

Linux

### Operating system details

EndeavourOS (on kernel 6.9.6-arch1-1)

### Flet version

python-flet 0.23.1-1

### Regression

I'm not sure / I don't know

**Comment by mriscoc** [comment]
I had similar error in a web deployment test on Windows 11:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
...
...
 File "flet\fastapi\flet_static_files.py", line 120, in __config
Exception: Web root path not found: W:\Python\CaptureUI\dist\Capture\_internal\flet\web
```

**Comment by ndonkoHenri** [comment]
What is the output of running the below command:
```bash
printenv | grep FLET
```

**Comment by mriscoc** [comment]
> What is the output of running the below command:

![image](https://github.com/user-attachments/assets/3c91c7c3-84ac-49c9-a1d8-0484a32e9466)

**Comment by AbdouSadou** [comment]
> What is the output of running the below command:
@ndonkoHenri Empty output. Should I set an env variable for flet ?

![image](https://github.com/user-attachments/assets/4ea68d82-9e2f-437e-b671-9359faaa77d5)

**Comment by betopolione** [comment]
I am getting the same problem running on NixOS

**Comment by taaaf11** [comment]
I am on Windows and I am experiencing the same error (i.e. Exception: Web root path not found: E:\flet\client\build\web
)

**Comment by ndonkoHenri** [comment]
Can you please try the [latest release](https://flet.dev/blog/flet-1-0-beta) and let know if the issue still happens?

**Comment by ndonkoHenri** [comment]
If anyone faces issues with one of the latest releases, please open a new ticket with details.
