### ISSUE TITLE
Flet app startup issue in Windows Build 

### ISSUE THREAD

**Issue by wpritom** [flet-dev/flet#3736]
Inconsistent performance in Windows build has been observed. There are 3 scenarios after running the executable file. 

1. UI Loads instantly
2. UI loads after a waiting for a few seconds
3. UI does not load even after 10 seconds. (seems like app has been crashed) 

There is no way to sense the reason behind this behavior. This happens for as simple code as following: 

```python
import datetime
import flet as ft

def notify_user(e):
   pass
    
async def main(page: ft.Page):

    tool_column = ft.Column([ft.Text("HELLO")])

    page.add(
        tool_column
        )

ft.app(main)

```` 
The app is build with the following command. 

```
flet build windows --project sample--module-name app.py --output build --verbose
```

OS : Windows 11 
Python: 3.12.4
Flet: 0.23.2
Flutter: 3.22.3 

The build is also tested in other desktops. The behavior was same.

**Comment by suifeng2018** [comment]
the same issue! UI loading very slower

**Comment by imadityacoder** [comment]
It also happening with me. UI not refresh automatically.

**Comment by ndonkoHenri** [comment]
Will you guys mind sharing a screen record?

**Comment by baseplate-admin** [comment]
Sounds like the issue i faced in
- https://github.com/flet-dev/flet/issues/3738

---

> Will you guys mind sharing a screen record?

I shared a screen record

**Comment by VordyV** [comment]
I observe the same situation. 

https://github.com/user-attachments/assets/2714be92-4d20-4f74-b6fa-d7005266d146

**Comment by wpritom** [comment]
This problem still remains in the latest version (0.24.0).

**Comment by imadityacoder** [comment]
It is also happening in android 


Uploading XRecorder_Edited_10102024_074201.mp4…

**Comment by Wanna-Pizza** [comment]
Same to me @ndonkoHenri 

I have same issue. Sometimes app starting properly, but almost all time its just white/black screen.

**Comment by baebranch** [comment]
I have the same issue on windows with  `flet v0.25.1`

**Comment by Abduguru** [comment]
> It is also happening in android 
> 
> 
> 
> https://github.com/user-attachments/assets/b2eb70de-382d-44b1-8e35-56bee07642f0.mp4
> 
> 
> 
> 

Did you remove splash screen

**Comment by 2dig4it** [comment]
Possibly related issue for regular execution/start in Windows (Windows 10). 
- no influence by Windows Defender
- no influence by Windows Firewall
- no influence with fresh Python Installation

Very slow execution (~10..12s) in case of: 
**import flet (even for simple applications) or
"flet --version" command on commandline** 

Random manual interruption will lead to C:\env\Python310-32\lib\site-packages\flet\core\icons.py, which therefore consumes **A LOT of processing time.** in our case.

The issue started (in our case) with an update to newest version, and was not observed previously. Revert to older versions did not help.

C:\Users\PRODAT>flet --version
Traceback (most recent call last):
  File "C:\env\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\env\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\env\Python310-32\Scripts\flet.exe\__main__.py", line 4, in <module>
  File "C:\env\Python310-32\lib\site-packages\flet\__init__.py", line 1, in <module>
    from flet.app import app, app_async
  File "C:\env\Python310-32\lib\site-packages\flet\app.py", line 12, in <module>
    from flet.core.page import Page
  File "C:\env\Python310-32\lib\site-packages\flet\core\page.py", line 32, in <module>
    from flet.core.adaptive_control import AdaptiveControl
  File "C:\env\Python310-32\lib\site-packages\flet\core\adaptive_control.py", line 3, in <module>
    from flet.core.control import Control
  File "C:\env\Python310-32\lib\site-packages\flet\core\control.py", line 18, in <module>
    from flet.core.badge import Badge, BadgeValue
  File "C:\env\Python310-32\lib\site-packages\flet\core\badge.py", line 5, in <module>
    from flet.core.text_style import TextStyle
  File "C:\env\Python310-32\lib\site-packages\flet\core\text_style.py", line 5, in <module>
    from flet.core.box import BoxShadow
  File "C:\env\Python310-32\lib\site-packages\flet\core\box.py", line 6, in <module>
    from flet.core.border import Border
  File "C:\env\Python310-32\lib\site-packages\flet\core\border.py", line 5, in <module>
    from flet.core.types import ColorValue, OptionalNumber
  File "C:\env\Python310-32\lib\site-packages\flet\core\types.py", line 28, in <module>
    from flet.core.icons import Icons, icons
  **File "C:\env\Python310-32\lib\site-packages\flet\core\icons.py", line 29, in <module>
    class icons(str, Enum, metaclass=IconsDeprecated):**
  File "C:\env\Python310-32\lib\enum.py", line 302, in __new__
    if canonical_member._value_ == enum_member._value_:
KeyboardInterrupt
^C
C:\Users\PRODAT>flet --version
Traceback (most recent call last):
  File "C:\env\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\env\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\env\Python310-32\Scripts\flet.exe\__main__.py", line 4, in <module>
  File "C:\env\Python310-32\lib\site-packages\flet\__init__.py", line 1, in <module>
    from flet.app import app, app_async
  File "C:\env\Python310-32\lib\site-packages\flet\app.py", line 12, in <module>
    from flet.core.page import Page
  File "C:\env\Python310-32\lib\site-packages\flet\core\page.py", line 32, in <module>
    from flet.core.adaptive_control import AdaptiveControl
  File "C:\env\Python310-32\lib\site-packages\flet\core\adaptive_control.py", line 3, in <module>
    from flet.core.control import Control
  File "C:\env\Python310-32\lib\site-packages\flet\core\control.py", line 18, in <module>
    from flet.core.badge import Badge, BadgeValue
  File "C:\env\Python310-32\lib\site-packages\flet\core\badge.py", line 5, in <module>
    from flet.core.text_style import TextStyle
  File "C:\env\Python310-32\lib\site-packages\flet\core\text_style.py", line 5, in <module>
    from flet.core.box import BoxShadow
  File "C:\env\Python310-32\lib\site-packages\flet\core\box.py", line 6, in <module>
    from flet.core.border import Border
  File "C:\env\Python310-32\lib\site-packages\flet\core\border.py", line 5, in <module>
    from flet.core.types import ColorValue, OptionalNumber
  File "C:\env\Python310-32\lib\site-packages\flet\core\types.py", line 28, in <module>
    from flet.core.icons import Icons, icons
  **File "C:\env\Python310-32\lib\site-packages\flet\core\icons.py", line 29, in <module>
    class icons(str, Enum, metaclass=IconsDeprecated):**
  File "C:\env\Python310-32\lib\enum.py", line 302, in __new__
    if canonical_member._value_ == enum_member._value_:
KeyboardInterrupt
^C
C:\Users\PRODAT>flet --version
Traceback (most recent call last):
  File "C:\env\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\env\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\env\Python310-32\Scripts\flet.exe\__main__.py", line 4, in <module>
  File "C:\env\Python310-32\lib\site-packages\flet\__init__.py", line 1, in <module>
    from flet.app import app, app_async
  File "C:\env\Python310-32\lib\site-packages\flet\app.py", line 12, in <module>
    from flet.core.page import Page
  File "C:\env\Python310-32\lib\site-packages\flet\core\page.py", line 32, in <module>
    from flet.core.adaptive_control import AdaptiveControl
  File "C:\env\Python310-32\lib\site-packages\flet\core\adaptive_control.py", line 3, in <module>
    from flet.core.control import Control
  File "C:\env\Python310-32\lib\site-packages\flet\core\control.py", line 18, in <module>
    from flet.core.badge import Badge, BadgeValue
  File "C:\env\Python310-32\lib\site-packages\flet\core\badge.py", line 5, in <module>
    from flet.core.text_style import TextStyle
  File "C:\env\Python310-32\lib\site-packages\flet\core\text_style.py", line 5, in <module>
    from flet.core.box import BoxShadow
  File "C:\env\Python310-32\lib\site-packages\flet\core\box.py", line 6, in <module>
    from flet.core.border import Border
  File "C:\env\Python310-32\lib\site-packages\flet\core\border.py", line 5, in <module>
    from flet.core.types import ColorValue, OptionalNumber
  File "C:\env\Python310-32\lib\site-packages\flet\core\types.py", line 28, in <module>
    from flet.core.icons import Icons, icons
  **File "C:\env\Python310-32\lib\site-packages\flet\core\icons.py", line 29, in <module>
    class icons(str, Enum, metaclass=IconsDeprecated):**
  File "C:\env\Python310-32\lib\enum.py", line 302, in __new__
    if canonical_member._value_ == enum_member._value_:
KeyboardInterrupt
^C

**Comment by FeodorFitsner** [comment]
App startup on Windows has been improved.
