### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: /sdcard

### ISSUE THREAD

**Issue by tsiens** [flet-dev/flet#3767]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I have made modifications AndroidManifest.xml，build apk，and grant all permissions through 'adb install -g .apk'，
in python
```
import os
print(os.listdir('/sdcard'))
with open('/sdcard/error.log','r') as f:
    print(f.read())
```
error:
```
['Android', 'RxLogger', 'Music', 'Podcasts', 'Ringtones', 'Alarms', 'Notifications', 'Pictures', 'Movies', 'Download', 'DCIM', 'Documents', 'Audiobooks', 'smu', 'Stats', 'tda', 'stagenow']
Traceback (most recent call last):
  File "<string>", line 43, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/serious_python_tempCSDNCB/main.py", line 3, in <module>
  File "/tmp/serious_python_tempCSDNCB/page/setting.py", line 4, in <module>
  File "/tmp/serious_python_tempCSDNCB/page/base.py", line 9, in <module>
PermissionError: [Errno 13] Permission denied: '/sdcard/error.log'
```
Can see all folders, but does not display files

### Code sample

flet-build-template\{{cookiecutter.out_dir}}\android\app\src\main\AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN"/>
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION "/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <application
        android:label="{{ cookiecutter.product_name }}"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <meta-data
                android:name="io.flutter.embedding.android.EnableImpeller"
                android:value="false"/>
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme"
            />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="android.intent.category.HOME"/>
                <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

### To reproduce

-

### Operating System

Linux

### Operating system details

android 11

### Flet version

0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Related to https://github.com/flet-dev/flet/issues/2357

**Comment by tsiens** [comment]
> Related to #2357
So how do we solve this problem? Can't I read data from the /sdcard now

**Comment by baseplate-admin** [comment]
>  So how do we solve this problem? Can't I read data from the /sdcard now

Please wait till they figure out what to do

**Comment by ndonkoHenri** [comment]
Closing this issue as duplicate.
Feel free to go mention complementary information in the issue I linked.
