### ISSUE TITLE
Client storage requests do not work on web (static)

### ISSUE THREAD

**Issue by mfxbe** [flet-dev/flet#3783]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Attempting to access any of the client storage requests on web clients results in a _TimeoutError_ (see log). I do not think this is the real problem, but I have not been able to find out more details. The example below tries to access it in the main method, but the problem occurs when used anywhere else.     
It's not browser specific, it happens in Firefox/Chrome on Debian as well as in Safari on iOS ( also when used as a PWA).

The same code works fine when using `flet run` or even when using `flet run --web`. The Linux builds also just work, the others I have not tried yet. (**Edit**: Android build works flawless as well)

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

def main(page: ft.Page):
        text = ft.Text("Test")
        page.add(text)

        res = page.client_storage.contains_key("key")
        if res == False:
                text.value = "Key not found"
                page.update()

ft.app(main)
```

</details>

### To reproduce

1. Build code sample with `flet build web` or `flet publish`
2. Run the result on a local or external server
3. Access the URL in a browser

### Expected behavior

No error in log and the displayed text should become "Key not found".

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Linux

### Operating system details

Debian sid

### Flet version

0.23.2

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

**From browser console:**

```console
Loading from existing service worker. [flutter.js:3:660](http://localhost:8000/flutter.js)
Service worker already active. [flutter.js:3:908](http://localhost:8000/flutter.js)
Injecting <script> tag. Using callback. [flutter.js:1:1458](http://localhost:8000/flutter.js)
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://localhost:8000/flutter.js
Source-Map-Adresse: flutter.js.map

WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. 2 [canvaskit.js:14:383](https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.js)
TypeError: flet_js.send is not a function
[python-worker.js:39:17](http://localhost:8000/python-worker.js)
TypeError: flet_js.send is not a function
[python-worker.js:39:17](http://localhost:8000/python-worker.js)
Python engine initialized! [python.js:23:13](http://localhost:8000/python.js)
Unhandled error processing page session : Traceback (most recent call last): [pyodide.asm.js:9:98748](https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.js)
  File "/tmp/serious_python_tempELXFMW/__pypackages__/flet/flet.py", line 71, in on_session_created [pyodide.asm.js:9:98748](https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.js)
  File "/tmp/serious_python_tempELXFMW/main.py", line 7, in main [pyodide.asm.js:9:98748](https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.js)
  File "/tmp/serious_python_tempELXFMW/__pypackages__/flet_core/client_storage.py", line 46, in contains_key [pyodide.asm.js:9:98748](https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.js)
  File "/tmp/serious_python_tempELXFMW/__pypackages__/flet_core/page.py", line 1342, in _invoke_method [pyodide.asm.js:9:98748](https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.js)
TimeoutError: Timeout waiting for invokeMethod clientStorage:containskey({'key': 'key'}) call [pyodide.asm.js:9:98748](https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.js)
<empty string>
```

</details>

### Additional details

**Edit:** There are the similar issues #2948 and #3613 but they seem to happen in different circumstances (i.e. not only failing on web).

**Comment by mfxbe** [comment]
Unfortunately, I still have the problem (flet 0.24.1)  , but I would like to add an additional discovery:

When using `page.client_storage.set("key", "value")` the key does actually get set in local storage (can be found out with the browser devs tools) but the function call nevertheless fails with a "Timeout Error". Also there are no changes when trying `get` or `contains_key` after _"successfully"_ (well or howerever I should call it) setting the key, still a "TimeoutError" and no value returned.

**Comment by mfxbe** [comment]
For everyone else having the problem as well I'll take the liberty of quoting a workaround from Discord (thanks to @k3nz0):

> I have the same issue using client_storage methods like described here https://github.com/flet-dev/flet/issues/3783 ? Can you help me with that? When i call set i see my data is stored into local storage but my code throws timeout error. The only way i made it work calling lower level protected methods 
> 
> token = await page._invoke_method_async(  # noqa: WPS437
            method_name="clientStorage:get",
            arguments={"key": "mock.access_token"},
            wait_timeout=10,
            wait_for_result=True,
        )
> 
> 
> or 
> 
> await self.page._invoke_method_async(  # noqa: WPS437
                    "clientStorage:set",
                    {"key": "mock.access_token", "value": self.user_client.auth_token},
                    wait_timeout=10,
                )

([Discord link](https://discord.com/channels/981374556059086931/1000264673284857866/1277532745081552918))

It's not a perfect solution, but it works for now.

**Comment by nilton-medeiros** [comment]
I encountered the same issue, so I followed your solution:
```
# I replaced the following:

page.client_storage.set(f"{PREFIX}user-settings", user_settings) 

# With your command:

await page._invoke_method_async(  # noqa: WPS437
    "clientStorage:set",
    {"key": f"{PREFIX}user-settings", "value": user_settings},
    wait_timeout=10,
)
```
When calling the function, I handled the exception, which solved the error. However, I noticed that nothing is saved in the browser's local storage. Back to square one.

**Comment by nilton-medeiros** [comment]
Over time, I realized that a simple example works because it operates synchronously, without being inside an asynchronous function. However, when used in asynchronous functions, a timeout occurs because access to client_storage in web and mobile environments depends on IndexedDB, which sometimes exceeds the standard 1-second limit. Therefore, we should not call this method within an asynchronous function, as there is an incompatibility.

**Comment by mfxbe** [comment]
When I encountered the problem the first time I experimented quit a bit around and if I remember correctly I also tried to set time limits up to quit large values and it did not fix anything for me. It just took longer for the error to appear. But I'm not completely sure anymore what I tried and what not.

I'm not sure why the workaround is not working for you, I'm actively using the `page._invoke_method_async` and the values are getting stored by the browser.

**Comment by FeodorFitsner** [comment]
To work in web browser environment (Pyodide) you should use `_async` methods. See here: https://github.com/flet-dev/flet/issues/5264#issuecomment-2856846040

The code that works on all platforms:

```py
import flet as ft

async def main(page: ft.Page):
        text = ft.Text("Test")
        page.add(text)

        res = await page.client_storage.contains_key_async("key")
        if res == False:
                text.value = "Key not found"
                page.update()

ft.app(main)
```
