### ISSUE TITLE
flet buil macos succeed but show error when open the app

### ISSUE THREAD

**Issue by datle021194** [flet-dev/flet#3859]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I'm building a Flet MacOS app. `flet run` command is ok, my app work as expected.
I tried to build the app with `flet build macos` command, it succeed but when I opened the app then the app show this error:

> Traceback (most recent call last):
  File "<string>", line 43, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/var/folders/f3/k07jx8zd2832zhxxr2pbm5_00000gn/T/serious_python_tempwF5CIT/main.py", line 2, in <module>
  File "/var/folders/f3/k07jx8zd2832zhxxr2pbm5_00000gn/T/serious_python_tempwF5CIT/source/presentation/scenes/scene_coordinator.py", line 5, in <module>
  File "/var/folders/f3/k07jx8zd2832zhxxr2pbm5_00000gn/T/serious_python_tempwF5CIT/source/presentation/scenes/home/ui.py", line 4, in <module>
  File "/var/folders/f3/k07jx8zd2832zhxxr2pbm5_00000gn/T/serious_python_tempwF5CIT/source/presentation/scenes/home/controller.py", line 2, in <module>
  File "/var/folders/f3/k07jx8zd2832zhxxr2pbm5_00000gn/T/serious_python_tempwF5CIT/source/libraries/image_manager/__init__.py", line 1, in <module>
  File "/var/folders/f3/k07jx8zd2832zhxxr2pbm5_00000gn/T/serious_python_tempwF5CIT/__pypackages__/rembg/__init__.py", line 5, in <module>
  File "/var/folders/f3/k07jx8zd2832zhxxr2pbm5_00000gn/T/serious_python_tempwF5CIT/__pypackages__/rembg/bg.py", line 7, in <module>
  File "/var/folders/f3/k07jx8zd2832zhxxr2pbm5_00000gn/T/serious_python_tempwF5CIT/__pypackages__/cv2/__init__.py", line 181, in <module>
  File "/var/folders/f3/k07jx8zd2832zhxxr2pbm5_00000gn/T/serious_python_tempwF5CIT/__pypackages__/cv2/__init__.py", line 111, in bootstrap
  File "/var/folders/f3/k07jx8zd2832zhxxr2pbm5_00000gn/T/serious_python_tempwF5CIT/__pypackages__/cv2/__init__.py", line 109, in load_first_config
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.

requirements.txt:
> flet
> flet-core
> flet-runtime
> pillow
> posthog
> rembg

I checked this same issue in the issues list but it's on window and my build folder didn't have an app.zip file.
I also tried to remove the .venv and created a new one to reinstall all dependencies but still error.

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

Sonoma 14.4

### Flet version

0.23.2

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by datle021194** [comment]
Please give me any help

**Comment by OwenMcDonnell** [comment]
Can you try this again on the latest Flet pre-release?
