### ISSUE TITLE
Open a new View error (in new version 0.24)

### ISSUE THREAD

**Issue by nastiliano** [flet-dev/flet#3916]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Hello.

I have an app working completly fine in Flet version 0.23.2, but when I updated to new 0.24 Flet version I can't open Views (if the code View is inside a Subclass. If it's inside a Class all is ok, but if my View is inside a Subclass appears an error).

### Code sample

<details open><summary>Code</summary>

```python
Future exception was never retrieved
future: <Future finished exception=AssertionError('at minimum, text, icon or a visible content must be provided')>
Traceback (most recent call last):
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/flet_core/page.py", line 944, in wrapper
    handler(*args)
  File "/home/user/pagina_principal.py", line 246, in <lambda>
    on_click = lambda e: self.esdeveniments(e) ,
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/pagina_principal.py", line 373, in esdeveniments
    self.GUI.gestio_instal_actual(self.GUI.obri_vista , _("Obri instal·lació") , "/obri_instal" , self.vista_Obri_Client , False)
  File "/home/user/interficie.py", line 654, in gestio_instal_actual
    aplicar_accio()
  File "/home/user/interficie.py", line 627, in aplicar_accio
    accio(args[0] , args[1] , args[2])
  File "/home/user/interficie.py", line 377, in obri_vista
    self.pagina_principal.page.update()
  File "/home/user/.local/lib/python3.12/site-packages/flet_core/page.py", line 719, in update
    r = self.__update(self)
        ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/flet_core/page.py", line 833, in __update
    commands, added_controls, removed_controls = self.__prepare_update(*controls)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/flet_core/page.py", line 849, in __prepare_update
    control.build_update_commands(
  File "/home/user/.local/lib/python3.12/site-packages/flet_core/control.py", line 480, in build_update_commands
    innerCmds = ctrl._build_add_commands(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/flet_core/control.py", line 545, in _build_add_commands
    childCmd = control._build_add_commands(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/flet_core/control.py", line 545, in _build_add_commands
    childCmd = control._build_add_commands(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/.local/lib/python3.12/site-packages/flet_core/control.py", line 545, in _build_add_commands
    childCmd = control._build_add_commands(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 5 more times]
  File "/home/users/.local/lib/python3.12/site-packages/flet_core/control.py", line 534, in _build_add_commands
    command = self._build_command(False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/flet_core/control.py", line 561, in _build_command
    self.before_update()
  File "/home/user/.local/lib/python3.12/site-packages/flet_core/elevated_button.py", line 158, in before_update
    self.text or self.icon or (self.__content and self.__content.visible)
AssertionError: at minimum, text, icon or a visible content must be provided
```

</details>

### To reproduce

Run

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

All O.S (Windows , MacOS and Linux)

### Flet version

0.24

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Will you please share some runnable code example?

**Comment by nastiliano** [comment]
Hello,

I've simplified a lot my code.
And I put the view in a class, not in a subclass, but the error is the same

Thank you, best regards.
[issue.zip](https://github.com/user-attachments/files/16839901/issue.zip)

**Comment by ndonkoHenri** [comment]
Error happens because some `FilledTonalButton` have an empty string (`""`) as `text`. To resolve this you can do one of the following in those buttons:
- set the `content` to a `Text` control containing the empty string: `content=ft.Text()`
- add at least one space in the string: `text=" "`
