### ISSUE TITLE
nuitka - another packager to consider

### ISSUE THREAD

**Issue by hololeo** [flet-dev/flet#392]
https://nuitka.net/

This may be another packager for flet. I will test it against multiple projects and report problems and success

**Comment by FHU-yezi** [comment]
Juist tested on Windows 10 with Poetry for venv and package manager. Still cant't work, maybe some file is not property be packaged.

**Comment by ningzichun** [comment]
Tested on MacOS and Linux, it works now, and I think it is much faster on MacOS than `flet pack` cause it is on onedir mode.

python3 -m nuitka --standalone --macos-create-app-bundle --macos-app-icon=scripts/icon.png --assume-yes-for-downloads  --macos-app-mode="ui-element"  main.py
python3 -m nuitka --standalone  --linux-icon=scripts/icon.png --assume-yes-for-downloads --onefile main.py

While on Windows, it still could not work, and I am trying tweaking the parameters.
```
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\main.py", line 29, in <module>
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\flet\flet.py", line 85, in app
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\flet\flet.py", line 152, in __app_sync
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\flet\flet.py", line 510, in open_flet_view
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\flet\flet.py", line 566, in __locate_and_unpack_flet_view
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\flet\flet.py", line 678, in __download_flet_client
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\urllib\request.py", line 241, in urlretrieve
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\urllib\request.py", line 216, in urlopen
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\urllib\request.py", line 519, in open
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\urllib\request.py", line 536, in _open
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\urllib\request.py", line 496, in _call_chain
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\urllib\request.py", line 1391, in https_open
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\urllib\request.py", line 1352, in do_open
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\http\client.py", line 1375, in getresponse
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\http\client.py", line 318, in begin
  File "C:\Users\ADMINI~1\Desktop\helloft\MAIN~1.DIS\http\client.py", line 287, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by ndonkoHenri** [comment]
Great, @ningzichun.
Please could you come up with a little guide on this when you are done?
I will trying it on Windows.

**Comment by ningzichun** [comment]
> Great, @ningzichun. Please could you come up with a little guide on this when you are done?

Yeah, I am surprised that Nuitka works now, while I tried it 3 months ago. 

Now the only barrier is that for the fletd isn't correctly detected and packed by Nuitka, so for someone who don't have Internet connection or fail to download fletd cannot use the packed app.
