### ISSUE TITLE
The error message when packaged as apk does not specify the specific error

### ISSUE THREAD

**Issue by huqunfeng** [flet-dev/flet#3987]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

The program packaging error resulted in the file handle not being released, making it impossible to delete the temporary file. Even if you skip deleting temporary files, you cannot complete the packaging

### Code sample

<details open><summary>Code</summary>

```python
[import flet as ft
from globalvar import env
import UserLogin
from orderfile import orderpage
from pilefile import pilepage
from settlefile import settlepage
from userfile import userpage
from esfile import espage
from redisfile import redispage
import requests
from globalvar import ipaddress

def main(page: ft.Page):
    global token
    page.title = f"万马爱充查询工具({env})"
    page.fonts = {
        "globalfont": "fonts/msyh.ttc",
    }
    page.theme = ft.Theme(font_family="globalfont")

    page.appbar = ft.AppBar(
        leading=ft.Row(controls=[ft.Container(width=5),ft.Image(src='./icons/wanmalogo2.png',width=40,height=12.4)]),
        toolbar_height=30,
        title=ft.Text(f"万马爱充自助查询工具({env})",size=13),
        center_title=True,
        bgcolor= '#F7AB00',

    )
    page1 = orderpage.OrderPage()
    page2 = pilepage.PilePage()
    page3 = userpage.UserPage()
    page4 = settlepage.SettlePage()
    page5 = espage.EsPage()
    page6 = redispage.RedisPage()
    pagelist = [page1, page2, page3, page4, page5,page6]

    if page.client_storage.contains_key("token"):
        token = page.client_storage.get("token")
        headers = \
            {
                "Content-Type": "application/json;charset=UTF-8"
            }
        checktokenurl = f"http://{ipaddress}/check_token?token={token}"
        result = requests.post(checktokenurl, headers=headers)
        if result.status_code == 401:
            page.route = '/'
        else:
            page.route = "/root"
    else:
        page.route = '/'

    def route_change(route):
        page.views.clear()
        if page.route == "/root":
            def PageUpdate(num):
                datepage.controls = [pagelist[num]]
                page.update()

            datepage = ft.View(
                    route = "/root",
                    appbar=page.appbar,
                    scroll=ft.ScrollMode.ADAPTIVE,
                    adaptive=True,
                    controls = [page1],
                    navigation_bar = ft.NavigationBar(
                        bgcolor='#F7AB00',
                        indicator_color=ft.colors.WHITE,
                        on_change=lambda e: PageUpdate(e.control.selected_index),
                        destinations=[
                            ft.NavigationBarDestination(icon=ft .icons.QUERY_STATS, label="订单查询"),
                            ft.NavigationBarDestination(icon=ft.icons.EV_STATION, label="电桩查询"),
                            ft.NavigationBarDestination(icon=ft.icons.PEOPLE, label="用户查询"),
                            ft.NavigationBarDestination(icon=ft.icons.PAYMENT, label="人工结算"),
                            ft.NavigationBarDestination(icon=ft.icons.DATA_OBJECT, label="ES查询"),
                            ft.NavigationBarDestination(icon=ft.icons.DATA_USAGE, label="Redis查询")
                        ],
                        selected_index=0,
                    )
                )
            page.views.append(
                datepage
            )
        if page.route == "/":
            page.views.append(
                ft.View(
                    "/",
                    [
                        UserLogin.Login()
                    ],
                    appbar=page.appbar,
                    auto_scroll=True
                )
            )
        page.update()

    def view_pop(view):
        page.views.pop()
        top_view = page.views[-1]
        page.go(top_view.route)

    page.on_route_change = route_change
    page.on_view_pop = view_pop
    page.go(page.route)


ft.app(target=main)]
```

</details>

### To reproduce

It is normal to package the program into exe or run it on a webpage

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

windows 11

### Flet version

0.23.2

### Regression

No, it isn't

### Suggestions

Need to know the specific reasons and number of lines for packaging errors in order to make modifications

### Logs

<details open><summary>Logs</summary>

```console
[Error log：
Compiling Python sources at C:\Users\HUQUNF~1\AppData\Local\Temp\serious_python_tempac91ccf2
VERBOSE: C:\Users\HUQUNF~1\AppData\Local\Temp\hostpython3.11_8e064605\python\python.exe -m compileall -b C:\Users\HUQUNF~1\AppData\Local\Temp\serious_python_tempac91ccf2
Error: FormatException: Unexpected extension byte (at offset 485)
Deleting temp directory C:\Users\HUQUNF~1\AppData\Local\Temp\serious_python_tempac91ccf2
Deleting sitecustomize directory C:\Users\HUQUNF~1\AppData\Local\Temp\serious_python_sitecustomizeaf49e289
Deleting Python directory C:\Users\HUQUNF~1\AppData\Local\Temp\hostpython3.11_8e064605
Unhandled exception:
PathAccessException: Deletion failed, path = 'C:\Users\HUQUNF~1\AppData\Local\Temp\hostpython3.11_8e064605' (OS Error: 拒绝访问。
, errno = 5)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:180:7)
<asynchronous suspension>
#2      PackageCommand.run (file:///C:/Users/huqunfeng/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/serious_python-0.7.1/bin/package_command.dart:363:9)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#4      main (file:///C:/Users/huqunfeng/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/serious_python-0.7.1/bin/main.dart:10:3)
<asynchronous suspension>
[09:44:25] Deleting Flutter bootstrap directory                                 
           C:\Users\HUQUNF~1\AppData\Local\Temp\flet_flutter_build_HEtH8XBHRA
           Error building Flet app - see the log of failed command above. ]
```

</details>

**Comment by huqunfeng** [comment]
Currently resolved
