### ISSUE TITLE
windows build error 

### ISSUE THREAD

**Issue by Ambassador-of-programming** [flet-dev/flet#4071]
### Duplicate Check

- [x] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Traceback (most recent call last):
  File "<string>", line 43, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\pro\AppData\Local\Temp\serious_python_temp78927f7e\main.py", line 3, in <module>
  File "C:\Users\pro\AppData\Local\Temp\serious_python_temp78927f7e\navigation\FletRouter.py", line 3, in <module>
  File "C:\Users\pro\AppData\Local\Temp\serious_python_temp78927f7e\pages\main.py", line 1, in <module>
  File "C:\Users\pro\AppData\Local\Temp\serious_python_temp78927f7e\parsing\cian.py", line 4, in <module>
ModuleNotFoundError: No module named 'bs4'

`flet build windows -vv `                      

I can't understand why I can't see my own builds for windows, namely beautifulsoup4                                                                                           

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

flet build windows -vv                                                                                                                  

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

11

### Flet version

flet 0.24.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Can you share your requirements file?

**Comment by Ambassador-of-programming** [comment]
> Can you share your requirements file?

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
undetected-chromedriver = "*"
beautifulsoup4 = "*"
flet = "*"
nuitka = "*"
imageio = "*"

[dev-packages]

[requires]
python_version = "3.11"
python_full_version = "3.11.4"
