### ISSUE TITLE
Errors appearing when running flet on Android when the flet code contains some libraries even though they are binary on https://pypi.org/ like pyzbar:

### ISSUE THREAD

**Issue by YasseenAlhusammi** [flet-dev/flet#4159]
### Discussed in https://github.com/flet-dev/flet/discussions/4158

<div type='discussions-op-text'>

<sup>Originally posted by **YasseenAlhusammi** October 14, 2024</sup>
Please add pyzbar:
The following reasons:
When converting a Fleet project using to apk using:
Version: flet==0.25.0.dev3519
and python==3.12.6:
and windows 10:
The following error appears on Android when running the application on Android despite adding pyzbar to requirements.txt, and despite the fact that
pyzbar-0.1.9-py2.py3-none-win_amd64.whl has a binary file at https://pypi.org/:
The error that appears when running the application on Android is as follows:
Traceback (most recent call last):
File "<string>", line 43, in <module>
File "<frozen runpy>", line 229, in run_module
File "<frozen runpy>", line 88, in _run_code
File "/data/user/0/com.flet.myapp/files/flet/app/main.py", line 4, in <module> from pyzbar import pyzbar File "/data/user/0/com.flet.myapp/files/flet/python_site_packages/pyzbar/pyzbar.py", line 7, in <module> from .wrapper import ( File "/data/user/0/com.flet.my app/files/flet/python_site_packages/pyzbar/wrapper.py", line 151, in <module> zbar_version = zbar_function( ^^^^^^^^^^^^^^ File "/data/user/0/com.flet.myapp/files/flet/python_site_packages/pyzbar/wrapper.py", line 148, in zbar_function return prototype((fname, load_libzbar())) ^^^^^^^^^^^^^ File "/data/user/0/com.flet.myapp/files/flet/python_site_packages/pyzbar/wrapper.py", line 127, in load_libzbar libzbar, dependencies = zbar_library.load() ^^^^^^^^^ File "/data/user/0/com.flet.myapp/files/flet/python_site_packages/pyzbar/zbar_library.py", line 65, in load raise ImportError('Unable to find zbar shared library') ImportError: Unable to find zbar shared library</div>

**Comment by FeodorFitsner** [comment]
`pyzbar` module depends on `zbar` library written in C. Maybe zbar lib could be compiled for Android, but then probably pyzbar package itself should be modified to be able to load zbar at runtime.
I'm moving that to discussions.
