### ISSUE TITLE
Could not connected to Flet server in 30 seconds.

### ISSUE THREAD

**Issue by YutaRedux** [flet-dev/flet#424]
**Description**

Traceback (most recent call last):
  File "C:\...\flet_test.py", line 25, in <module>
    flet.app(target=main, port=8550, view=flet.WEB_BROWSER)
  File "C:\...\AppData\Local\Programs\Python\Python310\lib\site-packages\flet\flet.py", line 94, in app
    conn = _connect_internal(
  File "C:\...\AppData\Local\Programs\Python\Python310\lib\site-packages\flet\flet.py", line 256, in _connect_internal      
    raise Exception(
Exception: Could not connected to Flet server in 30 seconds.

**Code example to reproduce the issue:**

```python
import flet

def main(page: flet.Page):
    page.add(flet.Text("Hello, world!"))

flet.app(target=main)
```

**Describe the results you received:**

Traceback (most recent call last):
  File "C:\...\flet_test.py", line 25, in <module>
    flet.app(target=main, port=8550, view=flet.WEB_BROWSER)
  File "C:\...\AppData\Local\Programs\Python\Python310\lib\site-packages\flet\flet.py", line 94, in app
    conn = _connect_internal(
  File "C:\...\AppData\Local\Programs\Python\Python310\lib\site-packages\flet\flet.py", line 256, in _connect_internal      
    raise Exception(
Exception: Could not connected to Flet server in 30 seconds.

**Describe the results you expected:**

a working app :|

**Additional information you deem important (e.g. issue happens only occasionally):**
issue happens only on flet 0.1.60, it worked fine on 0.1.58

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.1.60
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author:
Author-email: Appveyor Systems Inc. <hello@flet.dev>
License: MIT
Location: c:\users\kelpm\appdata\local\programs\python\python310\lib\site-packages
Requires: beartype, cryptography, oauthlib, repath, requests, watchdog, websocket-client
Required-by:
```

**Operating system**:

windows 10 21H2

**Additional environment details:**
python 3.10

**Comment by YutaRedux** [comment]
i added
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

here's the output:

```INFO:root:Starting local Flet Server on port 50418...
INFO:root:Attached process: True
INFO:root:Flet Server found in: C:\...\AppData\Local\Programs\Python\Python310\lib\site-packages\flet\bin\fletd.exe
INFO:root:Web renderer configured: canvaskit
INFO:root:Route URL strategy configured: hash
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
panic: error reading config file: While parsing config: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into map[string]interface {}

goroutine 1 [running]:
github.com/flet-dev/flet/server/config.init.0()
        /home/appveyor/projects/flet/server/config/config.go:96 +0x733
DEBUG:root:Exited run_forever()
INFO:root:Failed to connect: ws://127.0.0.1:50418/ws
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:50418/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds```

**Comment by FeodorFitsner** [comment]
Do you have `%USERPROFILE%\.flet\config.yml`?

**Comment by YutaRedux** [comment]
> Do you have `%USERPROFILE%\.flet\config.yml`?

I created this file and now everything works, but it's probably a bug and should be fixed, should it?

**Comment by FeodorFitsner** [comment]
Well, it should work without that file. Does it work if your delete that file and .flet folder?

**Comment by YutaRedux** [comment]
> Well, it should work without that file. Does it work if your delete that file and .flet folder?

No, it doesn't

**Comment by FeodorFitsner** [comment]
OK, will take a look.

**Comment by FeodorFitsner** [comment]
I cannot reproduce it with 0.1.60 and the most recent 0.1.61 versions of Flet.
There is another place where Flet config is being searched: `%ProgramData%\flet\config.yml`.
