### ISSUE TITLE
Error running APK file after build - module not found

### ISSUE THREAD

**Issue by NHLOCAL** [flet-dev/flet#4570]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

After building an APK, the application opens and shows a "module not found" error, even though the library was included in the requirements file and no error was shown during the build

### Code sample

<details open><summary>Code</summary>

```console
Traceback (most recent call last):
  File "<string>", line 47, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/[data/user/0/nhlocal.shamorzachor/files/flet/app/main.py](http://data/user/0/nhlocal.shamorzachor/files/flet/app/main.py)", line 6, in <module>
    from data_loader import load_data, get_total_pages, get_completion_date_string
  File "/[data/user/0/nhlocal.shamorzachor/files/flet/app/data_loader.py](http://data/user/0/nhlocal.shamorzachor/files/flet/app/data_loader.py)", line 5, in <module>
    from pyluach import dates
ModuleNotFoundError: No module named 'pyluach'
```

</details>

### To reproduce

1. I built the application with flet build
2. Construction completed successfully
3. When I ran the apk on the android device, the above error was displayed

### Expected behavior

Proper operation of the application

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

windows 11

### Flet version

0.25.1

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[22:19:43] No additional Flutter dependencies!
[22:19:47] Created Flutter bootstrap project from gh:flet-dev/flet-build-template with ref 0.25.1 ✅
           Customized app icons and splash images ✅
           Run subprocess:
           ['C:\\Users\\Public\\flutter_windows_3.19.6-stable\\flutter\\bin\\dart.BAT', 'run',
           'flutter_launcher_icons']
(●     ) Generating app icons ⏳...
Built flutter_launcher_icons:flutter_launcher_icons.
(     ●) Generating app icons ⏳...   ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.14.1)
  ════════════════════════════════════════════

(    ● ) Generating app icons ⏳... • Creating default icons Android
( ●    ) Generating app icons ⏳... • Overwriting the default Android launcher icon with a new icon
( ●    ) Generating app icons ⏳... • Creating adaptive icons Android
(    ● ) Generating app icons ⏳... • Updating colors.xml with color for adaptive icon background
• Creating mipmap xml file Android
( ●    ) Generating app icons ⏳... • Overwriting default iOS launcher icon with new icon
(●     ) Generating app icons ⏳... Creating Icons for Web...
(     ●) Generating app icons ⏳... Creating Icons for Windows...
(  ●   ) Generating app icons ⏳... Creating Icons for MacOS...
(  ●   ) Generating app icons ⏳...
✓ Successfully generated launcher icons
[22:19:52] Generated app icons ✅
           Run subprocess:
           ['C:\\Users\\Public\\flutter_windows_3.19.6-stable\\flutter\\bin\\dart.BAT', 'run',
           'flutter_native_splash:create']
( ●    ) Generating splash screens ⏳...
Built flutter_native_splash:create.
(     ●) Generating splash screens ⏳... [Android] Creating default splash images
(   ●  ) Generating splash screens ⏳... [Android] Creating dark mode splash images
( ●    ) Generating splash screens ⏳... [Android] Creating default android12splash images
(    ● ) Generating splash screens ⏳... [Android] Creating dark mode android12splash images
(  ●   ) Generating splash screens ⏳... [Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
( ●    ) Generating splash screens ⏳... [Android]  - android/app/src/main/res/drawable-night/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
(  ●   ) Generating splash screens ⏳... [iOS] Creating  images
(   ●  ) Generating splash screens ⏳... [iOS] Creating dark mode  images
(   ●  ) Generating splash screens ⏳... [iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
(  ●   ) Generating splash screens ⏳... [Web] Creating images
(     ●) Generating splash screens ⏳... [Web] Creating images
( ●    ) Generating splash screens ⏳... [Web] Creating background images
[Web] Creating CSS
(  ●   ) Generating splash screens ⏳... [Web] Updating index.html

✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash

[22:19:57] Generated splash screens ✅
           Run subprocess:
           ['C:\\Users\\Public\\flutter_windows_3.19.6-stable\\flutter\\bin\\dart.BAT', 'run',
           'serious_python:main', 'package', 'C:\\Users\\me\\first-flet-app\\shamor-zachor',
           '--platform', 'Android', '--requirements',
           '-r,C:\\Users\\me\\first-flet-app\\shamor-zachor\\requirements.txt', '--exclude', 'build',
           '--cleanup']
(    ● ) Packaging Python app ⏳...
Built serious_python:main.
(●     ) Packaging Python app ⏳...
Extra PyPi indexes: [https://pypi.flet.dev]
Created temp directory: C:\Users\me\AppData\Local\Temp\serious_python_tempfa0d4973
Copying Python app from C:\Users\me\first-flet-app\shamor-zachor to a temp directory
Cleanup app
Configured Android/arm64-v8a platform with sitecustomize.py
(    ● ) Packaging Python app ⏳... Installing [-r, C:\Users\me\first-flet-app\shamor-zachor\requirements.txt] with pip command to C:\Users\me\first-flet-app\shamor-zachor\build\site-packages\arm64-v8a
(   ●  ) Packaging Python app ⏳... Cleanup installed packages
(   ●  ) Packaging Python app ⏳... Configured Android/armeabi-v7a platform with sitecustomize.py
Installing [-r, C:\Users\me\first-flet-app\shamor-zachor\requirements.txt] with pip command to C:\Users\me\first-flet-app\shamor-zachor\build\site-packages\armeabi-v7a
(●     ) Packaging Python app ⏳... Cleanup installed packages
(    ● ) Packaging Python app ⏳... Configured Android/x86_64 platform with sitecustomize.py
Installing [-r, C:\Users\me\first-flet-app\shamor-zachor\requirements.txt] with pip command to C:\Users\me\first-flet-app\shamor-zachor\build\site-packages\x86_64
( ●    ) Packaging Python app ⏳... Cleanup installed packages
(   ●  ) Packaging Python app ⏳... Configured Android/x86 platform with sitecustomize.py
Installing [-r, C:\Users\me\first-flet-app\shamor-zachor\requirements.txt] with pip command to C:\Users\me\first-flet-app\shamor-zachor\build\site-packages\x86
(  ●   ) Packaging Python app ⏳... Cleanup installed packages
(    ● ) Packaging Python app ⏳... Creating app archive at C:\Users\me\first-flet-app\shamor-zachor\build\flutter\app/app.zip from a temp directory
(    ● ) Packaging Python app ⏳... Writing app archive hash to C:\Users\me\first-flet-app\shamor-zachor\build\flutter\app/app.zip.hash
Deleting temp directory
[22:21:25] Packaged Python app ✅
           Run subprocess:
           ['C:\\Users\\Public\\flutter_windows_3.19.6-stable\\flutter\\bin\\flutter.BAT', 'build',
           'apk', '--build-number', '300', '--build-name', '0.3.0']
(    ● ) Building .apk for Android ⏳...
( ●    ) Building .apk for Android ⏳... Running Gradle task 'assembleRelease'...
Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 257628 to 209160 bytes (18.8% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1261080 bytes (23.3% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
(    ● ) Building .apk for Androi   33.9s
(  ●   ) Building .apk for Android ⏳... √ Built build\app\outputs\flutter-apk\app-release.apk (63.2MB)
[22:22:02] Built .apk for Android ✅
           Copying build output from:
           C:\Users\me\first-flet-app\shamor-zachor\build\flutter\build\app\outputs\flutter-apk\*
```

</details>

### Additional details

The application previously worked with flet 0.25.1 before I added the pyluach package to it

#### requirements.txt file:
```
python-hebrew-numbers
flet==0.25.1
pyluach==2.2.0
```

**Comment by FeodorFitsner** [comment]
See what's inside `.apk`. Unpack `.apk` (it's a zip). Then inside archive locate `lib/arm64-v8a/libpythonsitepackages.so` and unpack it.

**Comment by NHLOCAL** [comment]
I located the file. Its content is binary, how can it be disassembled?

**Comment by FeodorFitsner** [comment]
'pyluach' is there and I would assume should be importable.

**Comment by NHLOCAL** [comment]
what does that mean In practice the application crashes!

**Comment by NHLOCAL** [comment]
Could it be related to the improvement you made in the new version, that the build uses the existing build folder instead of building everything completely from scratch?

**Comment by FeodorFitsner** [comment]
I built an APK with `pyluach` included and it worked for me on simulator.

The program:

```py
import flet as ft
from pyluach import dates


def main(page: ft.Page):
    heb_date = dates.HebrewDate(5783, 3, 6)
    page.add(
        ft.SafeArea(
            ft.Text(str(heb_date.festival(israel=True, prefix_day=True))),
        )
    )


ft.app(main)
```

Result:

<img width="390" alt="image" src="https://github.com/user-attachments/assets/b9f0cfc6-f631-4d02-8635-ab6395105da8" />

**Comment by NHLOCAL** [comment]
I have now rebuilt the application with version 0.25.2 in an isolated environment inside github operations and it works fine
