### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by 3mora2** [flet-dev/flet#4596]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

the code work fine, but some time show error like
```python
asyncio:ERROR:Future exception was never retrieved
future: <Future finished exception=AssertionError()>
Traceback (most recent call last):
  File "concurrent\futures\thread.py", line 58, in run
  File "flet\core\page.py", line 948, in wrapper
  File "frontend\Components\TabAddProduct\images.py", line 277, in func_suggest_image
  File "flet\core\page.py", line 1429, in open
  File "flet\core\control.py", line 326, in update
  File "flet\core\page.py", line 723, in update
  File "flet\core\page.py", line 835, in __update
  File "flet\core\page.py", line 851, in __prepare_update
  File "flet\core\control.py", line 487, in build_update_commands
  File "flet_core\control.py", line 483, in build_update_commands
AssertionError
```

line 277, in func_suggest_image
```python
        self.page.open(
            DialogSearchImage(images_for_drop=self.images(),
                              on_dismiss=lambda x: self.show_image(),
                              update_images_session=self.update_images_session,
                              images=images,
                              title=title,
                              )
        )

```

in genral it's work fine, but when error show , more error will show

```python
asyncio:ERROR:Future exception was never retrieved
future: <Future finished exception=AssertionError()>
Traceback (most recent call last):
  File "concurrent\futures\thread.py", line 58, in run
  File "flet\core\page.py", line 948, in wrapper
  File "frontend\HomePageParts\appbar.py", line 25, in show_drawer
  File "flet\core\page.py", line 1429, in open
  File "flet\core\control.py", line 326, in update
  File "flet\core\page.py", line 723, in update
  File "flet\core\page.py", line 835, in __update
  File "flet\core\page.py", line 851, in __prepare_update
  File "flet\core\control.py", line 487, in build_update_commands
  File "flet_core\control.py", line 483, in build_update_commands
AssertionError

```

```python
ALister:INFO:Prepare To Close
ALister:ERROR:on_window_event
Traceback (most recent call last):
  File "frontend\HomePage.py", line 185, in on_window_event
  File "flet\core\page.py", line 482, in destroy
  File "flet\core\page.py", line 721, in update
  File "flet\core\page.py", line 835, in __update
  File "flet\core\page.py", line 851, in __prepare_update
  File "flet\core\control.py", line 487, in build_update_commands
  File "flet\core\control.py", line 487, in build_update_commands
  File "flet_core\control.py", line 483, in build_update_commands
AssertionError
```
line 185, in on_window_event
```python
        if e.data == "close":
            self.page.window.destroy()
```

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

error start with `page.open` `ft.AlertDialog`

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

win10

### Flet version

last version

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment]
Please share the assertion error-message. Also, will be great if you could come up with a reproducible code sample to test your issue. 

>   File "flet\core\control.py", line 487, in build_update_commands
  File "flet_core\control.py", line 483, in build_update_commands

Additionally, this is quite strange, as in the latest version 0.25.2, we only have `flet\core` and no more `flet_core`.
I will suggest you install Flet in a new virtual env using `pip install 'flet[all]'`
