### ISSUE TITLE
Calling `update()` inside `Control.did_mount()` causes deadlock

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#489]
Sample code causing deadlock:

```python
import flet
from flet import Container, Page, Text, UserControl

class MyControl(UserControl):
    def build(self):
        print("i am built")
        self.c = Container()
        self.c.bgcolor = "blue"
        self.c.content = Text("hello there")
        return self.c

    def did_mount(self):
        print("i am mounted")
        self.resize_me()

    def resize_me(self):
        self.c.bgcolor = "red"
        self.update()

def main(page: Page):
    t = MyControl()
    page.add(t)
    print("i am added")

flet.app(target=main)
```

Solution:

Go through a list of added controls after `update()` is finished and lock released and call `did_mount()` for each added control.

**Comment by ndonkoHenri** [comment]
Hey, will it now be possible to easily access `self.page` in the UserControl?

**Comment by ItsCubeTime** [comment]
Hi, the issue still seems present in `0.3.0.dev941` & 0.2.4 on Pypi.

```py

import flet

class userCtrl(flet.UserControl):
    def build(self):
        return [flet.Container(bgcolor=flet.colors.RED, width=self.page.width, height=100000)]

def main(page: flet.Page):
    page.add(
        userCtrl()
    )

flet.app(
    target=main, web_renderer="html", assets_dir=".", port=3768
    # , view=flet.WEB_BROWSER
)
```

```
PS C:\Users\olliv\Desktop\Art And Development\Flutter Learning\Flet\Calculator example> python -u "f:\Olliver\Art and development\Flutter Learning\Flet\Calculator example\selfPageBug.py"
Unhandled error processing page session 07cc183d-3ca2-4055-bcd2-0a70433d1b61: Traceback (most recent call last):
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python310\lib\site-packages\flet\flet.py", line 220, in on_session_created
    session_handler(page)
  File "f:\Olliver\Art and development\Flutter Learning\Flet\Calculator example\selfPageBug.py", line 8, in main
    page.add(
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python310\lib\site-packages\flet\page.py", line 256, in add
    added_controls = self.__update(self)
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python310\lib\site-packages\flet\page.py", line 231, in __update
    control.build_update_commands(self._index, added_controls, commands)
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python310\lib\site-packages\flet\control.py", line 353, in build_update_commands
    innerCmds = ctrl._build_add_commands(
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python310\lib\site-packages\flet\control.py", line 401, in _build_add_commands
    childCmd = control._build_add_commands(
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python310\lib\site-packages\flet\control.py", line 381, in _build_add_commands
    self._build()
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python310\lib\site-packages\flet\user_control.py", line 12, in _build
    content = self.build()
  File "f:\Olliver\Art and development\Flutter Learning\Flet\Calculator example\selfPageBug.py", line 5, in build
    return [flet.Container(bgcolor=flet.colors.RED, width=self.page.width, height=100000)]
AttributeError: 'NoneType' object has no attribute 'width'
```

**Comment by FeodorFitsner** [comment]
`self.page` is available in `did_mount()` method only: https://github.com/flet-dev/flet/issues/488#issuecomment-1280018830

Control tree is updated with a page instance only after its changes sent to a UI.
