### ISSUE TITLE
Deepcopy failed on _thread.lock

### ISSUE THREAD

**Issue by gjelsas** [flet-dev/flet#565]
I'm trying to build a little board game with a reasonably smart computer opponent. For that, I need deepcopy to find the best next move. Using copy.deepcopy gives me the following error. Any hints for getting this to work would be great! 

Python 3.10 on Ubuntu is in use here...

> Exception in thread Thread-9 (handler):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/georg/.virtualenvs/SteinchenSpiel/lib/python3.10/site-packages/flet/event_handler.py", line 16, in handler
    h(r)
  File "/home/.../gui/MuldenButton.py", line 45, in spiele
    self.board.lasse_computer_ziehen()
  File "/home/.../gui/Spielbrett.py", line 37, in lasse_computer_ziehen
    self.computer_spieler.spiele_zug_mit_meisten_steinen_am_ende()
  File "/home/.../Spieler/AutomatischerSpieler.py", line 17, in spiele_zug_mit_meisten_steinen_am_ende
    sf = deepcopy(self.get_spielfeld())
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  .
.
.
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.lock' object

I skipped some reoccurring lines

**Comment by ndonkoHenri** [comment]
Have you tried googling the error? 
https://www.google.com/search?q=cannot%20pickle%20%27_thread.lock%27%20object

**Comment by gjelsas** [comment]
> Have you tried googling the error? https://www.google.com/search?q=cannot%20pickle%20%27_thread.lock%27%20object

Yes, in fact I did google it, but I'm not sure if it's a general thing caused by the multiprocess nature of flet. 

When I run the Program without GUI, the code is working. When the method with utilizes the deepcopy is called from a flet GUI Button, it crashes with the error mentioned above.  

I guess I need to find a way to omit _thread.lock from being copied or run the whole method single threaded. But I have no clue so far, where to start this endeavor.

**Comment by FeodorFitsner** [comment]
Could you do a simple repro, so we could investigate?

**Comment by gjelsas** [comment]
Here a little working example. The problem is the deepcopy of the ListElementClass object, which is a flet.Text object, I think. 


```
import flet as flet
from flet import Page, AnimatedSwitcher, Text, Container


class ListElementClass(Text):  # Element to be altered inside copied list
    def __init__(self):
        super().__init__(value="Push me!")


list = []
for _ in range(10):
    list.append(ListElementClass())  # Mache Elemente flet Object...


class OtherClass(AnimatedSwitcher):
    class InnerClass(Container):
        def __init__(self, methode):  # Constructor of InnerClass
            super().__init__(content=Text(value=list[0].value), on_click=methode)

    def __init__(self):  # Constructor of OuterClass
        super().__init__(content=OtherClass.InnerClass(methode=self.deepcopy_methode))

    def deepcopy_methode(self, e):
        from copy import deepcopy
        print("Methode invoked")
        copy_of_list = deepcopy(list)


def main(page: Page):
    oc = OtherClass()  # Creating the construct
    page.add(oc)  # adding to the site


flet.app(target=main)
```

By producing this example code, I thought that maybe I should keep the values outside any flet object and store them in a different datastructure to do the deepcopy on that datastructure...

@FeodorFitsner And a word of Thank You for this nice project! I really appreciate your work here.

**Comment by gjelsas** [comment]
So I came up with a solution to this issue. There is a class which is subject to the deepcopy process. This class itself has an attribute self.board which is a flet object. By excluding it from deepcopy, things work like a charm. 

```
def __deepcopy__(self, memo):
        from copy import deepcopy
        cls = self.__class__
        result = cls.__new__(cls)
        memo[id(self)] = result
        for k, v in self.__dict__.items():
            if k != 'board': # here is the trick
                setattr(result, k, deepcopy(v, memo))
        return result
```
I hope my failure will be of help to anybody else. Thanks again for the project and the fast response!

**Comment by ndonkoHenri** [comment]
Issue seems closed. Did you manage to get it fixed?

**Comment by ndonkoHenri** [comment]
So, I just faced this same issue, and I actually confirm that **flet controls can't be deepcopied**. Please @FeodorFitsner investigate on this.
I made this basic code sample to help ease investigations:
```python
import copy
import flet as ft

def main(page: ft.Page):
    text = ft.Text("Hello")
    mycopy = copy.deepcopy(text)

    page.add(
        ft.Text("Hello")
    )


ft.app(target=main)
```

This issue should be reopened. If it can't then I can maybe create another one.

**Comment by FeodorFitsner** [comment]
We could provide a custom `___deepcopy__()` implementation and bypass non-cloneable attributes: https://stackoverflow.com/a/50352368/1435891 - is anyone willing to help with that?

**Comment by ndonkoHenri** [comment]
I will give it a try.
Please what do you mean by "bypass non-cloneable attributes"?

**Comment by FeodorFitsner** [comment]
I mean when you implement `Control.___deepcopy__()` you choose what object fields to clone and you don't clone `self.__lock` and other such things.

**Comment by ndonkoHenri** [comment]
So, I am now on this issue and understand exactly from where the error comes. 
I also now understand what you meant by "bypass non-cloneable attributes".
I found the non-cloneable attribute causing all the problems: `'_lock': <unlocked _thread.lock object at 0x000002AEDF27A340>`
This key, value pair is found in `self.__dict__`
I am willing to "bypass" it, but will like to know it's use, or if it won't cause any issue?

**Comment by ndonkoHenri** [comment]
>I mean when you implement Control.___deepcopy__() you choose what object fields to clone and you don't clone self.__lock and other such things.

Yeah I got it. Will it be alright to leave it out?

**Comment by FeodorFitsner** [comment]
those locks are needed for proper functioning.

**Comment by ndonkoHenri** [comment]
After investigations I happened to come out with this bit of code(which is to be added into the `Control` class - so every control inherits it):
```python
    def __deepcopy__(self, memo):
        """
        It creates a new instance of the class, and then copies all the attributes of the old instance into the new one,
        except for those attributes that can't be deepcopied(ex: _lock).

        :param memo: A dictionary of objects already copied during the current copying pass
        :return: A deep copy of the object.
        """
        cls = self.__class__()
        memo[id(self)] = cls
        for k, v in self.__dict__.items():
            try:
                cls.__dict__[k] = copy.deepcopy(v, memo)
            except TypeError:
                pass
        return cls
```

I tested it on the code below and it worked like charm:
```python
import copy
import flet as ft


def main(page: ft.Page):
    text = ft.Text(
        "Hello from Text",
        size=50,
        color=ft.colors.WHITE,
        bgcolor=ft.colors.GREEN_700,
        weight=ft.FontWeight.BOLD,
        italic=True,
    )

    deepcopy = copy.deepcopy(text)  # make a deepcopy

    print(f"{text=}, \n{deepcopy=}\n")
    print(f"{text.value=},\n{deepcopy.value=}\n")

    def modify(e):
        text.value = "Bye from Text"
        deepcopy.value = "Bye from DEEP Copy"
        page.update()
        print(f"{text.value=}, \n{deepcopy.value=}\n")

    page.add(
        ft.ElevatedButton("Modify", on_click=modify),
        text,
        deepcopy
    )

ft.app(target=main)
```
![deepcopy](https://user-images.githubusercontent.com/98978078/211947108-2f0a6ec0-3997-4e7c-be5d-88d06e0a6247.gif)

But the above solution I made doesn't seem to work as expected with complex controls (the `DataTable` control precisely, which is the only control I need to deepcopy in my usecase - PaginatedDT). I prepared a little code sample below:
```python
import copy
import flet as ft


def main(page: ft.Page):
    page.theme_mode = "light"

    dt = ft.DataTable(
        width=700,
        bgcolor="yellow",
        border=ft.border.all(2, "red"),
        border_radius=10,
        vertical_lines=ft.border.BorderSide(3, "blue"),
        horizontal_lines=ft.border.BorderSide(1, "green"),
        sort_column_index=0,
        sort_ascending=True,
        heading_row_color=ft.colors.BLACK12,
        heading_row_height=100,
        data_row_color={ft.MaterialState.HOVERED: "0x30FF0000"},
        show_checkbox_column=True,
        divider_thickness=0,
        column_spacing=200,
        columns=[
            ft.DataColumn(
                ft.Text("Column 1"),
                on_sort=lambda e: print(f"{e.column_index}, {e.ascending}"),
            ),
            ft.DataColumn(
                ft.Text("Column 2"),
                tooltip="This is a second column",
                numeric=True,
                on_sort=lambda e: print(f"{e.column_index}, {e.ascending}"),
            ),
        ],
        rows=[
            ft.DataRow(
                [ft.DataCell(ft.Text("A")), ft.DataCell(ft.Text("1"))],
                selected=True,
                on_select_changed=lambda e: print(f"row select changed: {e.data}"),
            ),
            ft.DataRow([ft.DataCell(ft.Text("B")), ft.DataCell(ft.Text("2"))]),
        ],
    )

    mycopy = copy.deepcopy(dt)

    print(f"{dt=}, \n{mycopy=}\n")

    page.add(
        dt,
        mycopy
    )


ft.app(target=main)
```
The result could be seen below. The original on the top, and the deepcopied down (the line + checkbox in the middle)
![image](https://user-images.githubusercontent.com/98978078/211945154-960bda98-63cd-4a51-bf1e-8ea83426c9d0.png)

I might keep investigating, but don't know what I can do to properly 'deepcopy' flet controls. I will appreciate some help.

**Comment by FeodorFitsner** [comment]
Implementation looks good to me - I'd probably start with that :)
I guess (just a guess) there are some non covered cases with DataTable, like inner collections? Don't know if `copy.deepcopy()` works agains them automatically. You can investigate on some simpler controls with collections like `Row`, etc.

**Comment by ndonkoHenri** [comment]
I also went on to modify the for loop as follows (in order to see the message in the `TypeError` raised by the `Data**` stuffs);
```python
        for k, v in self.__dict__.items():
            # try:
            if k != "_lock":
                cls.__dict__[k] = copy.deepcopy(v, memo)
            # except TypeError:
            #     print(k, v)
            #     pass
```
And had the below error:
```bash
  File "C:\Users\TheEthicalBoy\venv\Lib\site-packages\flet\control.py", line 460, in __deepcopy__
    cls = self.__class__()
          ^^^^^^^^^^^^^^^^
TypeError: DataColumn.__init__() missing 1 required positional argument: 'label'
```

**Comment by FeodorFitsner** [comment]
My thinking is that you have to override `__deepcopy__()` in `DataColumn` and `DataCell` classes as well.
And maybe filter copying of an attribute with `_lock` name, but instead create a new Lock explicitly.

**Comment by ndonkoHenri** [comment]
I think I have to make a PR so you see how things move.
If creating a new lock won't disturb, How can I create a new lock please?

**Comment by ndonkoHenri** [comment]
Fixed in Flet [Alpha](https://flet.dev/blog/introducing-flet-1-0-alpha#trying-flet-10-alpha), where we now make use of dataclasses to build controls. 

Running the code example from one of my comments above now shows this:
<details><summary>Code</summary>
<p>

```python
import copy
import flet as ft


def main(page: ft.Page):
    page.theme_mode = "light"

    dt = ft.DataTable(
        width=700,
        bgcolor="yellow",
        border=ft.border.all(2, "red"),
        border_radius=10,
        vertical_lines=ft.border.BorderSide(3, "blue"),
        horizontal_lines=ft.border.BorderSide(1, "green"),
        sort_column_index=0,
        sort_ascending=True,
        heading_row_color=ft.colors.BLACK12,
        heading_row_height=100,
        data_row_color={ft.MaterialState.HOVERED: "0x30FF0000"},
        show_checkbox_column=True,
        divider_thickness=0,
        column_spacing=200,
        columns=[
            ft.DataColumn(
                ft.Text("Column 1"),
                on_sort=lambda e: print(f"{e.column_index}, {e.ascending}"),
            ),
            ft.DataColumn(
                ft.Text("Column 2"),
                tooltip="This is a second column",
                numeric=True,
                on_sort=lambda e: print(f"{e.column_index}, {e.ascending}"),
            ),
        ],
        rows=[
            ft.DataRow(
                [ft.DataCell(ft.Text("A")), ft.DataCell(ft.Text("1"))],
                selected=True,
                on_select_changed=lambda e: print(f"row select changed: {e.data}"),
            ),
            ft.DataRow([ft.DataCell(ft.Text("B")), ft.DataCell(ft.Text("2"))]),
        ],
    )

    mycopy = copy.deepcopy(dt)

    page.add(
        dt,
        mycopy
    )


ft.run(target=main)
``` 

</p>
</details> 

<img width="793" height="597" alt="Image" src="https://github.com/user-attachments/assets/67bdd35e-cd7d-402a-8a0e-90dcdca2d77d" />

Interesting note:
```python
print(dt is mycopy)  # False → different objects
print(dt == mycopy)  # True → same contents
```
