### ISSUE TITLE
Issues while importing flet using python 3.9

### ISSUE THREAD

**Issue by snehccurry** [flet-dev/flet#69]
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\TEST\crossplatformappswith_flet_and_flutter\counter.py", line 1, in <module>
    import flet
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flet\__init__.py", line 1, in <module>
    from flet.alert_dialog import AlertDialog
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flet\alert_dialog.py", line 3, in <module>
    from beartype import beartype
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\beartype\__init__.py", line 59, in <module>
    from beartype._decor.main import beartype
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\beartype\_decor\main.py", line 22, in <module>
    from beartype.typing import TYPE_CHECKING
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\beartype\typing\__init__.py", line 329, in <module>
    from beartype.typing._typingpep544 import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\beartype\typing\_typingpep544.py", line 35, in <module>
    from beartype._util.cache.utilcachecall import callable_cached
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\beartype\_util\cache\utilcachecall.py", line 33, in <module>
    from beartype._util.func.arg.utilfuncargtest import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\beartype\_util\func\arg\utilfuncargtest.py", line 16, in <module>
    from beartype._util.func.utilfunccodeobj import get_func_codeobj
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\beartype\_util\func\utilfunccodeobj.py", line 19, in <module>
    from beartype._data.datatyping import Codeobjable, TypeException
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\beartype\_data\datatyping.py", line 85, in <module>
    BeartypeReturn = Union[BeartypeableT, BeartypeConfedDecorator]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\typing.py", line 243, in inner
    return func(*args, **kwds)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'

**Comment by FeodorFitsner** [comment]
What version of Flet module is that? Could you paste the output of `pip list` command please?

**Comment by snehccurry** [comment]
Hey, 
The version is: 
flet             0.1.41

I just installed python3.10 and it seems to work fine, IDK why is it working like that, I tested it with python3.10, I tried using it in a sandbox and it worked, so, now here I am using python3.10, isn't there a support for python 3.9??

**Comment by FeodorFitsner** [comment]
It should work on 3.9 without any issues. I'm currently working on Flet on Windows 11 desktop with Python 3.9.10:

```
PS C:\Projects\flet-dev\flet> python --version
Python 3.9.10
```

though mine installed to `C:\Python39\python.exe`.

**Comment by snehccurry** [comment]
let's see if others have this issue, I don't know why it happened to me, may be due to some broken links/paths, but for me python 3.10 helped, and thanks again.

**Comment by KranzKrone** [comment]
I have the same problem with Python 3.9.1.

**Comment by FeodorFitsner** [comment]
@KranzKrone are you running it on Windows? Would you mind upgrading Python to the latest 3.9.13 and give Flet another try?

**Comment by snehccurry** [comment]
> I have the same problem with Python 3.9.1.

I think the problem is because of the method of importing flet, idk why's that, but this is the error: TypeError: unhashable type: 'list', and ig it is supported in the newest version of python or something, I did try upgrading and it worked for me, I'm using Python 3.10.5

**Comment by KranzKrone** [comment]
@FeodorFitsner Yes I am using Windows. After Update Python to 3.10.5 it working fine now. Thanks

**Comment by snehccurry** [comment]
yeah, same thing with me.
