### ISSUE TITLE
Exception: Could not connected to Flet server in 30 seconds. : FATA[2023-01-12T17:44:42+08:00] listen: listen tcp :80: bind: permission denied

### ISSUE THREAD

**Issue by monkeycc** [flet-dev/flet#864]
```
import flet
import logging
logging.basicConfig(level=logging.DEBUG)

def main(page: flet.Page):
    page.add(flet.Text("Hello, world!"))

ft.app(target=main,port=80,assets_dir="assets", view=ft.WEB_BROWSER)
```

```
Traceback (most recent call last):
  File "/home/ubuntu/WWW/main.py", line 369, in <module>
    ft.app(target=main,port=80,assets_dir="assets", view=ft.WEB_BROWSER)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/flet/flet.py", line 102, in app
    conn = _connect_internal(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/flet/flet.py", line 264, in _connect_internal
    raise Exception(
Exception: Could not connected to Flet server in 30 seconds.
```
```

INFO[2023-01-12T17:44:42+08:00] Starting server on :80                       
INFO[2023-01-12T17:44:42+08:00] Starting background tasks...                 
INFO[2023-01-12T17:44:42+08:00] Start background task to cleanup expired data 
INFO:root:Connecting Flet Server at ws://127.0.0.1:80/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:80/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:80/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:80/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:80/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:80/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:80/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:80/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
FATA[2023-01-12T17:44:42+08:00] listen: listen tcp :80: bind: permission denied
INFO:root:Connecting Flet Server at ws://127.0.0.1:80/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds
INFO:root:Connecting Flet Server at ws://127.0.0.1:80/ws...
DEBUG:root:Exited run_forever()
INFO:root:Reconnecting Flet Server in 0.1 seconds

FATA[2023-01-12T17:44:42+08:00] listen: listen tcp :80: bind: permission denied
```

**Comment by monkeycc** [comment]
sudo ...

Problem solving

No defects
