### ISSUE TITLE
flet pre: client_storage throws not implemented

### ISSUE THREAD

**Issue by gbrandt** [flet-dev/flet#903]
**Description**

page.client_storage.(set, get, remove) all throw a not implemented error in the pre-release

**Code example to reproduce the issue:**

```python
import flet as ft

async def main(page: ft.Page):

    async def on_click(event: ft.ControlEvent):
            event.page.client_storage.set("test", "test")


    await page.add_async( ft.ElevatedButton("Click me", on_click=on_click) )
    await page.update_async()

ft.app(target=main)

```

**Describe the results you received:**

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-9' coro=<__connect_internal_async.<locals>.on_event() done, defined at web_app/lib/python3.11/site-packages/flet/flet.py:346> exception=NotImplementedError()>
Traceback (most recent call last):
  File "/web_app/lib/python3.11/site-packages/flet/flet.py", line 348, in on_event
    await conn.sessions[e.sessionID].on_event_async(
  File "/web_app/lib/python3.11/site-packages/flet_core/page.py", line 459, in on_event_async
    await handler(ce)
  File "/web-app2/test.py", line 6, in on_click
    event.page.client_storage.set("test", "test")
  File "/web_app/lib/python3.11/site-packages/flet_core/client_storage.py", line 13, in set
    self.__page.invoke_method(
  File "/web_app/lib/python3.11/site-packages/flet_core/page.py", line 808, in invoke_method
    result = self._send_command(
             ^^^^^^^^^^^^^^^^^^^
  File "/web_app/lib/python3.11/site-packages/flet_core/page.py", line 675, in _send_command
    return self.__conn.send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/web_app/lib/python3.11/site-packages/flet_core/connection.py", line 19, in send_command
    raise NotImplementedError()
NotImplementedError
```
**Describe the results you expected:**

expected browser to store local client side data

flet version 0.4.0.dev1066

**Operating system**:

macOS 13.1 on a M1 MacBook Pro

**Comment by FeodorFitsner** [comment]
You have to use `_async` storage methods as well:

```python
import flet as ft

async def main(page: ft.Page):

    async def on_click(event: ft.ControlEvent):
            await event.page.client_storage.set_async("test", "test")


    await page.add_async( ft.ElevatedButton("Click me", on_click=on_click) )
    await page.update_async()

ft.app(target=main)
```

Look at this full-featured async example: https://github.com/flet-dev/examples/blob/async-examples/python/apps/authentication/github-oauth-with-listing-repos-async.py

**Comment by gbrandt** [comment]
Ah, ok.  Other non async function actually have an error that says to use the async version, so I did not expect that.
