### ISSUE TITLE
oauthAuthorize exception in desktop mode

### ISSUE THREAD

**Issue by CrinitusFeles** [flet-dev/flet#985]
In release ```0.4.0``` the authentication (specifically for oauth provider) was broken. Using the example for custom OAuth provider from docs https://flet.dev/docs/guides/python/authentication#configuring-a-custom-oauth-provider , where changing ```view=ft.WEB_BROWSER``` to  ```view=ft.FLET_APP``` leads to next exception:
```Exception in thread Thread-4 (login_click):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "X:\flet_test\main.py", line 39, in login_click
    page.login(provider)
  File "X:\venvs\FletVenv\Lib\site-packages\flet_core\page.py", line 542, in login
    result = self._send_command("oauthAuthorize", attrs=auth_attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\venvs\FletVenv\Lib\site-packages\flet_core\page.py", line 674, in _send_command
    return self.__conn.send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\venvs\FletVenv\Lib\site-packages\flet\sync_local_socket_connection.py", line 106, in send_command
    result, message = self._process_command(command)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\venvs\FletVenv\Lib\site-packages\flet_core\local_connection.py", line 89, in _process_command
    raise Exception("Unsupported command: {}".format(command.name))
Exception: Unsupported command: oauthAuthorize
```

In WEB_BROWSER mode and previous version it works fine.

**Comment by FeodorFitsner** [comment]
OAuth is no longer supported in standalone desktop applications, because it... doesn't make any sense as a client needs OAuth Client ID and Client Secret to make auth work.

**Comment by CrinitusFeles** [comment]
I am still a newbie at auth flow but having a self-hosted authentication server like _keycloak_ was very cool having a feature to switch between web and desktop modes out of the box

**Comment by hokaso** [comment]
Respect your choice, but I will adhere to my own thoughts. If other friends encounter similar problems, just refer to this method: https://github.com/hokaso/Fork-flet/9F9C3D5BB1177C184533B70edB66
